name: 'Download compressed artifact'
description: 'Downloads a compressed artifact and decompresses it'

inputs:
  artifact-name:
    description: 'The name of the artifact to download before invoking the command'
    type: string
    required: true
  artifact-path:
    description: 'Destination path for the downloaded artifact'
    type: string
    required: false

runs:
  using: 'composite'
  steps:
    - name: Download artifact
      uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5
      with:
        name: ${{ inputs.artifact-name }}
        path: ${{ inputs.artifact-path }}

    - name: Decompress artifact
      working-directory: ${{ inputs.artifact-path }}
      shell: 'bash'
      env:
        SEVEN_ZIP: ${{ runner.os == 'Windows' && '7z.exe' || '7z'  }}
      run: ${{ env.SEVEN_ZIP }} x -aoa ${{ inputs.artifact-name }}.zip
