name: 'Set up Node'
description: 'Sets up Node.js'

inputs:
  node-version:
    description: 'Version spec of the version to use. Examples: 12.x, 10.15.1, >=10.15.0.'
    type: string
    required: true
    default: '22.x'

runs:
  using: 'composite'
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4

    - name: Setup Node
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'

    - name: Install dependencies
      shell: bash
      run: pnpm install
