image:
  file: .gitpod/.gitpod.Dockerfile

ports:
  - port: 3000
    onOpen: notify
    visibility: public

tasks:
  - name: 'Install Node modules and compile Serenity/JS'
    init: |
        nvm install
        nvm use
        make install compile

  - name: 'Install VSCode Extensions'
    command: |
        echo "Wait for VSCode to boot up..."
        sleep 10
        echo "Installing Cucumber extension..."
        code --install-extension /vscode-extensions/cucumber-official.vsix

  - name: 'Serenity/JS website'
    command: >
      cd documentation/serenity-js.org &&
      npm start

  - name: 'Welcome'
    command: |
      echo "To view the website, go to:"
      gp url 3000

vscode:
  extensions:
    - CucumberOpen.cucumber-official
    - dbaeumer.vscode-eslint
    - eamodio.gitlens
    - EditorConfig.EditorConfig
    - Gruntfuggly.todo-tree
    - streetsidesoftware.code-spell-checker

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: prevent-merge-on-error
    addComment: false
    addBadge: true
