image:
  file: .gitpod/.gitpod.Dockerfile

ports:
  - port: 3000
    onOpen: notify
    visibility: public

tasks:
  - name: 'Install Node modules and compile Serenity/JS'
    init: |
      nvm install
      nvm use
      make install compile
      gp sync-done installation

  - name: 'Install VSCode Extensions'
    command: |
      echo "Wait for VSCode to boot up..."
      sleep 10
      echo "Installing Cucumber extension..."
      code --install-extension /vscode-extensions/cucumber-official.vsix

  - name: 'Serenity/JS website'
    init: gp sync-await installation
    command: >
      cd documentation/serenity-js.org &&
      npm start

  - name: 'Welcome'
    init: |
      echo "Hello! We're getting your workspace ready, just one moment..."
      gp sync-await installation
    command: |
      echo "And we're done! To view the website, go to:"
      gp url 3000

vscode:
  extensions:
    - CucumberOpen.cucumber-official
    - dbaeumer.vscode-eslint
    - eamodio.gitlens
    - EditorConfig.EditorConfig
    - Gruntfuggly.todo-tree
    - streetsidesoftware.code-spell-checker

github:
  prebuilds:
    master: true
    branches: false
    pullRequests: true
    pullRequestsFromForks: false
    addCheck: true
    addComment: false
    addBadge: true
