check-leaks: false
color: true
diff: true
full-trace: true
reporter: mocha-multi
reporter-options: 'mocha-multi=.mocha-reporters.json'
require: 'ts-node/register'
timeout: 10000
v8-stack-trace-limit: 100
node-option:
  - trace-warnings

# Relative to the package root
spec: 'spec/**/*.spec.*'
