packages:
  - examples/*
  - integration/*
  - integration/*/examples/*
  - packages/*
onlyBuiltDependencies:
  - chromedriver
  - cucumber-expressions
  - nx
ignoredBuiltDependencies:
  - core-js
  - core-js-pure
  - dtrace-provider
  - edgedriver
  - es5-ext
  - esbuild
  - geckodriver
