packages:
  - examples/*
  - integration/*
  - packages/*

ignoredBuiltDependencies:
  - core-js
  - core-js-pure
  - dtrace-provider
  - edgedriver
  - es5-ext
  - esbuild
  - geckodriver

onlyBuiltDependencies:
  - chromedriver
  - cucumber-expressions
  - electron
  - nx
