= Serenity/JS

Serenity/JS gives your automated acceptance and regression tests
the scalability of the http://#:[Screenplay Pattern]
and the power of the http://serenity-bdd.info/docs/serenity/#_detailed_description_of_aggregation_reports[Serenity BDD]
reporting.

CAUTION: Serenity/JS is an experimental project.
This means that although you can use it straight away,
its structure and APIs might and most likely will change over the coming weeks.
Is that a problem? We hope not! The feedback from the Community will help us
shape Serenity/JS to your needs so that together we can build the best acceptance
testing library the JavaScript world has seen ;-)

== How does it work?

Serenity/JS is a layer between the



== Show me the code

== How do I use this at work?

== Your feedback matters!





== Technical stack

Serenity/JS is an open source https://nodejs.org/en/about/[node.js] library that aims to make the idea
of https://en.wikipedia.org/wiki/Specification_by_example[living documentation] a reality.

Based on the popular http://serenity-bdd.info/[Serenity BDD for the JVM],
Serenity/JS helps you write cleaner and more maintainable automated acceptance and regression tests faster.
It helps you apply https://en.wikipedia.org/wiki/SOLID_(object-oriented_design)[SOLID]
engineering practices and scale your automated tests easily
thanks to the https://dzone.com/articles/page-objects-refactored-solid-steps-to-the-screenp[Screenplay Pattern].

Serenity uses the test results to produce illustrated, narrative reports that document and describe what your application does and how it works.
Serenity tells you not only what tests have been executed, but more importantly, what requirements have been tested.

One key advantage of using Serenity.js is that you do not have to invest time in building and maintaining your own automation framework,
but you also don't have to drop the tools that you've used before either.
Serenity.js works well with https://github.com/angular/protractor[Protractor] and https://github.com/cucumber/cucumber-js[Cucumber.js].

Although Serenity.js provides strong support for automating web tests using Selenium 2, it's also works very effectively
for non-web tests such as those that exercise web services or even call application code directly.

== Getting started

Have a look at the link:examples/[examples and tutorials] and create your first project now!