window.esdocSearchIndex = [
  [
    "@serenity-js/assertions~ensure",
    "class/src/Ensure.ts~Ensure.html",
    "<span>Ensure</span> <span class=\"search-result-import-path\">@serenity-js/assertions</span>",
    "class"
  ],
  [
    "@serenity-js/assertions/lib/expectations~and",
    "function/index.html#static-function-and",
    "<span>and</span> <span class=\"search-result-import-path\">@serenity-js/assertions/lib/expectations</span>",
    "function"
  ],
  [
    "@serenity-js/assertions/lib/expectations~contain",
    "function/index.html#static-function-contain",
    "<span>contain</span> <span class=\"search-result-import-path\">@serenity-js/assertions/lib/expectations</span>",
    "function"
  ],
  [
    "@serenity-js/assertions/lib/expectations~containatleastoneitemthat",
    "function/index.html#static-function-containAtLeastOneItemThat",
    "<span>containAtLeastOneItemThat</span> <span class=\"search-result-import-path\">@serenity-js/assertions/lib/expectations</span>",
    "function"
  ],
  [
    "@serenity-js/assertions/lib/expectations~containitemswhereeachitem",
    "function/index.html#static-function-containItemsWhereEachItem",
    "<span>containItemsWhereEachItem</span> <span class=\"search-result-import-path\">@serenity-js/assertions/lib/expectations</span>",
    "function"
  ],
  [
    "@serenity-js/assertions/lib/expectations~endswith",
    "function/index.html#static-function-endsWith",
    "<span>endsWith</span> <span class=\"search-result-import-path\">@serenity-js/assertions/lib/expectations</span>",
    "function"
  ],
  [
    "@serenity-js/assertions/lib/expectations~equals",
    "function/index.html#static-function-equals",
    "<span>equals</span> <span class=\"search-result-import-path\">@serenity-js/assertions/lib/expectations</span>",
    "function"
  ],
  [
    "@serenity-js/assertions/lib/expectations~includes",
    "function/index.html#static-function-includes",
    "<span>includes</span> <span class=\"search-result-import-path\">@serenity-js/assertions/lib/expectations</span>",
    "function"
  ],
  [
    "@serenity-js/assertions/lib/expectations~isafter",
    "function/index.html#static-function-isAfter",
    "<span>isAfter</span> <span class=\"search-result-import-path\">@serenity-js/assertions/lib/expectations</span>",
    "function"
  ],
  [
    "@serenity-js/assertions/lib/expectations~isbefore",
    "function/index.html#static-function-isBefore",
    "<span>isBefore</span> <span class=\"search-result-import-path\">@serenity-js/assertions/lib/expectations</span>",
    "function"
  ],
  [
    "@serenity-js/assertions/lib/expectations~isfalse",
    "function/index.html#static-function-isFalse",
    "<span>isFalse</span> <span class=\"search-result-import-path\">@serenity-js/assertions/lib/expectations</span>",
    "function"
  ],
  [
    "@serenity-js/assertions/lib/expectations~isgreaterthan",
    "function/index.html#static-function-isGreaterThan",
    "<span>isGreaterThan</span> <span class=\"search-result-import-path\">@serenity-js/assertions/lib/expectations</span>",
    "function"
  ],
  [
    "@serenity-js/assertions/lib/expectations~islessthan",
    "function/index.html#static-function-isLessThan",
    "<span>isLessThan</span> <span class=\"search-result-import-path\">@serenity-js/assertions/lib/expectations</span>",
    "function"
  ],
  [
    "@serenity-js/assertions/lib/expectations~istrue",
    "function/index.html#static-function-isTrue",
    "<span>isTrue</span> <span class=\"search-result-import-path\">@serenity-js/assertions/lib/expectations</span>",
    "function"
  ],
  [
    "@serenity-js/assertions/lib/expectations~matches",
    "function/index.html#static-function-matches",
    "<span>matches</span> <span class=\"search-result-import-path\">@serenity-js/assertions/lib/expectations</span>",
    "function"
  ],
  [
    "@serenity-js/assertions/lib/expectations~not",
    "function/index.html#static-function-not",
    "<span>not</span> <span class=\"search-result-import-path\">@serenity-js/assertions/lib/expectations</span>",
    "function"
  ],
  [
    "@serenity-js/assertions/lib/expectations~or",
    "function/index.html#static-function-or",
    "<span>or</span> <span class=\"search-result-import-path\">@serenity-js/assertions/lib/expectations</span>",
    "function"
  ],
  [
    "@serenity-js/assertions/lib/expectations~property",
    "function/index.html#static-function-property",
    "<span>property</span> <span class=\"search-result-import-path\">@serenity-js/assertions/lib/expectations</span>",
    "function"
  ],
  [
    "@serenity-js/assertions/lib/expectations~startswith",
    "function/index.html#static-function-startsWith",
    "<span>startsWith</span> <span class=\"search-result-import-path\">@serenity-js/assertions/lib/expectations</span>",
    "function"
  ],
  [
    "@serenity-js/core/lib/errors~assertionerror",
    "/modules/core/class/src/errors/AssertionError.ts~AssertionError.html",
    "@serenity-js/core/lib/errors~AssertionError",
    "external"
  ],
  [
    "@serenity-js/core/lib/errors~configurationerror",
    "/modules/core/class/src/errors/ConfigurationError.ts~ConfigurationError.html",
    "@serenity-js/core/lib/errors~ConfigurationError",
    "external"
  ],
  [
    "@serenity-js/core/lib/errors~implementationpendingerror",
    "/modules/core/class/src/errors/ImplementationPendingError.ts~ImplementationPendingError.html",
    "@serenity-js/core/lib/errors~ImplementationPendingError",
    "external"
  ],
  [
    "@serenity-js/core/lib/errors~logicerror",
    "/modules/core/class/src/errors/LogicError.ts~LogicError.html",
    "@serenity-js/core/lib/errors~LogicError",
    "external"
  ],
  [
    "@serenity-js/core/lib/errors~runtimeerror",
    "/modules/core/class/src/errors/RuntimeError.ts~RuntimeError.html",
    "@serenity-js/core/lib/errors~RuntimeError",
    "external"
  ],
  [
    "@serenity-js/core/lib/errors~testcompromisederror",
    "/modules/core/class/src/errors/TestCompromisedError.ts~TestCompromisedError.html",
    "@serenity-js/core/lib/errors~TestCompromisedError",
    "external"
  ],
  [
    "@serenity-js/core/lib/errors~unknownerror",
    "/modules/core/class/src/errors/UnknownError.ts~UnknownError.html",
    "@serenity-js/core/lib/errors~UnknownError",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~activityfinished",
    "/modules/core/class/src/events/ActivityFinished.ts~ActivityFinished.html",
    "@serenity-js/core/lib/events~ActivityFinished",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~activityrelatedartifactarchived",
    "/modules/core/class/src/events/ActivityRelatedArtifactArchived.ts~ActivityRelatedArtifactArchived.html",
    "@serenity-js/core/lib/events~ActivityRelatedArtifactArchived",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~activityrelatedartifactgenerated",
    "/modules/core/class/src/events/ActivityRelatedArtifactGenerated.ts~ActivityRelatedArtifactGenerated.html",
    "@serenity-js/core/lib/events~ActivityRelatedArtifactGenerated",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~activitystarts",
    "/modules/core/class/src/events/ActivityStarts.ts~ActivityStarts.html",
    "@serenity-js/core/lib/events~ActivityStarts",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~artifactarchived",
    "/modules/core/class/src/events/ArtifactArchived.ts~ArtifactArchived.html",
    "@serenity-js/core/lib/events~ArtifactArchived",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~artifactgenerated",
    "/modules/core/class/src/events/ArtifactGenerated.ts~ArtifactGenerated.html",
    "@serenity-js/core/lib/events~ArtifactGenerated",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~asyncoperationattempted",
    "/modules/core/class/src/events/AsyncOperationAttempted.ts~AsyncOperationAttempted.html",
    "@serenity-js/core/lib/events~AsyncOperationAttempted",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~asyncoperationcompleted",
    "/modules/core/class/src/events/AsyncOperationCompleted.ts~AsyncOperationCompleted.html",
    "@serenity-js/core/lib/events~AsyncOperationCompleted",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~asyncoperationfailed",
    "/modules/core/class/src/events/AsyncOperationFailed.ts~AsyncOperationFailed.html",
    "@serenity-js/core/lib/events~AsyncOperationFailed",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~businessruledetected",
    "/modules/core/class/src/events/BusinessRuleDetected.ts~BusinessRuleDetected.html",
    "@serenity-js/core/lib/events~BusinessRuleDetected",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~domainevent",
    "/modules/core/class/src/events/DomainEvent.ts~DomainEvent.html",
    "@serenity-js/core/lib/events~DomainEvent",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~featurenarrativedetected",
    "/modules/core/class/src/events/FeatureNarrativeDetected.ts~FeatureNarrativeDetected.html",
    "@serenity-js/core/lib/events~FeatureNarrativeDetected",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~interactionfinished",
    "/modules/core/class/src/events/InteractionFinished.ts~InteractionFinished.html",
    "@serenity-js/core/lib/events~InteractionFinished",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~interactionstarts",
    "/modules/core/class/src/events/InteractionStarts.ts~InteractionStarts.html",
    "@serenity-js/core/lib/events~InteractionStarts",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~retryablescenedetected",
    "/modules/core/class/src/events/RetryableSceneDetected.ts~RetryableSceneDetected.html",
    "@serenity-js/core/lib/events~RetryableSceneDetected",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~scenebackgrounddetected",
    "/modules/core/class/src/events/SceneBackgroundDetected.ts~SceneBackgroundDetected.html",
    "@serenity-js/core/lib/events~SceneBackgroundDetected",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~scenedescriptiondetected",
    "/modules/core/class/src/events/SceneDescriptionDetected.ts~SceneDescriptionDetected.html",
    "@serenity-js/core/lib/events~SceneDescriptionDetected",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~scenefinished",
    "/modules/core/class/src/events/SceneFinished.ts~SceneFinished.html",
    "@serenity-js/core/lib/events~SceneFinished",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~scenefinishes",
    "/modules/core/class/src/events/SceneFinishes.ts~SceneFinishes.html",
    "@serenity-js/core/lib/events~SceneFinishes",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~sceneparametersdetected",
    "/modules/core/class/src/events/SceneParametersDetected.ts~SceneParametersDetected.html",
    "@serenity-js/core/lib/events~SceneParametersDetected",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~scenesequencedetected",
    "/modules/core/class/src/events/SceneSequenceDetected.ts~SceneSequenceDetected.html",
    "@serenity-js/core/lib/events~SceneSequenceDetected",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~scenestarts",
    "/modules/core/class/src/events/SceneStarts.ts~SceneStarts.html",
    "@serenity-js/core/lib/events~SceneStarts",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~scenetagged",
    "/modules/core/class/src/events/SceneTagged.ts~SceneTagged.html",
    "@serenity-js/core/lib/events~SceneTagged",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~scenetemplatedetected",
    "/modules/core/class/src/events/SceneTemplateDetected.ts~SceneTemplateDetected.html",
    "@serenity-js/core/lib/events~SceneTemplateDetected",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~taskfinished",
    "/modules/core/class/src/events/TaskFinished.ts~TaskFinished.html",
    "@serenity-js/core/lib/events~TaskFinished",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~taskstarts",
    "/modules/core/class/src/events/TaskStarts.ts~TaskStarts.html",
    "@serenity-js/core/lib/events~TaskStarts",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~testrunfinished",
    "/modules/core/class/src/events/TestRunFinished.ts~TestRunFinished.html",
    "@serenity-js/core/lib/events~TestRunFinished",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~testrunfinishes",
    "/modules/core/class/src/events/TestRunFinishes.ts~TestRunFinishes.html",
    "@serenity-js/core/lib/events~TestRunFinishes",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~testrunstarts",
    "/modules/core/class/src/events/TestRunStarts.ts~TestRunStarts.html",
    "@serenity-js/core/lib/events~TestRunStarts",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~testrunnerdetected",
    "/modules/core/class/src/events/TestRunnerDetected.ts~TestRunnerDetected.html",
    "@serenity-js/core/lib/events~TestRunnerDetected",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~testsuitefinished",
    "/modules/core/class/src/events/TestSuiteFinished.ts~TestSuiteFinished.html",
    "@serenity-js/core/lib/events~TestSuiteFinished",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~testsuitestarts",
    "/modules/core/class/src/events/TestSuiteStarts.ts~TestSuiteStarts.html",
    "@serenity-js/core/lib/events~TestSuiteStarts",
    "external"
  ],
  [
    "@serenity-js/core/lib/io/collections~mappable",
    "/modules/core/class/src/io/collections/mappable.ts~Mappable.html",
    "@serenity-js/core/lib/io/collections~Mappable",
    "external"
  ],
  [
    "@serenity-js/core/lib/io/collections~reducible",
    "/modules/core/class/src/io/collections/reducible.ts~Reducible.html",
    "@serenity-js/core/lib/io/collections~Reducible",
    "external"
  ],
  [
    "@serenity-js/core/lib/io/collections~ismappable",
    "/modules/core/function/index.html#static-function-isMappable",
    "@serenity-js/core/lib/io/collections~isMappable",
    "external"
  ],
  [
    "@serenity-js/core/lib/io/json~parse",
    "/modules/core/function/index.html#static-function-parse",
    "@serenity-js/core/lib/io/json~parse",
    "external"
  ],
  [
    "@serenity-js/core/lib/io/json~stringify",
    "/modules/core/function/index.html#static-function-stringify",
    "@serenity-js/core/lib/io/json~stringify",
    "external"
  ],
  [
    "@serenity-js/core/lib/io/reflection~has",
    "/modules/core/function/index.html#static-function-has",
    "@serenity-js/core/lib/io/reflection~has",
    "external"
  ],
  [
    "@serenity-js/core/lib/io~assertionreportdiffer",
    "/modules/core/class/src/io/AssertionReportDiffer.ts~AssertionReportDiffer.html",
    "@serenity-js/core/lib/io~AssertionReportDiffer",
    "external"
  ],
  [
    "@serenity-js/core/lib/io~config",
    "/modules/core/class/src/io/Config.ts~Config.html",
    "@serenity-js/core/lib/io~Config",
    "external"
  ],
  [
    "@serenity-js/core/lib/io~errorserialiser",
    "/modules/core/class/src/io/ErrorSerialiser.ts~ErrorSerialiser.html",
    "@serenity-js/core/lib/io~ErrorSerialiser",
    "external"
  ],
  [
    "@serenity-js/core/lib/io~filefinder",
    "/modules/core/class/src/io/FileFinder.ts~FileFinder.html",
    "@serenity-js/core/lib/io~FileFinder",
    "external"
  ],
  [
    "@serenity-js/core/lib/io~filesystem",
    "/modules/core/class/src/io/FileSystem.ts~FileSystem.html",
    "@serenity-js/core/lib/io~FileSystem",
    "external"
  ],
  [
    "@serenity-js/core/lib/io~filesystemlocation",
    "/modules/core/class/src/io/FileSystemLocation.ts~FileSystemLocation.html",
    "@serenity-js/core/lib/io~FileSystemLocation",
    "external"
  ],
  [
    "@serenity-js/core/lib/io~moduleloader",
    "/modules/core/class/src/io/ModuleLoader.ts~ModuleLoader.html",
    "@serenity-js/core/lib/io~ModuleLoader",
    "external"
  ],
  [
    "@serenity-js/core/lib/io~outputstream",
    "/modules/core/class/src/io/OutputStream.ts~OutputStream.html",
    "@serenity-js/core/lib/io~OutputStream",
    "external"
  ],
  [
    "@serenity-js/core/lib/io~path",
    "/modules/core/class/src/io/Path.ts~Path.html",
    "@serenity-js/core/lib/io~Path",
    "external"
  ],
  [
    "@serenity-js/core/lib/io~serialisederror",
    "/modules/core/class/src/io/ErrorSerialiser.ts~SerialisedError.html",
    "@serenity-js/core/lib/io~SerialisedError",
    "external"
  ],
  [
    "@serenity-js/core/lib/io~testrunneradapter",
    "/modules/core/class/src/io/TestRunnerAdapter.ts~TestRunnerAdapter.html",
    "@serenity-js/core/lib/io~TestRunnerAdapter",
    "external"
  ],
  [
    "@serenity-js/core/lib/io~version",
    "/modules/core/class/src/io/Version.ts~Version.html",
    "@serenity-js/core/lib/io~Version",
    "external"
  ],
  [
    "@serenity-js/core/lib/io~commaseparated",
    "/modules/core/function/index.html#static-function-commaSeparated",
    "@serenity-js/core/lib/io~commaSeparated",
    "external"
  ],
  [
    "@serenity-js/core/lib/io~formatted",
    "/modules/core/function/index.html#static-function-formatted",
    "@serenity-js/core/lib/io~formatted",
    "external"
  ],
  [
    "@serenity-js/core/lib/io~inspected",
    "/modules/core/function/index.html#static-function-inspected",
    "@serenity-js/core/lib/io~inspected",
    "external"
  ],
  [
    "@serenity-js/core/lib/io~trimmed",
    "/modules/core/function/index.html#static-function-trimmed",
    "@serenity-js/core/lib/io~trimmed",
    "external"
  ],
  [
    "@serenity-js/core/lib/model/artifacts~assertionreport",
    "/modules/core/class/src/model/artifacts/AssertionReport.ts~AssertionReport.html",
    "@serenity-js/core/lib/model/artifacts~AssertionReport",
    "external"
  ],
  [
    "@serenity-js/core/lib/model/artifacts~httprequestresponse",
    "/modules/core/class/src/model/artifacts/HTTPRequestResponse.ts~HTTPRequestResponse.html",
    "@serenity-js/core/lib/model/artifacts~HTTPRequestResponse",
    "external"
  ],
  [
    "@serenity-js/core/lib/model/artifacts~jsondata",
    "/modules/core/class/src/model/artifacts/JSONData.ts~JSONData.html",
    "@serenity-js/core/lib/model/artifacts~JSONData",
    "external"
  ],
  [
    "@serenity-js/core/lib/model/artifacts~logentry",
    "/modules/core/class/src/model/artifacts/LogEntry.ts~LogEntry.html",
    "@serenity-js/core/lib/model/artifacts~LogEntry",
    "external"
  ],
  [
    "@serenity-js/core/lib/model/artifacts~photo",
    "/modules/core/class/src/model/artifacts/Photo.ts~Photo.html",
    "@serenity-js/core/lib/model/artifacts~Photo",
    "external"
  ],
  [
    "@serenity-js/core/lib/model/artifacts~requestandresponse",
    "/modules/core/class/src/model/artifacts/HTTPRequestResponse.ts~RequestAndResponse.html",
    "@serenity-js/core/lib/model/artifacts~RequestAndResponse",
    "external"
  ],
  [
    "@serenity-js/core/lib/model/artifacts~testreport",
    "/modules/core/class/src/model/artifacts/TestReport.ts~TestReport.html",
    "@serenity-js/core/lib/model/artifacts~TestReport",
    "external"
  ],
  [
    "@serenity-js/core/lib/model/artifacts~textdata",
    "/modules/core/class/src/model/artifacts/TextData.ts~TextData.html",
    "@serenity-js/core/lib/model/artifacts~TextData",
    "external"
  ],
  [
    "@serenity-js/core/lib/model/tags~arbitrarytag",
    "/modules/core/class/src/model/tags/ArbitraryTag.ts~ArbitraryTag.html",
    "@serenity-js/core/lib/model/tags~ArbitraryTag",
    "external"
  ],
  [
    "@serenity-js/core/lib/model/tags~browsertag",
    "/modules/core/class/src/model/tags/BrowserTag.ts~BrowserTag.html",
    "@serenity-js/core/lib/model/tags~BrowserTag",
    "external"
  ],
  [
    "@serenity-js/core/lib/model/tags~capabilitytag",
    "/modules/core/class/src/model/tags/CapabilityTag.ts~CapabilityTag.html",
    "@serenity-js/core/lib/model/tags~CapabilityTag",
    "external"
  ],
  [
    "@serenity-js/core/lib/model/tags~contexttag",
    "/modules/core/class/src/model/tags/ContextTag.ts~ContextTag.html",
    "@serenity-js/core/lib/model/tags~ContextTag",
    "external"
  ],
  [
    "@serenity-js/core/lib/model/tags~executionretriedtag",
    "/modules/core/class/src/model/tags/ExecutionRetriedTag.ts~ExecutionRetriedTag.html",
    "@serenity-js/core/lib/model/tags~ExecutionRetriedTag",
    "external"
  ],
  [
    "@serenity-js/core/lib/model/tags~featuretag",
    "/modules/core/class/src/model/tags/FeatureTag.ts~FeatureTag.html",
    "@serenity-js/core/lib/model/tags~FeatureTag",
    "external"
  ],
  [
    "@serenity-js/core/lib/model/tags~issuetag",
    "/modules/core/class/src/model/tags/IssueTag.ts~IssueTag.html",
    "@serenity-js/core/lib/model/tags~IssueTag",
    "external"
  ],
  [
    "@serenity-js/core/lib/model/tags~manualtag",
    "/modules/core/class/src/model/tags/ManualTag.ts~ManualTag.html",
    "@serenity-js/core/lib/model/tags~ManualTag",
    "external"
  ],
  [
    "@serenity-js/core/lib/model/tags~platformtag",
    "/modules/core/class/src/model/tags/PlatformTag.ts~PlatformTag.html",
    "@serenity-js/core/lib/model/tags~PlatformTag",
    "external"
  ],
  [
    "@serenity-js/core/lib/model/tags~tag",
    "/modules/core/class/src/model/tags/Tag.ts~Tag.html",
    "@serenity-js/core/lib/model/tags~Tag",
    "external"
  ],
  [
    "@serenity-js/core/lib/model/tags~themetag",
    "/modules/core/class/src/model/tags/ThemeTag.ts~ThemeTag.html",
    "@serenity-js/core/lib/model/tags~ThemeTag",
    "external"
  ],
  [
    "@serenity-js/core/lib/model~activitydetails",
    "/modules/core/class/src/model/ActivityDetails.ts~ActivityDetails.html",
    "@serenity-js/core/lib/model~ActivityDetails",
    "external"
  ],
  [
    "@serenity-js/core/lib/model~artifact",
    "/modules/core/class/src/model/Artifact.ts~Artifact.html",
    "@serenity-js/core/lib/model~Artifact",
    "external"
  ],
  [
    "@serenity-js/core/lib/model~businessrule",
    "/modules/core/class/src/model/BusinessRule.ts~BusinessRule.html",
    "@serenity-js/core/lib/model~BusinessRule",
    "external"
  ],
  [
    "@serenity-js/core/lib/model~category",
    "/modules/core/class/src/model/Category.ts~Category.html",
    "@serenity-js/core/lib/model~Category",
    "external"
  ],
  [
    "@serenity-js/core/lib/model~correlationid",
    "/modules/core/class/src/model/CorrelationId.ts~CorrelationId.html",
    "@serenity-js/core/lib/model~CorrelationId",
    "external"
  ],
  [
    "@serenity-js/core/lib/model~description",
    "/modules/core/class/src/model/Description.ts~Description.html",
    "@serenity-js/core/lib/model~Description",
    "external"
  ],
  [
    "@serenity-js/core/lib/model~duration",
    "/modules/core/class/src/model/Duration.ts~Duration.html",
    "@serenity-js/core/lib/model~Duration",
    "external"
  ],
  [
    "@serenity-js/core/lib/model~executioncompromised",
    "/modules/core/class/src/model/outcomes.ts~ExecutionCompromised.html",
    "@serenity-js/core/lib/model~ExecutionCompromised",
    "external"
  ],
  [
    "@serenity-js/core/lib/model~executionfailedwithassertionerror",
    "/modules/core/class/src/model/outcomes.ts~ExecutionFailedWithAssertionError.html",
    "@serenity-js/core/lib/model~ExecutionFailedWithAssertionError",
    "external"
  ],
  [
    "@serenity-js/core/lib/model~executionfailedwitherror",
    "/modules/core/class/src/model/outcomes.ts~ExecutionFailedWithError.html",
    "@serenity-js/core/lib/model~ExecutionFailedWithError",
    "external"
  ],
  [
    "@serenity-js/core/lib/model~executionignored",
    "/modules/core/class/src/model/outcomes.ts~ExecutionIgnored.html",
    "@serenity-js/core/lib/model~ExecutionIgnored",
    "external"
  ],
  [
    "@serenity-js/core/lib/model~executionskipped",
    "/modules/core/class/src/model/outcomes.ts~ExecutionSkipped.html",
    "@serenity-js/core/lib/model~ExecutionSkipped",
    "external"
  ],
  [
    "@serenity-js/core/lib/model~executionsuccessful",
    "/modules/core/class/src/model/outcomes.ts~ExecutionSuccessful.html",
    "@serenity-js/core/lib/model~ExecutionSuccessful",
    "external"
  ],
  [
    "@serenity-js/core/lib/model~implementationpending",
    "/modules/core/class/src/model/outcomes.ts~ImplementationPending.html",
    "@serenity-js/core/lib/model~ImplementationPending",
    "external"
  ],
  [
    "@serenity-js/core/lib/model~name",
    "/modules/core/class/src/model/Name.ts~Name.html",
    "@serenity-js/core/lib/model~Name",
    "external"
  ],
  [
    "@serenity-js/core/lib/model~outcome",
    "/modules/core/class/src/model/outcomes.ts~Outcome.html",
    "@serenity-js/core/lib/model~Outcome",
    "external"
  ],
  [
    "@serenity-js/core/lib/model~problemindication",
    "/modules/core/class/src/model/outcomes.ts~ProblemIndication.html",
    "@serenity-js/core/lib/model~ProblemIndication",
    "external"
  ],
  [
    "@serenity-js/core/lib/model~scenariodetails",
    "/modules/core/class/src/model/ScenarioDetails.ts~ScenarioDetails.html",
    "@serenity-js/core/lib/model~ScenarioDetails",
    "external"
  ],
  [
    "@serenity-js/core/lib/model~scenarioparameters",
    "/modules/core/class/src/model/ScenarioParameters.ts~ScenarioParameters.html",
    "@serenity-js/core/lib/model~ScenarioParameters",
    "external"
  ],
  [
    "@serenity-js/core/lib/model~serialisedoutcome",
    "/modules/core/class/src/model/outcomes.ts~SerialisedOutcome.html",
    "@serenity-js/core/lib/model~SerialisedOutcome",
    "external"
  ],
  [
    "@serenity-js/core/lib/model~testsuitedetails",
    "/modules/core/class/src/model/TestSuiteDetails.ts~TestSuiteDetails.html",
    "@serenity-js/core/lib/model~TestSuiteDetails",
    "external"
  ],
  [
    "@serenity-js/core/lib/model~timestamp",
    "/modules/core/class/src/model/Timestamp.ts~Timestamp.html",
    "@serenity-js/core/lib/model~Timestamp",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay/abilities~discardable",
    "/modules/core/class/src/screenplay/abilities/Discardable.ts~Discardable.html",
    "@serenity-js/core/lib/screenplay/abilities~Discardable",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay/abilities~initialisable",
    "/modules/core/class/src/screenplay/abilities/Initialisable.ts~Initialisable.html",
    "@serenity-js/core/lib/screenplay/abilities~Initialisable",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay/abilities~takenotes",
    "/modules/core/class/src/screenplay/abilities/TakeNotes.ts~TakeNotes.html",
    "@serenity-js/core/lib/screenplay/abilities~TakeNotes",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay/actor~actor",
    "/modules/core/class/src/screenplay/actor/Actor.ts~Actor.html",
    "@serenity-js/core/lib/screenplay/actor~Actor",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay/actor~answersquestions",
    "/modules/core/class/src/screenplay/actor/AnswersQuestions.ts~AnswersQuestions.html",
    "@serenity-js/core/lib/screenplay/actor~AnswersQuestions",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay/actor~canhaveabilities",
    "/modules/core/class/src/screenplay/actor/CanHaveAbilities.ts~CanHaveAbilities.html",
    "@serenity-js/core/lib/screenplay/actor~CanHaveAbilities",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay/actor~collectsartifacts",
    "/modules/core/class/src/screenplay/actor/CollectsArtifacts.ts~CollectsArtifacts.html",
    "@serenity-js/core/lib/screenplay/actor~CollectsArtifacts",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay/actor~performsactivities",
    "/modules/core/class/src/screenplay/actor/PerformsActivities.ts~PerformsActivities.html",
    "@serenity-js/core/lib/screenplay/actor~PerformsActivities",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay/actor~usesabilities",
    "/modules/core/class/src/screenplay/actor/UsesAbilities.ts~UsesAbilities.html",
    "@serenity-js/core/lib/screenplay/actor~UsesAbilities",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay/interactions~log",
    "/modules/core/class/src/screenplay/interactions/Log.ts~Log.html",
    "@serenity-js/core/lib/screenplay/interactions~Log",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay/interactions~see",
    "/modules/core/class/src/screenplay/interactions/See.ts~See.html",
    "@serenity-js/core/lib/screenplay/interactions~See",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay/interactions~takenote",
    "/modules/core/class/src/screenplay/interactions/TakeNote.ts~TakeNote.html",
    "@serenity-js/core/lib/screenplay/interactions~TakeNote",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay/questions/expectations~expectationmet",
    "/modules/core/class/src/screenplay/questions/expectations/ExpectationMet.ts~ExpectationMet.html",
    "@serenity-js/core/lib/screenplay/questions/expectations~ExpectationMet",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay/questions/expectations~expectationnotmet",
    "/modules/core/class/src/screenplay/questions/expectations/ExpectationNotMet.ts~ExpectationNotMet.html",
    "@serenity-js/core/lib/screenplay/questions/expectations~ExpectationNotMet",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay/questions/expectations~expectationoutcome",
    "/modules/core/class/src/screenplay/questions/expectations/ExpectationOutcome.ts~ExpectationOutcome.html",
    "@serenity-js/core/lib/screenplay/questions/expectations~ExpectationOutcome",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay/questions/lists~arraylistadapter",
    "/modules/core/class/src/screenplay/questions/lists/ArrayListAdapter.ts~ArrayListAdapter.html",
    "@serenity-js/core/lib/screenplay/questions/lists~ArrayListAdapter",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay/questions/lists~listadapter",
    "/modules/core/class/src/screenplay/questions/lists/ListAdapter.ts~ListAdapter.html",
    "@serenity-js/core/lib/screenplay/questions/lists~ListAdapter",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay/questions/mappings/string~append",
    "/modules/core/function/index.html#static-function-append",
    "@serenity-js/core/lib/screenplay/questions/mappings/string~append",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay/questions/mappings/string~normalize",
    "/modules/core/function/index.html#static-function-normalize",
    "@serenity-js/core/lib/screenplay/questions/mappings/string~normalize",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay/questions/mappings/string~replace",
    "/modules/core/function/index.html#static-function-replace",
    "@serenity-js/core/lib/screenplay/questions/mappings/string~replace",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay/questions/mappings/string~slice",
    "/modules/core/function/index.html#static-function-slice",
    "@serenity-js/core/lib/screenplay/questions/mappings/string~slice",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay/questions/mappings/string~split",
    "/modules/core/function/index.html#static-function-split",
    "@serenity-js/core/lib/screenplay/questions/mappings/string~split",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay/questions/mappings/string~tolocalelowercase",
    "/modules/core/function/index.html#static-function-toLocaleLowerCase",
    "@serenity-js/core/lib/screenplay/questions/mappings/string~toLocaleLowerCase",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay/questions/mappings/string~tolocaleuppercase",
    "/modules/core/function/index.html#static-function-toLocaleUpperCase",
    "@serenity-js/core/lib/screenplay/questions/mappings/string~toLocaleUpperCase",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay/questions/mappings/string~tolowercase",
    "/modules/core/function/index.html#static-function-toLowerCase",
    "@serenity-js/core/lib/screenplay/questions/mappings/string~toLowerCase",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay/questions/mappings/string~tonumber",
    "/modules/core/function/index.html#static-function-toNumber",
    "@serenity-js/core/lib/screenplay/questions/mappings/string~toNumber",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay/questions/mappings/string~touppercase",
    "/modules/core/function/index.html#static-function-toUpperCase",
    "@serenity-js/core/lib/screenplay/questions/mappings/string~toUpperCase",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay/questions/mappings/string~trim",
    "/modules/core/function/index.html#static-function-trim",
    "@serenity-js/core/lib/screenplay/questions/mappings/string~trim",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay/questions~check",
    "/modules/core/class/src/screenplay/questions/Check.ts~Check.html",
    "@serenity-js/core/lib/screenplay/questions~Check",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay/questions~expectation",
    "/modules/core/class/src/screenplay/questions/Expectation.ts~Expectation.html",
    "@serenity-js/core/lib/screenplay/questions~Expectation",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay/questions~list",
    "/modules/core/class/src/screenplay/questions/List.ts~List.html",
    "@serenity-js/core/lib/screenplay/questions~List",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay/questions~metaquestion",
    "/modules/core/class/src/screenplay/questions/MetaQuestion.ts~MetaQuestion.html",
    "@serenity-js/core/lib/screenplay/questions~MetaQuestion",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay/questions~note",
    "/modules/core/class/src/screenplay/questions/Note.ts~Note.html",
    "@serenity-js/core/lib/screenplay/questions~Note",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay/questions~property",
    "/modules/core/class/src/screenplay/questions/Property.ts~Property.html",
    "@serenity-js/core/lib/screenplay/questions~Property",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay/questions~transform",
    "/modules/core/class/src/screenplay/questions/Transform.ts~Transform.html",
    "@serenity-js/core/lib/screenplay/questions~Transform",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay/questions~q",
    "/modules/core/function/index.html#static-function-q",
    "@serenity-js/core/lib/screenplay/questions~q",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay/tasks~loop",
    "/modules/core/class/src/screenplay/tasks/Loop.ts~Loop.html",
    "@serenity-js/core/lib/screenplay/tasks~Loop",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay~ability",
    "/modules/core/class/src/screenplay/Ability.ts~Ability.html",
    "@serenity-js/core/lib/screenplay~Ability",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay~abilitytype",
    "/modules/core/class/src/screenplay/AbilityType.ts~AbilityType.html",
    "@serenity-js/core/lib/screenplay~AbilityType",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay~activity",
    "/modules/core/class/src/screenplay/Activity.ts~Activity.html",
    "@serenity-js/core/lib/screenplay~Activity",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay~interaction",
    "/modules/core/class/src/screenplay/Interaction.ts~Interaction.html",
    "@serenity-js/core/lib/screenplay~Interaction",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay~question",
    "/modules/core/class/src/screenplay/Question.ts~Question.html",
    "@serenity-js/core/lib/screenplay~Question",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay~task",
    "/modules/core/class/src/screenplay/Task.ts~Task.html",
    "@serenity-js/core/lib/screenplay~Task",
    "external"
  ],
  [
    "@serenity-js/core/lib/stage/crew/artifact-archiver~artifactarchiver",
    "/modules/core/class/src/stage/crew/artifact-archiver/ArtifactArchiver.ts~ArtifactArchiver.html",
    "@serenity-js/core/lib/stage/crew/artifact-archiver~ArtifactArchiver",
    "external"
  ],
  [
    "@serenity-js/core/lib/stage/crew/stream-reporter~streamreporter",
    "/modules/core/class/src/stage/crew/stream-reporter/StreamReporter.ts~StreamReporter.html",
    "@serenity-js/core/lib/stage/crew/stream-reporter~StreamReporter",
    "external"
  ],
  [
    "@serenity-js/core/lib/stage~cast",
    "/modules/core/class/src/stage/Cast.ts~Cast.html",
    "@serenity-js/core/lib/stage~Cast",
    "external"
  ],
  [
    "@serenity-js/core/lib/stage~clock",
    "/modules/core/class/src/stage/Clock.ts~Clock.html",
    "@serenity-js/core/lib/stage~Clock",
    "external"
  ],
  [
    "@serenity-js/core/lib/stage~dressingroom",
    "/modules/core/class/src/stage/DressingRoom.ts~DressingRoom.html",
    "@serenity-js/core/lib/stage~DressingRoom",
    "external"
  ],
  [
    "@serenity-js/core/lib/stage~listenstodomainevents",
    "/modules/core/class/src/stage/ListensToDomainEvents.ts~ListensToDomainEvents.html",
    "@serenity-js/core/lib/stage~ListensToDomainEvents",
    "external"
  ],
  [
    "@serenity-js/core/lib/stage~stage",
    "/modules/core/class/src/stage/Stage.ts~Stage.html",
    "@serenity-js/core/lib/stage~Stage",
    "external"
  ],
  [
    "@serenity-js/core/lib/stage~stagecrewmember",
    "/modules/core/class/src/stage/StageCrewMember.ts~StageCrewMember.html",
    "@serenity-js/core/lib/stage~StageCrewMember",
    "external"
  ],
  [
    "@serenity-js/core/lib/stage~stagecrewmemberbuilder",
    "/modules/core/class/src/stage/StageCrewMemberBuilder.ts~StageCrewMemberBuilder.html",
    "@serenity-js/core/lib/stage~StageCrewMemberBuilder",
    "external"
  ],
  [
    "@serenity-js/core/lib/stage~stagecrewmemberbuilderdependencies",
    "/modules/core/class/src/stage/StageCrewMemberBuilderDependencies.ts~StageCrewMemberBuilderDependencies.html",
    "@serenity-js/core/lib/stage~StageCrewMemberBuilderDependencies",
    "external"
  ],
  [
    "@serenity-js/core/lib/stage~stagemanager",
    "/modules/core/class/src/stage/StageManager.ts~StageManager.html",
    "@serenity-js/core/lib/stage~StageManager",
    "external"
  ],
  [
    "@serenity-js/core/lib/stage~withstage",
    "/modules/core/class/src/stage/WithStage.ts~WithStage.html",
    "@serenity-js/core/lib/stage~WithStage",
    "external"
  ],
  [
    "@serenity-js/core~serenity",
    "/modules/core/class/src/Serenity.ts~Serenity.html",
    "@serenity-js/core~Serenity",
    "external"
  ],
  [
    "@serenity-js/core~serenityconfig",
    "/modules/core/class/src/SerenityConfig.ts~SerenityConfig.html",
    "@serenity-js/core~SerenityConfig",
    "external"
  ],
  [
    "@serenity-js/core~actorcalled",
    "/modules/core/function/index.html#static-function-actorCalled",
    "@serenity-js/core~actorCalled",
    "external"
  ],
  [
    "@serenity-js/core~actorinthespotlight",
    "/modules/core/function/index.html#static-function-actorInTheSpotlight",
    "@serenity-js/core~actorInTheSpotlight",
    "external"
  ],
  [
    "@serenity-js/core~configure",
    "/modules/core/function/index.html#static-function-configure",
    "@serenity-js/core~configure",
    "external"
  ],
  [
    "@serenity-js/core~engage",
    "/modules/core/function/index.html#static-function-engage",
    "@serenity-js/core~engage",
    "external"
  ],
  [
    "@serenity-js/core~serenity",
    "/modules/core/variable/src/instance.ts~serenity.html",
    "@serenity-js/core~serenity",
    "external"
  ],
  [
    "@wdio/types~browser",
    "https://github.com/webdriverio/webdriverio/blob/main/packages/webdriverio/src/types.ts",
    "@wdio/types~Browser",
    "external"
  ],
  [
    "@wdio/types~element",
    "https://github.com/webdriverio/webdriverio/blob/main/packages/webdriverio/src/types.ts",
    "@wdio/types~Element",
    "external"
  ],
  [
    "@wdio/types~elementarray",
    "https://github.com/webdriverio/webdriverio/blob/main/packages/webdriverio/src/types.ts",
    "@wdio/types~ElementArray",
    "external"
  ],
  [
    "@wdio/types~options.testrunner",
    "https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-types/src/Options.ts",
    "@wdio/types~Options.TestRunner",
    "external"
  ],
  [
    "axioserror",
    "https://github.com/axios/axios/blob/v0.21.1/index.d.ts#L85",
    "AxiosError",
    "external"
  ],
  [
    "axiosinstance",
    "https://github.com/axios/axios/blob/v0.21.1/index.d.ts#L130",
    "AxiosInstance",
    "external"
  ],
  [
    "axiospromise",
    "https://github.com/axios/axios/blob/v0.21.1/index.d.ts#L94",
    "AxiosPromise",
    "external"
  ],
  [
    "axiosrequestconfig",
    "https://github.com/axios/axios/blob/v0.21.1/index.d.ts#L44",
    "AxiosRequestConfig",
    "external"
  ],
  [
    "axiosresponse",
    "https://github.com/axios/axios/blob/v0.21.1/index.d.ts#L76",
    "AxiosResponse",
    "external"
  ],
  [
    "elementarrayfinder",
    "https://www.protractortest.org/#/api?view=ElementArrayFinder",
    "ElementArrayFinder",
    "external"
  ],
  [
    "elementfinder",
    "https://www.protractortest.org/#/api?view=ElementFinder",
    "ElementFinder",
    "external"
  ],
  [
    "ensure src/ensure.ts~ensure,ensure",
    "test-file/spec/Ensure.spec.ts.html#lineNumber13",
    "Ensure",
    "test"
  ],
  [
    "ensure.that src/ensure.ts~ensure.that,ensure.that",
    "test-file/spec/Ensure.spec.ts.html#lineNumber16",
    "Ensure allows the actor to make an assertion",
    "test"
  ],
  [
    "ensure.that src/ensure.ts~ensure.that,ensure.that",
    "test-file/spec/Ensure.spec.ts.html#lineNumber57",
    "Ensure complains when given an Expectation that doesn't conform to the interface",
    "test"
  ],
  [
    "",
    "test-file/spec/Ensure.spec.ts.html#lineNumber150",
    "Ensure custom errors",
    "test"
  ],
  [
    "",
    "test-file/spec/Ensure.spec.ts.html#lineNumber165",
    "Ensure custom errors allows the actor to fail the flow with a custom RuntimeError with a custom error message",
    "test"
  ],
  [
    "",
    "test-file/spec/Ensure.spec.ts.html#lineNumber152",
    "Ensure custom errors allows the actor to fail the flow with a custom RuntimeError, embedding the original error",
    "test"
  ],
  [
    "ensure.that src/ensure.ts~ensure.that,ensure.that",
    "test-file/spec/Ensure.spec.ts.html#lineNumber23",
    "Ensure fails the actor flow when the assertion is not met",
    "test"
  ],
  [
    "ensure.that src/ensure.ts~ensure.that,ensure.that",
    "test-file/spec/Ensure.spec.ts.html#lineNumber30",
    "Ensure provides a description of the assertion being made",
    "test"
  ],
  [
    "ensure.that src/ensure.ts~ensure.that,ensure.that",
    "test-file/spec/Ensure.spec.ts.html#lineNumber35",
    "Ensure provides a description of the assertion being made, while correctly cleaning the output from new line characters",
    "test"
  ],
  [
    "",
    "test-file/spec/Ensure.spec.ts.html#lineNumber93",
    "Ensure when emitting an artifact",
    "test"
  ],
  [
    "expectation @serenity-js/core/lib/screenplay/questions~expectation,expectation",
    "test-file/spec/Expectation.spec.ts.html#lineNumber11",
    "Expectation",
    "test"
  ],
  [
    "",
    "test-file/spec/Expectation.spec.ts.html#lineNumber48",
    "Expectation allows to alias an expectation, so that the alias",
    "test"
  ],
  [
    "expectation.to expectation.to,expectation.to",
    "test-file/spec/Expectation.spec.ts.html#lineNumber72",
    "Expectation allows to alias an expectation, so that the alias contributes to a human-readable description",
    "test"
  ],
  [
    "expectation.to expectation.to,expectation.to",
    "test-file/spec/Expectation.spec.ts.html#lineNumber78",
    "Expectation allows to alias an expectation, so that the alias provides a precise failure message when the expectation is not met",
    "test"
  ],
  [
    "",
    "test-file/spec/Expectation.spec.ts.html#lineNumber13",
    "Expectation allows to easily define an assertion, which",
    "test"
  ],
  [
    "expectation.that ensure.that expectation.that,expectation.that src/ensure.ts~ensure.that,ensure.that",
    "test-file/spec/Expectation.spec.ts.html#lineNumber19",
    "Expectation allows to easily define an assertion, which allows the actor flow to continue when the assertion passes",
    "test"
  ],
  [
    "expectation.that ensure.that expectation.that,expectation.that src/ensure.ts~ensure.that,ensure.that",
    "test-file/spec/Expectation.spec.ts.html#lineNumber29",
    "Expectation allows to easily define an assertion, which stops the actor flow when the assertion fails",
    "test"
  ],
  [
    "",
    "test-file/spec/Expectation.spec.ts.html#lineNumber85",
    "Expectation allows to override the description of an expectation, so that the new version",
    "test"
  ],
  [
    "expectation.to expectation.to,expectation.to",
    "test-file/spec/Expectation.spec.ts.html#lineNumber113",
    "Expectation allows to override the description of an expectation, so that the new version provides a precise failure message when the expectation is not met",
    "test"
  ],
  [
    "expectation.to expectation.to,expectation.to",
    "test-file/spec/Expectation.spec.ts.html#lineNumber107",
    "Expectation allows to override the description of an expectation, so that the new version replaces the old description",
    "test"
  ],
  [
    "protractorbrowser",
    "https://www.protractortest.org/#/api?view=ProtractorBrowser",
    "ProtractorBrowser",
    "external"
  ],
  [
    "proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "Proxy",
    "external"
  ],
  [
    "",
    "test-file/spec/expectations/and.spec.ts.html#lineNumber8",
    "and",
    "test"
  ],
  [
    "and src/expectations/and.ts~and,and",
    "test-file/spec/expectations/and.spec.ts.html#lineNumber11",
    "and allows for the actor flow to continue when the \"actual\" meets all the expectations",
    "test"
  ],
  [
    "",
    "test-file/spec/expectations/and.spec.ts.html#lineNumber17",
    "and breaks the actor flow when \"actual\"",
    "test"
  ],
  [
    "and src/expectations/and.ts~and,and",
    "test-file/spec/expectations/and.spec.ts.html#lineNumber20",
    "and breaks the actor flow when \"actual\" does not meet the first expectation",
    "test"
  ],
  [
    "and src/expectations/and.ts~and,and",
    "test-file/spec/expectations/and.spec.ts.html#lineNumber31",
    "and breaks the actor flow when \"actual\" does not meet the second expectation",
    "test"
  ],
  [
    "and src/expectations/and.ts~and,and",
    "test-file/spec/expectations/and.spec.ts.html#lineNumber43",
    "and contributes to a human-readable description",
    "test"
  ],
  [
    "",
    "test-file/spec/expectations/contain.spec.ts.html#lineNumber8",
    "contain",
    "test"
  ],
  [
    "contain src/expectations/contain.ts~contain,contain",
    "test-file/spec/expectations/contain.spec.ts.html#lineNumber10",
    "contain allows for the actor flow to continue when the \"actual\" contains the \"expected\" text",
    "test"
  ],
  [
    "contain src/expectations/contain.ts~contain,contain",
    "test-file/spec/expectations/contain.spec.ts.html#lineNumber17",
    "contain breaks the actor flow when \"actual\" does not contain the \"expected\" text",
    "test"
  ],
  [
    "contain src/expectations/contain.ts~contain,contain",
    "test-file/spec/expectations/contain.spec.ts.html#lineNumber28",
    "contain contributes to a human-readable description",
    "test"
  ],
  [
    "",
    "test-file/spec/expectations/containAtLeastOneItemThat.spec.ts.html#lineNumber8",
    "containAtLeastOneItemThat",
    "test"
  ],
  [
    "containatleastoneitemthat src/expectations/containatleastoneitemthat.ts~containatleastoneitemthat,containatleastoneitemthat",
    "test-file/spec/expectations/containAtLeastOneItemThat.spec.ts.html#lineNumber11",
    "containAtLeastOneItemThat allows for the actor flow to continue when the \"actual\" includes at least one item that meets the expectation",
    "test"
  ],
  [
    "containatleastoneitemthat src/expectations/containatleastoneitemthat.ts~containatleastoneitemthat,containatleastoneitemthat",
    "test-file/spec/expectations/containAtLeastOneItemThat.spec.ts.html#lineNumber18",
    "containAtLeastOneItemThat breaks the actor flow when \"actual\" does not include at least one item that meets the expectation",
    "test"
  ],
  [
    "containatleastoneitemthat src/expectations/containatleastoneitemthat.ts~containatleastoneitemthat,containatleastoneitemthat",
    "test-file/spec/expectations/containAtLeastOneItemThat.spec.ts.html#lineNumber29",
    "containAtLeastOneItemThat breaks the actor flow when \"actual\" is an empty list",
    "test"
  ],
  [
    "atleastone atleastone,atleastone",
    "test-file/spec/expectations/containAtLeastOneItemThat.spec.ts.html#lineNumber40",
    "containAtLeastOneItemThat contributes to a human-readable description",
    "test"
  ],
  [
    "",
    "test-file/spec/expectations/containItemsWhereEachItem.spec.ts.html#lineNumber8",
    "containItemsWhereEachItem",
    "test"
  ],
  [
    "containitemswhereeachitem src/expectations/containitemswhereeachitem.ts~containitemswhereeachitem,containitemswhereeachitem",
    "test-file/spec/expectations/containItemsWhereEachItem.spec.ts.html#lineNumber11",
    "containItemsWhereEachItem allows for the actor flow to continue when the \"actual\" includes only those items that meet the expectation",
    "test"
  ],
  [
    "containitemswhereeachitem src/expectations/containitemswhereeachitem.ts~containitemswhereeachitem,containitemswhereeachitem",
    "test-file/spec/expectations/containItemsWhereEachItem.spec.ts.html#lineNumber18",
    "containItemsWhereEachItem breaks the actor flow when \"actual\" contains at least one item that does not meet the expectation",
    "test"
  ],
  [
    "containitemswhereeachitem src/expectations/containitemswhereeachitem.ts~containitemswhereeachitem,containitemswhereeachitem",
    "test-file/spec/expectations/containItemsWhereEachItem.spec.ts.html#lineNumber29",
    "containItemsWhereEachItem breaks the actor flow when \"actual\" is an empty list",
    "test"
  ],
  [
    "atleastone atleastone,atleastone",
    "test-file/spec/expectations/containItemsWhereEachItem.spec.ts.html#lineNumber40",
    "containItemsWhereEachItem contributes to a human-readable description",
    "test"
  ],
  [
    "",
    "test-file/spec/expectations/endsWith.spec.ts.html#lineNumber8",
    "endsWith",
    "test"
  ],
  [
    "endswith src/expectations/endswith.ts~endswith,endswith",
    "test-file/spec/expectations/endsWith.spec.ts.html#lineNumber11",
    "endsWith allows for the actor flow to continue when the \"actual\" ends with \"expected\"",
    "test"
  ],
  [
    "endswith src/expectations/endswith.ts~endswith,endswith",
    "test-file/spec/expectations/endsWith.spec.ts.html#lineNumber18",
    "endsWith breaks the actor flow when \"actual\" does not end with \"expected\"",
    "test"
  ],
  [
    "endswith src/expectations/endswith.ts~endswith,endswith",
    "test-file/spec/expectations/endsWith.spec.ts.html#lineNumber29",
    "endsWith contributes to a human-readable description",
    "test"
  ],
  [
    "equals src/expectations/equals.ts~equals,equals",
    "test-file/spec/expectations/equals.spec.ts.html#lineNumber11",
    "equals",
    "test"
  ],
  [
    "equals src/expectations/equals.ts~equals,equals",
    "test-file/spec/expectations/equals.spec.ts.html#lineNumber38",
    "equals breaks the actor flow when the values of \"actual\" and \"expected\" don't match",
    "test"
  ],
  [
    "equals src/expectations/equals.ts~equals,equals",
    "test-file/spec/expectations/equals.spec.ts.html#lineNumber49",
    "equals contributes to a human-readable description",
    "test"
  ],
  [
    "",
    "test-file/spec/expectations/property.spec.ts.html#lineNumber8",
    "hasProperty",
    "test"
  ],
  [
    "hasproperty hasproperty,hasproperty",
    "test-file/spec/expectations/property.spec.ts.html#lineNumber11",
    "hasProperty allows for the actor flow to continue when the \"actual\" has a property that meets the expectation",
    "test"
  ],
  [
    "hasproperty hasproperty,hasproperty",
    "test-file/spec/expectations/property.spec.ts.html#lineNumber18",
    "hasProperty breaks the actor flow when \"actual\" does not have a property that meets the expectation",
    "test"
  ],
  [
    "hasproperty hasproperty,hasproperty",
    "test-file/spec/expectations/property.spec.ts.html#lineNumber29",
    "hasProperty contributes to a human-readable description",
    "test"
  ],
  [
    "",
    "test-file/spec/expectations/includes.spec.ts.html#lineNumber8",
    "includes",
    "test"
  ],
  [
    "includes src/expectations/includes.ts~includes,includes",
    "test-file/spec/expectations/includes.spec.ts.html#lineNumber11",
    "includes allows for the actor flow to continue when the \"actual\" includes the \"expected\" text",
    "test"
  ],
  [
    "includes src/expectations/includes.ts~includes,includes",
    "test-file/spec/expectations/includes.spec.ts.html#lineNumber18",
    "includes breaks the actor flow when \"actual\" does not include the \"expected\" text",
    "test"
  ],
  [
    "includes src/expectations/includes.ts~includes,includes",
    "test-file/spec/expectations/includes.spec.ts.html#lineNumber29",
    "includes contributes to a human-readable description",
    "test"
  ],
  [
    "",
    "test-file/spec/expectations/isAfter.spec.ts.html#lineNumber8",
    "isAfter",
    "test"
  ],
  [
    "isafter src/expectations/isafter.ts~isafter,isafter",
    "test-file/spec/expectations/isAfter.spec.ts.html#lineNumber11",
    "isAfter allows for the actor flow to continue when the \"actual\" is after the \"expected\"",
    "test"
  ],
  [
    "isafter src/expectations/isafter.ts~isafter,isafter",
    "test-file/spec/expectations/isAfter.spec.ts.html#lineNumber18",
    "isAfter breaks the actor flow when \"actual\" is not after the \"expected\"",
    "test"
  ],
  [
    "isafter src/expectations/isafter.ts~isafter,isafter",
    "test-file/spec/expectations/isAfter.spec.ts.html#lineNumber29",
    "isAfter contributes to a human-readable description",
    "test"
  ],
  [
    "",
    "test-file/spec/expectations/isBefore.spec.ts.html#lineNumber8",
    "isBefore",
    "test"
  ],
  [
    "isbefore src/expectations/isbefore.ts~isbefore,isbefore",
    "test-file/spec/expectations/isBefore.spec.ts.html#lineNumber11",
    "isBefore allows for the actor flow to continue when the \"actual\" is before the \"expected\"",
    "test"
  ],
  [
    "isbefore src/expectations/isbefore.ts~isbefore,isbefore",
    "test-file/spec/expectations/isBefore.spec.ts.html#lineNumber18",
    "isBefore breaks the actor flow when \"actual\" is not before the \"expected\"",
    "test"
  ],
  [
    "isbefore src/expectations/isbefore.ts~isbefore,isbefore",
    "test-file/spec/expectations/isBefore.spec.ts.html#lineNumber29",
    "isBefore contributes to a human-readable description",
    "test"
  ],
  [
    "",
    "test-file/spec/expectations/isFalse.spec.ts.html#lineNumber8",
    "isFalse",
    "test"
  ],
  [
    "isfalse src/expectations/isfalse.ts~isfalse,isfalse",
    "test-file/spec/expectations/isFalse.spec.ts.html#lineNumber11",
    "isFalse allows for the actor flow to continue when the \"actual\" is false",
    "test"
  ],
  [
    "isfalse src/expectations/isfalse.ts~isfalse,isfalse",
    "test-file/spec/expectations/isFalse.spec.ts.html#lineNumber18",
    "isFalse breaks the actor flow when \"actual\" is not false",
    "test"
  ],
  [
    "isfalse src/expectations/isfalse.ts~isfalse,isfalse",
    "test-file/spec/expectations/isFalse.spec.ts.html#lineNumber29",
    "isFalse contributes to a human-readable description",
    "test"
  ],
  [
    "",
    "test-file/spec/expectations/isGreaterThan.spec.ts.html#lineNumber8",
    "isGreaterThan",
    "test"
  ],
  [
    "isgreaterthan src/expectations/isgreaterthan.ts~isgreaterthan,isgreaterthan",
    "test-file/spec/expectations/isGreaterThan.spec.ts.html#lineNumber11",
    "isGreaterThan allows for the actor flow to continue when the \"actual\" is greater than \"expected\"",
    "test"
  ],
  [
    "isgreaterthan src/expectations/isgreaterthan.ts~isgreaterthan,isgreaterthan",
    "test-file/spec/expectations/isGreaterThan.spec.ts.html#lineNumber18",
    "isGreaterThan breaks the actor flow when \"actual\" is not greater than \"expected\"",
    "test"
  ],
  [
    "isgreaterthan src/expectations/isgreaterthan.ts~isgreaterthan,isgreaterthan",
    "test-file/spec/expectations/isGreaterThan.spec.ts.html#lineNumber29",
    "isGreaterThan contributes to a human-readable description",
    "test"
  ],
  [
    "",
    "test-file/spec/expectations/isLessThan.spec.ts.html#lineNumber8",
    "isLessThan",
    "test"
  ],
  [
    "islessthan src/expectations/islessthan.ts~islessthan,islessthan",
    "test-file/spec/expectations/isLessThan.spec.ts.html#lineNumber11",
    "isLessThan allows for the actor flow to continue when the \"actual\" is less than \"expected\"",
    "test"
  ],
  [
    "islessthan src/expectations/islessthan.ts~islessthan,islessthan",
    "test-file/spec/expectations/isLessThan.spec.ts.html#lineNumber18",
    "isLessThan breaks the actor flow when \"actual\" is not less than \"expected\"",
    "test"
  ],
  [
    "islessthan src/expectations/islessthan.ts~islessthan,islessthan",
    "test-file/spec/expectations/isLessThan.spec.ts.html#lineNumber29",
    "isLessThan contributes to a human-readable description",
    "test"
  ],
  [
    "",
    "test-file/spec/expectations/isTrue.spec.ts.html#lineNumber8",
    "isTrue",
    "test"
  ],
  [
    "istrue src/expectations/istrue.ts~istrue,istrue",
    "test-file/spec/expectations/isTrue.spec.ts.html#lineNumber11",
    "isTrue allows for the actor flow to continue when the \"actual\" is true",
    "test"
  ],
  [
    "istrue src/expectations/istrue.ts~istrue,istrue",
    "test-file/spec/expectations/isTrue.spec.ts.html#lineNumber18",
    "isTrue breaks the actor flow when \"actual\" is not true",
    "test"
  ],
  [
    "istrue src/expectations/istrue.ts~istrue,istrue",
    "test-file/spec/expectations/isTrue.spec.ts.html#lineNumber29",
    "isTrue contributes to a human-readable description",
    "test"
  ],
  [
    "",
    "test-file/spec/expectations/matches.spec.ts.html#lineNumber8",
    "matches",
    "test"
  ],
  [
    "matches src/expectations/matches.ts~matches,matches",
    "test-file/spec/expectations/matches.spec.ts.html#lineNumber11",
    "matches allows for the actor flow to continue when the \"actual\" matches the \"expected\"",
    "test"
  ],
  [
    "matches src/expectations/matches.ts~matches,matches",
    "test-file/spec/expectations/matches.spec.ts.html#lineNumber18",
    "matches breaks the actor flow when \"actual\" does not match the \"expected\"",
    "test"
  ],
  [
    "matches src/expectations/matches.ts~matches,matches",
    "test-file/spec/expectations/matches.spec.ts.html#lineNumber29",
    "matches contributes to a human-readable description",
    "test"
  ],
  [
    "",
    "test-file/spec/expectations/not.spec.ts.html#lineNumber23",
    "not",
    "test"
  ],
  [
    "not src/expectations/not.ts~not,not",
    "test-file/spec/expectations/not.spec.ts.html#lineNumber26",
    "not allows for the actor flow to continue when the \"actual\" meets the expectation",
    "test"
  ],
  [
    "not src/expectations/not.ts~not,not",
    "test-file/spec/expectations/not.spec.ts.html#lineNumber33",
    "not breaks the actor flow when \"actual\" does not meet the expectation",
    "test"
  ],
  [
    "not src/expectations/not.ts~not,not",
    "test-file/spec/expectations/not.spec.ts.html#lineNumber44",
    "not contributes to a human-readable description",
    "test"
  ],
  [
    "",
    "test-file/spec/expectations/not.spec.ts.html#lineNumber61",
    "not double negative",
    "test"
  ],
  [
    "not src/expectations/not.ts~not,not",
    "test-file/spec/expectations/not.spec.ts.html#lineNumber63",
    "not double negative contributes to a human-readable description",
    "test"
  ],
  [
    "",
    "test-file/spec/expectations/not.spec.ts.html#lineNumber49",
    "not flips the outcome of an assertion, but doesn't hide any errors that might have happened while making it",
    "test"
  ],
  [
    "",
    "test-file/spec/expectations/not.spec.ts.html#lineNumber69",
    "not when combined with other assertions, such as",
    "test"
  ],
  [
    "",
    "test-file/spec/expectations/not.spec.ts.html#lineNumber71",
    "not when combined with other assertions, such as and,",
    "test"
  ],
  [
    "and src/expectations/and.ts~and,and",
    "test-file/spec/expectations/not.spec.ts.html#lineNumber87",
    "not when combined with other assertions, such as and, contributes to a human-readable description",
    "test"
  ],
  [
    "and src/expectations/and.ts~and,and",
    "test-file/spec/expectations/not.spec.ts.html#lineNumber75",
    "not when combined with other assertions, such as and, produces a sensible error message",
    "test"
  ],
  [
    "",
    "test-file/spec/expectations/not.spec.ts.html#lineNumber116",
    "not when combined with other assertions, such as containAtLeastOneItemThat,",
    "test"
  ],
  [
    "containatleastoneitemthat src/expectations/containatleastoneitemthat.ts~containatleastoneitemthat,containatleastoneitemthat",
    "test-file/spec/expectations/not.spec.ts.html#lineNumber133",
    "not when combined with other assertions, such as containAtLeastOneItemThat, contributes to a human-readable description",
    "test"
  ],
  [
    "containatleastoneitemthat src/expectations/containatleastoneitemthat.ts~containatleastoneitemthat,containatleastoneitemthat",
    "test-file/spec/expectations/not.spec.ts.html#lineNumber120",
    "not when combined with other assertions, such as containAtLeastOneItemThat, produces a sensible error message",
    "test"
  ],
  [
    "",
    "test-file/spec/expectations/not.spec.ts.html#lineNumber93",
    "not when combined with other assertions, such as contains,",
    "test"
  ],
  [
    "contains contains,contains",
    "test-file/spec/expectations/not.spec.ts.html#lineNumber110",
    "not when combined with other assertions, such as contains, contributes to a human-readable description",
    "test"
  ],
  [
    "contains contains,contains",
    "test-file/spec/expectations/not.spec.ts.html#lineNumber97",
    "not when combined with other assertions, such as contains, produces a sensible error message",
    "test"
  ],
  [
    "",
    "test-file/spec/expectations/not.spec.ts.html#lineNumber139",
    "not when combined with other assertions, such as endsWith,",
    "test"
  ],
  [
    "endswith src/expectations/endswith.ts~endswith,endswith",
    "test-file/spec/expectations/not.spec.ts.html#lineNumber155",
    "not when combined with other assertions, such as endsWith, contributes to a human-readable description",
    "test"
  ],
  [
    "endswith src/expectations/endswith.ts~endswith,endswith",
    "test-file/spec/expectations/not.spec.ts.html#lineNumber143",
    "not when combined with other assertions, such as endsWith, produces a sensible error message",
    "test"
  ],
  [
    "",
    "test-file/spec/expectations/not.spec.ts.html#lineNumber161",
    "not when combined with other assertions, such as equals,",
    "test"
  ],
  [
    "equals src/expectations/equals.ts~equals,equals",
    "test-file/spec/expectations/not.spec.ts.html#lineNumber177",
    "not when combined with other assertions, such as equals, contributes to a human-readable description",
    "test"
  ],
  [
    "equals src/expectations/equals.ts~equals,equals",
    "test-file/spec/expectations/not.spec.ts.html#lineNumber165",
    "not when combined with other assertions, such as equals, produces a sensible error message",
    "test"
  ],
  [
    "",
    "test-file/spec/expectations/not.spec.ts.html#lineNumber227",
    "not when combined with other assertions, such as includes,",
    "test"
  ],
  [
    "includes src/expectations/includes.ts~includes,includes",
    "test-file/spec/expectations/not.spec.ts.html#lineNumber243",
    "not when combined with other assertions, such as includes, contributes to a human-readable description",
    "test"
  ],
  [
    "includes src/expectations/includes.ts~includes,includes",
    "test-file/spec/expectations/not.spec.ts.html#lineNumber231",
    "not when combined with other assertions, such as includes, produces a sensible error message",
    "test"
  ],
  [
    "",
    "test-file/spec/expectations/not.spec.ts.html#lineNumber205",
    "not when combined with other assertions, such as isFalse,",
    "test"
  ],
  [
    "isfalse src/expectations/isfalse.ts~isfalse,isfalse",
    "test-file/spec/expectations/not.spec.ts.html#lineNumber221",
    "not when combined with other assertions, such as isFalse, contributes to a human-readable description",
    "test"
  ],
  [
    "isfalse src/expectations/isfalse.ts~isfalse,isfalse",
    "test-file/spec/expectations/not.spec.ts.html#lineNumber209",
    "not when combined with other assertions, such as isFalse, produces a sensible error message",
    "test"
  ],
  [
    "",
    "test-file/spec/expectations/not.spec.ts.html#lineNumber249",
    "not when combined with other assertions, such as isGreaterThan,",
    "test"
  ],
  [
    "isgreaterthan src/expectations/isgreaterthan.ts~isgreaterthan,isgreaterthan",
    "test-file/spec/expectations/not.spec.ts.html#lineNumber265",
    "not when combined with other assertions, such as isGreaterThan, contributes to a human-readable description",
    "test"
  ],
  [
    "isgreaterthan src/expectations/isgreaterthan.ts~isgreaterthan,isgreaterthan",
    "test-file/spec/expectations/not.spec.ts.html#lineNumber253",
    "not when combined with other assertions, such as isGreaterThan, produces a sensible error message",
    "test"
  ],
  [
    "",
    "test-file/spec/expectations/not.spec.ts.html#lineNumber271",
    "not when combined with other assertions, such as isLessThan,",
    "test"
  ],
  [
    "islessthan src/expectations/islessthan.ts~islessthan,islessthan",
    "test-file/spec/expectations/not.spec.ts.html#lineNumber287",
    "not when combined with other assertions, such as isLessThan, contributes to a human-readable description",
    "test"
  ],
  [
    "islessthan src/expectations/islessthan.ts~islessthan,islessthan",
    "test-file/spec/expectations/not.spec.ts.html#lineNumber275",
    "not when combined with other assertions, such as isLessThan, produces a sensible error message",
    "test"
  ],
  [
    "",
    "test-file/spec/expectations/not.spec.ts.html#lineNumber183",
    "not when combined with other assertions, such as isTrue,",
    "test"
  ],
  [
    "istrue src/expectations/istrue.ts~istrue,istrue",
    "test-file/spec/expectations/not.spec.ts.html#lineNumber199",
    "not when combined with other assertions, such as isTrue, contributes to a human-readable description",
    "test"
  ],
  [
    "istrue src/expectations/istrue.ts~istrue,istrue",
    "test-file/spec/expectations/not.spec.ts.html#lineNumber187",
    "not when combined with other assertions, such as isTrue, produces a sensible error message",
    "test"
  ],
  [
    "",
    "test-file/spec/expectations/not.spec.ts.html#lineNumber293",
    "not when combined with other assertions, such as or,",
    "test"
  ],
  [
    "or src/expectations/or.ts~or,or",
    "test-file/spec/expectations/not.spec.ts.html#lineNumber309",
    "not when combined with other assertions, such as or, contributes to a human-readable description",
    "test"
  ],
  [
    "or src/expectations/or.ts~or,or",
    "test-file/spec/expectations/not.spec.ts.html#lineNumber297",
    "not when combined with other assertions, such as or, produces a sensible error message",
    "test"
  ],
  [
    "",
    "test-file/spec/expectations/not.spec.ts.html#lineNumber315",
    "not when combined with other assertions, such as startsWith,",
    "test"
  ],
  [
    "startswith src/expectations/startswith.ts~startswith,startswith",
    "test-file/spec/expectations/not.spec.ts.html#lineNumber331",
    "not when combined with other assertions, such as startsWith, contributes to a human-readable description",
    "test"
  ],
  [
    "startswith src/expectations/startswith.ts~startswith,startswith",
    "test-file/spec/expectations/not.spec.ts.html#lineNumber319",
    "not when combined with other assertions, such as startsWith, produces a sensible error message",
    "test"
  ],
  [
    "",
    "test-file/spec/expectations/or.spec.ts.html#lineNumber8",
    "or",
    "test"
  ],
  [
    "",
    "test-file/spec/expectations/or.spec.ts.html#lineNumber10",
    "or allows for the actor flow to continue when the \"actual\"",
    "test"
  ],
  [
    "or src/expectations/or.ts~or,or",
    "test-file/spec/expectations/or.spec.ts.html#lineNumber13",
    "or allows for the actor flow to continue when the \"actual\" meets all the expectations",
    "test"
  ],
  [
    "or src/expectations/or.ts~or,or",
    "test-file/spec/expectations/or.spec.ts.html#lineNumber20",
    "or allows for the actor flow to continue when the \"actual\" meets at least one expectation",
    "test"
  ],
  [
    "or src/expectations/or.ts~or,or",
    "test-file/spec/expectations/or.spec.ts.html#lineNumber28",
    "or breaks the actor flow when \"actual\" does meets none of the expectations",
    "test"
  ],
  [
    "or src/expectations/or.ts~or,or",
    "test-file/spec/expectations/or.spec.ts.html#lineNumber39",
    "or contributes to a human-readable description",
    "test"
  ],
  [
    "protractor~protractorconfig",
    "https://github.com/angular/protractor/blob/master/lib/config.ts",
    "protractor~ProtractorConfig",
    "external"
  ],
  [
    "protractor~runner",
    "https://github.com/angular/protractor/blob/master/lib/runner.ts",
    "protractor~Runner",
    "external"
  ],
  [
    "selenium-webdriver~actions",
    "https://www.selenium.dev/selenium/docs/api/javascript/module/selenium-webdriver/lib/input_exports_Actions.html",
    "selenium-webdriver~Actions",
    "external"
  ],
  [
    "selenium-webdriver~alertpromise",
    "https://www.selenium.dev/selenium/docs/api/javascript/module/selenium-webdriver/lib/webdriver_exports_AlertPromise.html",
    "selenium-webdriver~AlertPromise",
    "external"
  ],
  [
    "selenium-webdriver~by",
    "https://www.selenium.dev/selenium/docs/api/javascript/module/selenium-webdriver/lib/by_exports_By.html",
    "selenium-webdriver~By",
    "external"
  ],
  [
    "selenium-webdriver~capabilities",
    "https://www.selenium.dev/selenium/docs/api/javascript/module/selenium-webdriver/index_exports_Capabilities.html",
    "selenium-webdriver~Capabilities",
    "external"
  ],
  [
    "selenium-webdriver~key",
    "https://www.selenium.dev/selenium/docs/api/javascript/module/selenium-webdriver/index_exports_Key.html",
    "selenium-webdriver~Key",
    "external"
  ],
  [
    "selenium-webdriver~navigation",
    "https://www.selenium.dev/selenium/docs/api/javascript/module/selenium-webdriver/lib/webdriver_exports_Navigation.html",
    "selenium-webdriver~Navigation",
    "external"
  ],
  [
    "selenium-webdriver~options",
    "https://www.selenium.dev/selenium/docs/api/javascript/module/selenium-webdriver/ie_exports_Options.html",
    "selenium-webdriver~Options",
    "external"
  ],
  [
    "selenium-webdriver~webelement",
    "https://www.selenium.dev/selenium/docs/api/javascript/module/selenium-webdriver/index_exports_WebElement.html",
    "selenium-webdriver~WebElement",
    "external"
  ],
  [
    "spec/ensure.spec.ts",
    "test-file/spec/Ensure.spec.ts.html",
    "spec/Ensure.spec.ts",
    "testFile"
  ],
  [
    "spec/expectation.spec.ts",
    "test-file/spec/Expectation.spec.ts.html",
    "spec/Expectation.spec.ts",
    "testFile"
  ],
  [
    "spec/expectations/and.spec.ts",
    "test-file/spec/expectations/and.spec.ts.html",
    "spec/expectations/and.spec.ts",
    "testFile"
  ],
  [
    "spec/expectations/contain.spec.ts",
    "test-file/spec/expectations/contain.spec.ts.html",
    "spec/expectations/contain.spec.ts",
    "testFile"
  ],
  [
    "spec/expectations/containatleastoneitemthat.spec.ts",
    "test-file/spec/expectations/containAtLeastOneItemThat.spec.ts.html",
    "spec/expectations/containAtLeastOneItemThat.spec.ts",
    "testFile"
  ],
  [
    "spec/expectations/containitemswhereeachitem.spec.ts",
    "test-file/spec/expectations/containItemsWhereEachItem.spec.ts.html",
    "spec/expectations/containItemsWhereEachItem.spec.ts",
    "testFile"
  ],
  [
    "spec/expectations/endswith.spec.ts",
    "test-file/spec/expectations/endsWith.spec.ts.html",
    "spec/expectations/endsWith.spec.ts",
    "testFile"
  ],
  [
    "spec/expectations/equals.spec.ts",
    "test-file/spec/expectations/equals.spec.ts.html",
    "spec/expectations/equals.spec.ts",
    "testFile"
  ],
  [
    "spec/expectations/includes.spec.ts",
    "test-file/spec/expectations/includes.spec.ts.html",
    "spec/expectations/includes.spec.ts",
    "testFile"
  ],
  [
    "spec/expectations/isafter.spec.ts",
    "test-file/spec/expectations/isAfter.spec.ts.html",
    "spec/expectations/isAfter.spec.ts",
    "testFile"
  ],
  [
    "spec/expectations/isbefore.spec.ts",
    "test-file/spec/expectations/isBefore.spec.ts.html",
    "spec/expectations/isBefore.spec.ts",
    "testFile"
  ],
  [
    "spec/expectations/isfalse.spec.ts",
    "test-file/spec/expectations/isFalse.spec.ts.html",
    "spec/expectations/isFalse.spec.ts",
    "testFile"
  ],
  [
    "spec/expectations/isgreaterthan.spec.ts",
    "test-file/spec/expectations/isGreaterThan.spec.ts.html",
    "spec/expectations/isGreaterThan.spec.ts",
    "testFile"
  ],
  [
    "spec/expectations/islessthan.spec.ts",
    "test-file/spec/expectations/isLessThan.spec.ts.html",
    "spec/expectations/isLessThan.spec.ts",
    "testFile"
  ],
  [
    "spec/expectations/istrue.spec.ts",
    "test-file/spec/expectations/isTrue.spec.ts.html",
    "spec/expectations/isTrue.spec.ts",
    "testFile"
  ],
  [
    "spec/expectations/matches.spec.ts",
    "test-file/spec/expectations/matches.spec.ts.html",
    "spec/expectations/matches.spec.ts",
    "testFile"
  ],
  [
    "spec/expectations/not.spec.ts",
    "test-file/spec/expectations/not.spec.ts.html",
    "spec/expectations/not.spec.ts",
    "testFile"
  ],
  [
    "spec/expectations/or.spec.ts",
    "test-file/spec/expectations/or.spec.ts.html",
    "spec/expectations/or.spec.ts",
    "testFile"
  ],
  [
    "spec/expectations/property.spec.ts",
    "test-file/spec/expectations/property.spec.ts.html",
    "spec/expectations/property.spec.ts",
    "testFile"
  ],
  [
    "spec/expectations/startswith.spec.ts",
    "test-file/spec/expectations/startsWith.spec.ts.html",
    "spec/expectations/startsWith.spec.ts",
    "testFile"
  ],
  [
    "spec/setup.spec.ts",
    "test-file/spec/setup.spec.ts.html",
    "spec/setup.spec.ts",
    "testFile"
  ],
  [
    "src/ensure.ts",
    "file/src/Ensure.ts.html",
    "src/Ensure.ts",
    "file"
  ],
  [
    "src/ensure.ts~ensure#asassertionerror",
    "class/src/Ensure.ts~Ensure.html#instance-method-asAssertionError",
    "src/Ensure.ts~Ensure#asAssertionError",
    "method"
  ],
  [
    "src/ensure.ts~ensure#constructor",
    "class/src/Ensure.ts~Ensure.html#instance-constructor-constructor",
    "src/Ensure.ts~Ensure#constructor",
    "method"
  ],
  [
    "src/ensure.ts~ensure#errorforoutcome",
    "class/src/Ensure.ts~Ensure.html#instance-method-errorForOutcome",
    "src/Ensure.ts~Ensure#errorForOutcome",
    "method"
  ],
  [
    "src/ensure.ts~ensure#otherwisefailwith",
    "class/src/Ensure.ts~Ensure.html#instance-method-otherwiseFailWith",
    "src/Ensure.ts~Ensure#otherwiseFailWith",
    "method"
  ],
  [
    "src/ensure.ts~ensure#performas",
    "class/src/Ensure.ts~Ensure.html#instance-method-performAs",
    "src/Ensure.ts~Ensure#performAs",
    "method"
  ],
  [
    "src/ensure.ts~ensure#tostring",
    "class/src/Ensure.ts~Ensure.html#instance-method-toString",
    "src/Ensure.ts~Ensure#toString",
    "method"
  ],
  [
    "src/ensure.ts~ensure.that",
    "class/src/Ensure.ts~Ensure.html#static-method-that",
    "src/Ensure.ts~Ensure.that",
    "method"
  ],
  [
    "src/expectations/and.ts",
    "file/src/expectations/and.ts.html",
    "src/expectations/and.ts",
    "file"
  ],
  [
    "src/expectations/contain.ts",
    "file/src/expectations/contain.ts.html",
    "src/expectations/contain.ts",
    "file"
  ],
  [
    "src/expectations/containatleastoneitemthat.ts",
    "file/src/expectations/containAtLeastOneItemThat.ts.html",
    "src/expectations/containAtLeastOneItemThat.ts",
    "file"
  ],
  [
    "src/expectations/containitemswhereeachitem.ts",
    "file/src/expectations/containItemsWhereEachItem.ts.html",
    "src/expectations/containItemsWhereEachItem.ts",
    "file"
  ],
  [
    "src/expectations/endswith.ts",
    "file/src/expectations/endsWith.ts.html",
    "src/expectations/endsWith.ts",
    "file"
  ],
  [
    "src/expectations/equals.ts",
    "file/src/expectations/equals.ts.html",
    "src/expectations/equals.ts",
    "file"
  ],
  [
    "src/expectations/includes.ts",
    "file/src/expectations/includes.ts.html",
    "src/expectations/includes.ts",
    "file"
  ],
  [
    "src/expectations/index.ts",
    "file/src/expectations/index.ts.html",
    "src/expectations/index.ts",
    "file"
  ],
  [
    "src/expectations/isafter.ts",
    "file/src/expectations/isAfter.ts.html",
    "src/expectations/isAfter.ts",
    "file"
  ],
  [
    "src/expectations/isbefore.ts",
    "file/src/expectations/isBefore.ts.html",
    "src/expectations/isBefore.ts",
    "file"
  ],
  [
    "src/expectations/isfalse.ts",
    "file/src/expectations/isFalse.ts.html",
    "src/expectations/isFalse.ts",
    "file"
  ],
  [
    "src/expectations/isgreaterthan.ts",
    "file/src/expectations/isGreaterThan.ts.html",
    "src/expectations/isGreaterThan.ts",
    "file"
  ],
  [
    "src/expectations/islessthan.ts",
    "file/src/expectations/isLessThan.ts.html",
    "src/expectations/isLessThan.ts",
    "file"
  ],
  [
    "src/expectations/istrue.ts",
    "file/src/expectations/isTrue.ts.html",
    "src/expectations/isTrue.ts",
    "file"
  ],
  [
    "src/expectations/matches.ts",
    "file/src/expectations/matches.ts.html",
    "src/expectations/matches.ts",
    "file"
  ],
  [
    "src/expectations/not.ts",
    "file/src/expectations/not.ts.html",
    "src/expectations/not.ts",
    "file"
  ],
  [
    "src/expectations/or.ts",
    "file/src/expectations/or.ts.html",
    "src/expectations/or.ts",
    "file"
  ],
  [
    "src/expectations/property.ts",
    "file/src/expectations/property.ts.html",
    "src/expectations/property.ts",
    "file"
  ],
  [
    "src/expectations/startswith.ts",
    "file/src/expectations/startsWith.ts.html",
    "src/expectations/startsWith.ts",
    "file"
  ],
  [
    "src/index.ts",
    "file/src/index.ts.html",
    "src/index.ts",
    "file"
  ],
  [
    "",
    "test-file/spec/expectations/startsWith.spec.ts.html#lineNumber8",
    "startsWith",
    "test"
  ],
  [
    "startswith src/expectations/startswith.ts~startswith,startswith",
    "test-file/spec/expectations/startsWith.spec.ts.html#lineNumber11",
    "startsWith allows for the actor flow to continue when the \"actual\" starts with \"expected\"",
    "test"
  ],
  [
    "startswith src/expectations/startswith.ts~startswith,startswith",
    "test-file/spec/expectations/startsWith.spec.ts.html#lineNumber18",
    "startsWith breaks the actor flow when \"actual\" does not start with \"expected\"",
    "test"
  ],
  [
    "startswith src/expectations/startswith.ts~startswith,startswith",
    "test-file/spec/expectations/startsWith.spec.ts.html#lineNumber29",
    "startsWith contributes to a human-readable description",
    "test"
  ],
  [
    "tiny-types~jsonobject",
    "https://jan-molak.github.io/tiny-types/file/src/types/json.ts.html",
    "tiny-types~JSONObject",
    "external"
  ],
  [
    "tiny-types~tinytype",
    "https://jan-molak.github.io/tiny-types/class/src/TinyType.ts~TinyType.html",
    "tiny-types~TinyType",
    "external"
  ]
]