/** @external {@serenity-js/rest/lib/model~DeleteRequest} /modules/rest/class/src/model/DeleteRequest.ts~DeleteRequest.html */
/** @external {@serenity-js/rest/lib/model~GetRequest} /modules/rest/class/src/model/GetRequest.ts~GetRequest.html */
/** @external {@serenity-js/rest/lib/model~HTTPRequest} /modules/rest/class/src/model/HTTPRequest.ts~HTTPRequest.html */
/** @external {@serenity-js/rest/lib/model~HeadRequest} /modules/rest/class/src/model/HeadRequest.ts~HeadRequest.html */
/** @external {@serenity-js/rest/lib/model~OptionsRequest} /modules/rest/class/src/model/OptionsRequest.ts~OptionsRequest.html */
/** @external {@serenity-js/rest/lib/model~PatchRequest} /modules/rest/class/src/model/PatchRequest.ts~PatchRequest.html */
/** @external {@serenity-js/rest/lib/model~PostRequest} /modules/rest/class/src/model/PostRequest.ts~PostRequest.html */
/** @external {@serenity-js/rest/lib/model~PutRequest} /modules/rest/class/src/model/PutRequest.ts~PutRequest.html */
/** @external {@serenity-js/rest/lib/screenplay/abilities~CallAnApi} /modules/rest/class/src/screenplay/abilities/CallAnApi.ts~CallAnApi.html */
/** @external {@serenity-js/rest/lib/screenplay/interactions~ChangeApiUrl} /modules/rest/class/src/screenplay/interactions/ChangeApiUrl.ts~ChangeApiUrl.html */
/** @external {@serenity-js/rest/lib/screenplay/interactions~Send} /modules/rest/class/src/screenplay/interactions/Send.ts~Send.html */
/** @external {@serenity-js/rest/lib/screenplay/questions~LastResponse} /modules/rest/class/src/screenplay/questions/LastResponse.ts~LastResponse.html */