extends: '../../.nycrc.yml'
cwd: '../../packages'
reportDir: '../target/coverage/integration-playwright-web'
tempDir: '../.nyc_output'
include:
  - 'core/src/**/*.ts'
  - 'core/lib/**/*.js'
  - 'mocha/src/**/*.ts'
  - 'mocha/lib/**/*.js'
  - 'web/src/**/*.ts'
  - 'web/lib/**/*.js'
  - 'playwright/src/**/*.ts'
  - 'playwright/lib/**/*.js'
exclude:
  - '**/target/**'
  - '**/spec/**'
  - '**/*.d.ts'
  - '**/*.spec.ts'
