extends: '../../.nycrc.yml'
cwd: '../../packages'
reportDir: '../target/coverage/integration-jasmine'
tempDir: '../.nyc_output'
include:
  - 'core/src/**/*.ts'
  - 'core/lib/**/*.js'
  - 'jasmine/src/**/*.ts'
  - 'jasmine/lib/**/*.js'
exclude:
  - '**/target/**'
  - '**/spec/**'
  - '**/*.d.ts'
  - '**/*.spec.ts'
