import htm from 'htm';
import { h } from 'preact';

const html = htm.bind(h);

export function AboutView(): ReturnType<typeof html> {
    return html`
    <div class="about-view">
      <div class="card">
        <p style="margin:0 0 var(--space-lg)">
          This report is generated by <a href="https://serenity-js.org" target="_blank" class="link-accent">Serenity/JS</a>.
          It gives you a clear picture of what your test suite covers, where it's failing, and whether the system is ready to release.
        </p>

        <section>
          <h3 class="about-section-title">Confidence scoring</h3>
          <p>The confidence score is this report's primary quality indicator — a single number (0–100%) that answers:</p>
          <blockquote style="border-left:3px solid var(--accent);padding:var(--space-sm) var(--space-md);margin:var(--space-md) 0;color:var(--text-secondary);font-style:italic">
            "How confident am I that this capability works correctly?"
          </blockquote>
          <p>Confidence is a weighted composite of three signals:</p>
          <table class="content-table">
            <thead>
              <tr style="border-bottom:2px solid var(--divider)">
                <th class="panel-section font-semibold text-left">Signal</th>
                <th class="panel-section font-semibold text-left">Weight</th>
                <th class="panel-section font-semibold text-left">Measures</th>
              </tr>
            </thead>
            <tbody>
              <tr class="border-b">
                <td class="panel-section font-medium">Pass Rate</td>
                <td class="panel-section">40%</td>
                <td class="panel-section text-secondary">Percentage of scenarios passing among those executed (excludes skipped/pending)</td>
              </tr>
              <tr class="border-b">
                <td class="panel-section font-medium">Consistency</td>
                <td class="panel-section">35%</td>
                <td class="panel-section text-secondary">How stable the results are across recent runs — a test that alternates between passing and failing scores low</td>
              </tr>
              <tr class="border-b">
                <td class="panel-section font-medium">Completeness</td>
                <td class="panel-section">25%</td>
                <td class="panel-section text-secondary">Percentage of scenarios that are implemented (not pending or skipped)</td>
              </tr>
            </tbody>
          </table>
          <p>
            The formula is deterministic with no hidden penalties:
            <code style="background:var(--bg-primary);padding:2px 6px;border-radius:var(--radius-sm);font-family:var(--font-mono);font-size:var(--font-xs)">
              Confidence = Pass Rate × 0.40 + Consistency × 0.35 + Completeness × 0.25
            </code>
          </p>
          <p>If all three metrics are 100%, confidence is 100%. In plain terms: passing tests matter most (40%), reliability across runs matters almost as much (35%), and having all tests implemented rather than pending or skipped accounts for the rest (25%).</p>
        </section>

        <section>
          <h3 class="about-section-title">Report sections</h3>

          <div class="stack-md">
            <div class="panel-bg">
              <h4 class="section-title-sm">Dashboard</h4>
              <p class="section-text">Overview of the latest test run — confidence, pass rate, consistency, completeness, duration, and trend across recent executions.</p>
            </div>
            <div class="panel-bg">
              <h4 class="section-title-sm">Test Scenarios</h4>
              <p class="section-text">Browse, search, and filter all test scenarios. View execution details, activity trees, screenshots, and retry history for each test.</p>
            </div>
            <div class="panel-bg">
              <h4 class="section-title-sm">Capabilities</h4>
              <p class="section-text">Hierarchical view of business capabilities, organised to match how your test files are structured. Each capability shows confidence, outcomes, and documentation from README files.</p>
            </div>
            <div class="panel-bg">
              <h4 class="section-title-sm">Errors</h4>
              <p class="section-text">Failed scenarios grouped by error type — assertion errors, timeouts, runtime errors, and compromised tests. Helps identify patterns in failures.</p>
            </div>
            <div class="panel-bg">
              <h4 class="section-title-sm">Consistency</h4>
              <p class="section-text">Tests with reliability issues across recent runs. Classifies tests based on their execution pattern:</p>
              <ul style="padding-left:var(--space-lg);margin:var(--space-sm) 0;font-size:var(--font-sm);color:var(--text-secondary);line-height:1.8">
                <li><strong>Flaky</strong> — fails on the first attempt but passes after a retry within the same run. The build goes green, but the test needed multiple tries to get there.</li>
                <li><strong>Inconsistent</strong> — has genuine failures in its recent history but currently survives only via retry. The build passes, but the test has broken before and may again.</li>
                <li><strong>Degraded</strong> — was passing in the previous run, now failing.</li>
                <li><strong>Recovered</strong> — was failing in the previous run, now passes cleanly without needing retry.</li>
              </ul>
            </div>
            <div class="panel-bg">
              <h4 class="section-title-sm">Timeline</h4>
              <p class="section-text">Execution timeline showing when each scenario ran and how long it took. Useful for identifying slow tests and optimising execution time.</p>
            </div>
            <div class="panel-bg">
              <h4 class="section-title-sm">Test Runs</h4>
              <p class="section-text">History of all test executions with trend analysis. Compare results across runs to identify regressions or improvements over time.</p>
            </div>
            <div class="panel-bg">
              <h4 class="section-title-sm">Machine-Readable Summary</h4>
              <p class="section-text">A machine-readable <a href="summary.json" target="_blank" class="link-accent">summary.json</a> file is generated alongside the report. It contains the same quality data (outcomes, failure patterns, consistency scores) in a format that CI pipelines, dashboards, and AI tools can consume automatically.</p>
            </div>
          </div>
        </section>

        <section>
          <h3 class="about-section-title">Improving confidence</h3>
          <p>To increase the confidence score for a capability:</p>
          <ul style="padding-left:var(--space-lg);margin:var(--space-sm) 0;font-size:var(--font-sm);color:var(--text-secondary);line-height:1.8">
            <li><strong>Fix failing tests</strong> — each failure directly reduces the pass rate component</li>
            <li><strong>Implement pending scenarios</strong> — unimplemented tests reduce completeness</li>
            <li><strong>Stabilise inconsistent tests</strong> — inconsistent outcomes reduce the consistency component</li>
            <li><strong>Run tests regularly</strong> — more execution history gives consistency a stronger signal</li>
          </ul>
        </section>

        <section>
          <h3 class="about-section-title">Glossary</h3>

          <h4 class="glossary-group-title">Screenplay Pattern</h4>
          <dl class="glossary">
            <div class="glossary-entry">
              <dt>Actor</dt>
              <dd>A person or external system interacting with the system under test. Actors perform Tasks and Interactions using their Abilities (e.g. <em>BrowseTheWeb</em>, <em>CallAnApi</em>).</dd>
            </div>
            <div class="glossary-entry">
              <dt>Ability</dt>
              <dd>A thin wrapper around an interface to the system under test (e.g. a browser, an HTTP client, a database connection). Actors are given Abilities so they can perform Interactions.</dd>
            </div>
            <div class="glossary-entry">
              <dt>Task</dt>
              <dd>A business-meaningful workflow composed of other Tasks and Interactions. Shown as bold entries in the activity tree (e.g. "Alice places an order").</dd>
            </div>
            <div class="glossary-entry">
              <dt>Interaction</dt>
              <dd>A single, atomic action at the system interface level (e.g. "Alice clicks on submit button", "Alice sends a POST request"). The leaf nodes in the activity tree.</dd>
            </div>
            <div class="glossary-entry">
              <dt>Question</dt>
              <dd>A way to read information from the system under test — for example, "the text of the heading" or "the status of the last response." Questions don't change anything; they only observe. They're used in assertions to verify expected behaviour.</dd>
            </div>
          </dl>

          <h4 class="glossary-group-title">Test scenario outcomes</h4>
          <dl class="glossary">
            <div class="glossary-entry">
              <dt>Passed</dt>
              <dd>A test scenario that completed successfully — all assertions were satisfied.</dd>
            </div>
            <div class="glossary-entry">
              <dt>Failed</dt>
              <dd>A test scenario where an assertion was not satisfied (e.g. expected value did not match actual).</dd>
            </div>
            <div class="glossary-entry">
              <dt>Error</dt>
              <dd>A test scenario that failed due to an unexpected error (e.g. an unhandled exception) rather than an assertion failure.</dd>
            </div>
            <div class="glossary-entry">
              <dt>Compromised</dt>
              <dd>A test that could not complete because something in the test environment failed (e.g. database unavailable, network timeout) — not because of a bug in the product being tested.</dd>
            </div>
            <div class="glossary-entry">
              <dt>Pending</dt>
              <dd>A test scenario that has been specified but not yet implemented — a placeholder for future work.</dd>
            </div>
            <div class="glossary-entry">
              <dt>Skipped</dt>
              <dd>A test scenario that was intentionally excluded from execution (e.g. via a tag filter or conditional skip).</dd>
            </div>
          </dl>

          <h4 class="glossary-group-title">Quality metrics</h4>
          <dl class="glossary">
            <div class="glossary-entry">
              <dt>Confidence</dt>
              <dd>A composite score (0–100%) indicating how likely a capability is to be working correctly. Combines pass rate, completeness, and consistency.</dd>
            </div>
            <div class="glossary-entry">
              <dt>Pass Rate</dt>
              <dd>The percentage of executed scenarios that are currently passing. Excludes pending and skipped scenarios from the calculation.</dd>
            </div>
            <div class="glossary-entry">
              <dt>Completeness</dt>
              <dd>The percentage of scenarios that are implemented and actively executed (not pending or skipped).</dd>
            </div>
            <div class="glossary-entry">
              <dt>Consistency</dt>
              <dd>How repeatable a test's outcome is across recent runs. A test that alternates between passing and failing has low consistency (colloquially known as "flaky").</dd>
            </div>
            <div class="glossary-entry">
              <dt>Consistency Window</dt>
              <dd>The number of most recent test runs considered when evaluating consistency (default: 5). Only runs within this window affect the consistency score.</dd>
            </div>
          </dl>

          <h4 class="glossary-group-title">Test history</h4>
          <dl class="glossary">
            <div class="glossary-entry">
              <dt>Flaky</dt>
              <dd>A test that fails on an earlier attempt but passes on a subsequent retry within a single test run. The build succeeds, but the test needed multiple tries to get there.</dd>
            </div>
            <div class="glossary-entry">
              <dt>Inconsistent</dt>
              <dd>A test that has genuine failures in its recent history but whose most recent outcome is a pass-on-retry. The build stays green only because retries are masking the underlying problem.</dd>
            </div>
            <div class="glossary-entry">
              <dt>Degraded</dt>
              <dd>A test that was passing in the previous run but is now failing — a new regression that needs attention.</dd>
            </div>
            <div class="glossary-entry">
              <dt>Recovered</dt>
              <dd>A test that was failing in the previous run but now passes cleanly on the first attempt. A test that now passes only via retry is "flaky", not "recovered".</dd>
            </div>
          </dl>

          <h4 class="glossary-group-title">Living documentation</h4>
          <dl class="glossary">
            <div class="glossary-entry">
              <dt>Capability</dt>
              <dd>A grouping of test scenarios derived from your spec directory structure. Each directory becomes a capability node; README files provide documentation for each capability.</dd>
            </div>
            <div class="glossary-entry">
              <dt>Activity Tree</dt>
              <dd>The hierarchical breakdown of a scenario's execution — showing the Tasks and Interactions performed, their outcomes, durations, and any associated artifacts (screenshots, HTTP exchanges).</dd>
            </div>
          </dl>
        </section>

        <section>
          <h3 class="about-section-title">Learn more</h3>
          <p>
            Visit <a href="https://serenity-js.org/handbook/reporting/" target="_blank" class="link-accent">serenity-js.org/handbook/reporting</a> for
            comprehensive documentation on configuring reporters, customising reports, and integrating Serenity/JS into your CI/CD pipeline.
          </p>
        </section>
      </div>
    </div>
  `;
}
