runs:
  using: 'composite'
  steps:
  - name:  Test OS
    shell: bash
    run: |
      if [[ $RUNNER_OS == 'Windows' ]]; then
          echo "We're on Windows"
      else
          echo "We're not on Windows"
      fi

      env
