runs:
  using: 'composite'
  steps:
  - name:  Test OS (Windows)
    shell: bash
    if:    ${{ runner.os == 'Windows' }}
    run: |
      env
  - name:  Test OS (Linux)
    shell: bash
    if:    ${{ runner.os != 'Windows' }}
    run: |
      env
