name: 'Upload Compressed Artifact'
description: 'Compresses and uploads an artifact'

inputs:
  artifact-name:
    description: 'The name of the artifact to upload after invoking the command'
    type: string
    required: true
  artifact-path:
    description: 'The paths to include in the uploaded artifact'
    type: string
    required: true

runs:
  using: 'composite'
  steps:
    - name: Compress artifact
      shell: bash
      run: 7z a ${{ inputs.artifact-name }}.zip ${{ inputs.artifact-path }}

    - name: Upload artifact
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
      with:
        retention-days: 3
        name: ${{ inputs.artifact-name }}
        path: |
          ${{ inputs.artifact-name }}.zip
