name: 'Upload Compressed Artifact'
description: 'Compresses and uploads an artifact'

inputs:
  artifact-name:
    description: 'The name of the artifact to upload after invoking the command'
    type: string
    required: true
  artifact-path:
    description: 'The paths to include in the uploaded artifact'
    type: string
    required: true

runs:
  using: 'composite'
  steps:
    - name: Compress artifact
      shell: bash
      run: 7z a ${{ inputs.artifact-name }}.zip ${{ inputs.artifact-path }}

    - name: Upload artifact
      uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5
      with:
        retention-days: 3
        name: ${{ inputs.artifact-name }}
        path: |
          ${{ inputs.artifact-name }}.zip
