/* eslint-disable @typescript-eslint/explicit-module-boundary-types */
import htm from 'htm';
import { h } from 'preact';

const html = htm.bind(h);

export function AboutView() {
    return html`
    <div class="about-view">
      <div class="card">
        <h2 style="margin:0 0 var(--space-sm);font-size:var(--font-2xl);font-weight:700">About this report</h2>
        <p style="color:var(--text-secondary);margin:0 0 var(--space-lg)">
          This report is generated by <a href="https://serenity-js.org" target="_blank" rel="noopener" style="color:var(--accent);text-decoration:none;font-weight:500">Serenity/JS</a> and provides living documentation of your test suite,
          combining executable specifications with quality analytics to help you make informed release decisions.
        </p>

        <section style="margin-bottom:var(--space-xl)">
          <h3 style="font-size:var(--font-lg);font-weight:600;margin:0 0 var(--space-md)">Confidence scoring</h3>
          <p>Confidence is the primary quality metric in this report. It answers the question:</p>
          <blockquote style="border-left:3px solid var(--accent);padding:var(--space-sm) var(--space-md);margin:var(--space-md) 0;color:var(--text-secondary);font-style:italic">
            "How much should I trust this capability?"
          </blockquote>
          <p>Confidence is a weighted composite of three signals:</p>
          <table style="width:100%;border-collapse:collapse;margin:var(--space-md) 0;font-size:var(--font-sm)">
            <thead>
              <tr style="border-bottom:2px solid var(--divider)">
                <th style="text-align:left;padding:var(--space-sm) var(--space-md);font-weight:600">Signal</th>
                <th style="text-align:left;padding:var(--space-sm) var(--space-md);font-weight:600">Weight</th>
                <th style="text-align:left;padding:var(--space-sm) var(--space-md);font-weight:600">Measures</th>
              </tr>
            </thead>
            <tbody>
              <tr style="border-bottom:1px solid var(--divider)">
                <td style="padding:var(--space-sm) var(--space-md);font-weight:500">Pass Rate</td>
                <td style="padding:var(--space-sm) var(--space-md)">40%</td>
                <td style="padding:var(--space-sm) var(--space-md);color:var(--text-secondary)">Percentage of scenarios passing among those executed (excludes skipped/pending)</td>
              </tr>
              <tr style="border-bottom:1px solid var(--divider)">
                <td style="padding:var(--space-sm) var(--space-md);font-weight:500">Consistency</td>
                <td style="padding:var(--space-sm) var(--space-md)">35%</td>
                <td style="padding:var(--space-sm) var(--space-md);color:var(--text-secondary)">Repeatability across recent executions — how often outcomes change between runs</td>
              </tr>
              <tr style="border-bottom:1px solid var(--divider)">
                <td style="padding:var(--space-sm) var(--space-md);font-weight:500">Completeness</td>
                <td style="padding:var(--space-sm) var(--space-md)">25%</td>
                <td style="padding:var(--space-sm) var(--space-md);color:var(--text-secondary)">Percentage of scenarios that are implemented (not pending or skipped)</td>
              </tr>
            </tbody>
          </table>
          <p style="font-size:var(--font-sm);color:var(--text-secondary)">
            The formula is deterministic with no hidden penalties:
            <code style="background:var(--bg-primary);padding:2px 6px;border-radius:var(--radius-sm);font-family:var(--font-mono);font-size:var(--font-xs)">
              Confidence = Pass Rate × 0.40 + Completeness × 0.25 + Consistency × 0.35
            </code>
          </p>
          <p style="font-size:var(--font-sm);color:var(--text-secondary)">If all three metrics are 100%, confidence is 100%.</p>
        </section>

        <section style="margin-bottom:var(--space-xl)">
          <h3 style="font-size:var(--font-lg);font-weight:600;margin:0 0 var(--space-md)">Report sections</h3>

          <div style="display:grid;gap:var(--space-md)">
            <div style="padding:var(--space-md);background:var(--bg-primary);border-radius:var(--radius-sm)">
              <h4 style="margin:0 0 var(--space-xs);font-weight:600">Dashboard</h4>
              <p style="margin:0;font-size:var(--font-sm);color:var(--text-secondary)">Overview of the latest test run — confidence, pass rate, consistency, completeness, duration, and trend across recent executions.</p>
            </div>
            <div style="padding:var(--space-md);background:var(--bg-primary);border-radius:var(--radius-sm)">
              <h4 style="margin:0 0 var(--space-xs);font-weight:600">Test Scenarios</h4>
              <p style="margin:0;font-size:var(--font-sm);color:var(--text-secondary)">Browse, search, and filter all test scenarios. View execution details, activity trees, screenshots, and retry history for each test.</p>
            </div>
            <div style="padding:var(--space-md);background:var(--bg-primary);border-radius:var(--radius-sm)">
              <h4 style="margin:0 0 var(--space-xs);font-weight:600">Capabilities</h4>
              <p style="margin:0;font-size:var(--font-sm);color:var(--text-secondary)">Hierarchical view of business capabilities derived from your test directory structure. Each capability shows confidence, outcomes, and documentation from README files.</p>
            </div>
            <div style="padding:var(--space-md);background:var(--bg-primary);border-radius:var(--radius-sm)">
              <h4 style="margin:0 0 var(--space-xs);font-weight:600">Errors</h4>
              <p style="margin:0;font-size:var(--font-sm);color:var(--text-secondary)">Failed scenarios grouped by error type — assertion errors, timeouts, runtime errors, and compromised tests. Helps identify patterns in failures.</p>
            </div>
            <div style="padding:var(--space-md);background:var(--bg-primary);border-radius:var(--radius-sm)">
              <h4 style="margin:0 0 var(--space-xs);font-weight:600">Consistency</h4>
              <p style="margin:0;font-size:var(--font-sm);color:var(--text-secondary)">Tests with inconsistent outcomes across recent runs. Identifies flaky tests that pass and fail unpredictably, undermining confidence in your test suite.</p>
            </div>
            <div style="padding:var(--space-md);background:var(--bg-primary);border-radius:var(--radius-sm)">
              <h4 style="margin:0 0 var(--space-xs);font-weight:600">Timeline</h4>
              <p style="margin:0;font-size:var(--font-sm);color:var(--text-secondary)">Execution timeline showing when each scenario ran and how long it took. Useful for identifying slow tests and optimising execution time.</p>
            </div>
            <div style="padding:var(--space-md);background:var(--bg-primary);border-radius:var(--radius-sm)">
              <h4 style="margin:0 0 var(--space-xs);font-weight:600">Test Runs</h4>
              <p style="margin:0;font-size:var(--font-sm);color:var(--text-secondary)">History of all test executions with trend analysis. Compare results across runs to identify regressions or improvements over time.</p>
            </div>
          </div>
        </section>

        <section style="margin-bottom:var(--space-xl)">
          <h3 style="font-size:var(--font-lg);font-weight:600;margin:0 0 var(--space-md)">Improving confidence</h3>
          <p>To increase the confidence score for a capability:</p>
          <ul style="padding-left:var(--space-lg);margin:var(--space-sm) 0;font-size:var(--font-sm);color:var(--text-secondary);line-height:1.8">
            <li><strong>Fix failing tests</strong> — each failure directly reduces the pass rate component</li>
            <li><strong>Implement pending scenarios</strong> — unimplemented tests reduce completeness</li>
            <li><strong>Stabilise flaky tests</strong> — inconsistent outcomes reduce the consistency component</li>
            <li><strong>Run tests regularly</strong> — more execution history gives consistency a stronger signal</li>
          </ul>
        </section>

        <section>
          <h3 style="font-size:var(--font-lg);font-weight:600;margin:0 0 var(--space-md)">Learn more</h3>
          <p style="font-size:var(--font-sm);color:var(--text-secondary)">
            Visit <a href="https://serenity-js.org/handbook/reporting/" target="_blank" rel="noopener" style="color:var(--accent);text-decoration:none;font-weight:500">serenity-js.org/handbook/reporting</a> for
            comprehensive documentation on configuring reporters, customising reports, and integrating Serenity/JS into your CI/CD pipeline.
          </p>
        </section>
      </div>
    </div>
  `;
}
