window.esdocSearchIndex = [
  [
    "@serenity-js/rest/lib/screenplay/abilities~callanapi",
    "class/src/screenplay/abilities/CallAnApi.ts~CallAnApi.html",
    "<span>CallAnApi</span> <span class=\"search-result-import-path\">@serenity-js/rest/lib/screenplay/abilities</span>",
    "class"
  ],
  [
    "@serenity-js/rest/lib/screenplay/interactions~changeapiurl",
    "class/src/screenplay/interactions/ChangeApiUrl.ts~ChangeApiUrl.html",
    "<span>ChangeApiUrl</span> <span class=\"search-result-import-path\">@serenity-js/rest/lib/screenplay/interactions</span>",
    "class"
  ],
  [
    "@serenity-js/rest/lib/model~deleterequest",
    "class/src/model/DeleteRequest.ts~DeleteRequest.html",
    "<span>DeleteRequest</span> <span class=\"search-result-import-path\">@serenity-js/rest/lib/model</span>",
    "class"
  ],
  [
    "@serenity-js/rest/lib/model~getrequest",
    "class/src/model/GetRequest.ts~GetRequest.html",
    "<span>GetRequest</span> <span class=\"search-result-import-path\">@serenity-js/rest/lib/model</span>",
    "class"
  ],
  [
    "@serenity-js/rest/lib/model~httprequest",
    "class/src/model/HTTPRequest.ts~HTTPRequest.html",
    "<span>HTTPRequest</span> <span class=\"search-result-import-path\">@serenity-js/rest/lib/model</span>",
    "class"
  ],
  [
    "@serenity-js/rest/lib/model~headrequest",
    "class/src/model/HeadRequest.ts~HeadRequest.html",
    "<span>HeadRequest</span> <span class=\"search-result-import-path\">@serenity-js/rest/lib/model</span>",
    "class"
  ],
  [
    "@serenity-js/rest/lib/screenplay/questions~lastresponse",
    "class/src/screenplay/questions/LastResponse.ts~LastResponse.html",
    "<span>LastResponse</span> <span class=\"search-result-import-path\">@serenity-js/rest/lib/screenplay/questions</span>",
    "class"
  ],
  [
    "@serenity-js/rest/lib/model~optionsrequest",
    "class/src/model/OptionsRequest.ts~OptionsRequest.html",
    "<span>OptionsRequest</span> <span class=\"search-result-import-path\">@serenity-js/rest/lib/model</span>",
    "class"
  ],
  [
    "@serenity-js/rest/lib/model~patchrequest",
    "class/src/model/PatchRequest.ts~PatchRequest.html",
    "<span>PatchRequest</span> <span class=\"search-result-import-path\">@serenity-js/rest/lib/model</span>",
    "class"
  ],
  [
    "@serenity-js/rest/lib/model~postrequest",
    "class/src/model/PostRequest.ts~PostRequest.html",
    "<span>PostRequest</span> <span class=\"search-result-import-path\">@serenity-js/rest/lib/model</span>",
    "class"
  ],
  [
    "@serenity-js/rest/lib/model~putrequest",
    "class/src/model/PutRequest.ts~PutRequest.html",
    "<span>PutRequest</span> <span class=\"search-result-import-path\">@serenity-js/rest/lib/model</span>",
    "class"
  ],
  [
    "@serenity-js/rest/lib/screenplay/interactions~send",
    "class/src/screenplay/interactions/Send.ts~Send.html",
    "<span>Send</span> <span class=\"search-result-import-path\">@serenity-js/rest/lib/screenplay/interactions</span>",
    "class"
  ],
  [
    "@serenity-js/assertions/lib/expectations~and",
    "/modules/assertions/function/src/expectations/and.ts~and.html",
    "@serenity-js/assertions/lib/expectations~and",
    "external"
  ],
  [
    "@serenity-js/assertions/lib/expectations~contain",
    "/modules/assertions/function/src/expectations/contain.ts~contain.html",
    "@serenity-js/assertions/lib/expectations~contain",
    "external"
  ],
  [
    "@serenity-js/assertions/lib/expectations~containatleastoneitemthat",
    "/modules/assertions/function/src/expectations/containAtLeastOneItemThat.ts~containAtLeastOneItemThat.html",
    "@serenity-js/assertions/lib/expectations~containAtLeastOneItemThat",
    "external"
  ],
  [
    "@serenity-js/assertions/lib/expectations~containitemswhereeachitem",
    "/modules/assertions/function/src/expectations/containItemsWhereEachItem.ts~containItemsWhereEachItem.html",
    "@serenity-js/assertions/lib/expectations~containItemsWhereEachItem",
    "external"
  ],
  [
    "@serenity-js/assertions/lib/expectations~endswith",
    "/modules/assertions/function/src/expectations/endsWith.ts~endsWith.html",
    "@serenity-js/assertions/lib/expectations~endsWith",
    "external"
  ],
  [
    "@serenity-js/assertions/lib/expectations~equals",
    "/modules/assertions/function/src/expectations/equals.ts~equals.html",
    "@serenity-js/assertions/lib/expectations~equals",
    "external"
  ],
  [
    "@serenity-js/assertions/lib/expectations~includes",
    "/modules/assertions/function/src/expectations/includes.ts~includes.html",
    "@serenity-js/assertions/lib/expectations~includes",
    "external"
  ],
  [
    "@serenity-js/assertions/lib/expectations~isafter",
    "/modules/assertions/function/src/expectations/isAfter.ts~isAfter.html",
    "@serenity-js/assertions/lib/expectations~isAfter",
    "external"
  ],
  [
    "@serenity-js/assertions/lib/expectations~isbefore",
    "/modules/assertions/function/src/expectations/isBefore.ts~isBefore.html",
    "@serenity-js/assertions/lib/expectations~isBefore",
    "external"
  ],
  [
    "@serenity-js/assertions/lib/expectations~isgreaterthan",
    "/modules/assertions/function/src/expectations/isGreaterThan.ts~isGreaterThan.html",
    "@serenity-js/assertions/lib/expectations~isGreaterThan",
    "external"
  ],
  [
    "@serenity-js/assertions/lib/expectations~islessthan",
    "/modules/assertions/function/src/expectations/isLessThan.ts~isLessThan.html",
    "@serenity-js/assertions/lib/expectations~isLessThan",
    "external"
  ],
  [
    "@serenity-js/assertions/lib/expectations~matches",
    "/modules/assertions/function/src/expectations/matches.ts~matches.html",
    "@serenity-js/assertions/lib/expectations~matches",
    "external"
  ],
  [
    "@serenity-js/assertions/lib/expectations~not",
    "/modules/assertions/function/src/expectations/not.ts~not.html",
    "@serenity-js/assertions/lib/expectations~not",
    "external"
  ],
  [
    "@serenity-js/assertions/lib/expectations~or",
    "/modules/assertions/function/src/expectations/or.ts~or.html",
    "@serenity-js/assertions/lib/expectations~or",
    "external"
  ],
  [
    "@serenity-js/assertions/lib/expectations~property",
    "/modules/assertions/function/src/expectations/property.ts~property.html",
    "@serenity-js/assertions/lib/expectations~property",
    "external"
  ],
  [
    "@serenity-js/assertions/lib/expectations~startswith",
    "/modules/assertions/function/src/expectations/startsWith.ts~startsWith.html",
    "@serenity-js/assertions/lib/expectations~startsWith",
    "external"
  ],
  [
    "@serenity-js/assertions~check",
    "/modules/assertions/class/src/Check.ts~Check.html",
    "@serenity-js/assertions~Check",
    "external"
  ],
  [
    "@serenity-js/assertions~ensure",
    "/modules/assertions/class/src/Ensure.ts~Ensure.html",
    "@serenity-js/assertions~Ensure",
    "external"
  ],
  [
    "@serenity-js/assertions~expectation",
    "/modules/assertions/class/src/Expectation.ts~Expectation.html",
    "@serenity-js/assertions~Expectation",
    "external"
  ],
  [
    "@serenity-js/assertions~expectationmet",
    "/modules/assertions/class/src/outcomes.ts~ExpectationMet.html",
    "@serenity-js/assertions~ExpectationMet",
    "external"
  ],
  [
    "@serenity-js/assertions~expectationnotmet",
    "/modules/assertions/class/src/outcomes.ts~ExpectationNotMet.html",
    "@serenity-js/assertions~ExpectationNotMet",
    "external"
  ],
  [
    "@serenity-js/assertions~outcome",
    "/modules/assertions/class/src/outcomes.ts~Outcome.html",
    "@serenity-js/assertions~Outcome",
    "external"
  ],
  [
    "@serenity-js/core/lib/errors~assertionerror",
    "/modules/core/class/src/errors/AssertionError.ts~AssertionError.html",
    "@serenity-js/core/lib/errors~AssertionError",
    "external"
  ],
  [
    "@serenity-js/core/lib/errors~configurationerror",
    "/modules/core/class/src/errors/ConfigurationError.ts~ConfigurationError.html",
    "@serenity-js/core/lib/errors~ConfigurationError",
    "external"
  ],
  [
    "@serenity-js/core/lib/errors~implementationpendingerror",
    "/modules/core/class/src/errors/ImplementationPendingError.ts~ImplementationPendingError.html",
    "@serenity-js/core/lib/errors~ImplementationPendingError",
    "external"
  ],
  [
    "@serenity-js/core/lib/errors~logicerror",
    "/modules/core/class/src/errors/LogicError.ts~LogicError.html",
    "@serenity-js/core/lib/errors~LogicError",
    "external"
  ],
  [
    "@serenity-js/core/lib/errors~runtimeerror",
    "/modules/core/class/src/errors/RuntimeError.ts~RuntimeError.html",
    "@serenity-js/core/lib/errors~RuntimeError",
    "external"
  ],
  [
    "@serenity-js/core/lib/errors~testcompromisederror",
    "/modules/core/class/src/errors/TestCompromisedError.ts~TestCompromisedError.html",
    "@serenity-js/core/lib/errors~TestCompromisedError",
    "external"
  ],
  [
    "@serenity-js/core/lib/errors~unknownerror",
    "/modules/core/class/src/errors/UnknownError.ts~UnknownError.html",
    "@serenity-js/core/lib/errors~UnknownError",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~activityfinished",
    "/modules/core/class/src/events/ActivityFinished.ts~ActivityFinished.html",
    "@serenity-js/core/lib/events~ActivityFinished",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~activityrelatedartifactarchived",
    "/modules/core/class/src/events/ActivityRelatedArtifactArchived.ts~ActivityRelatedArtifactArchived.html",
    "@serenity-js/core/lib/events~ActivityRelatedArtifactArchived",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~activityrelatedartifactgenerated",
    "/modules/core/class/src/events/ActivityRelatedArtifactGenerated.ts~ActivityRelatedArtifactGenerated.html",
    "@serenity-js/core/lib/events~ActivityRelatedArtifactGenerated",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~activitystarts",
    "/modules/core/class/src/events/ActivityStarts.ts~ActivityStarts.html",
    "@serenity-js/core/lib/events~ActivityStarts",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~artifactarchived",
    "/modules/core/class/src/events/ArtifactArchived.ts~ArtifactArchived.html",
    "@serenity-js/core/lib/events~ArtifactArchived",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~artifactgenerated",
    "/modules/core/class/src/events/ArtifactGenerated.ts~ArtifactGenerated.html",
    "@serenity-js/core/lib/events~ArtifactGenerated",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~asyncoperationattempted",
    "/modules/core/class/src/events/AsyncOperationAttempted.ts~AsyncOperationAttempted.html",
    "@serenity-js/core/lib/events~AsyncOperationAttempted",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~asyncoperationcompleted",
    "/modules/core/class/src/events/AsyncOperationCompleted.ts~AsyncOperationCompleted.html",
    "@serenity-js/core/lib/events~AsyncOperationCompleted",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~asyncoperationfailed",
    "/modules/core/class/src/events/AsyncOperationFailed.ts~AsyncOperationFailed.html",
    "@serenity-js/core/lib/events~AsyncOperationFailed",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~domainevent",
    "/modules/core/class/src/events/DomainEvent.ts~DomainEvent.html",
    "@serenity-js/core/lib/events~DomainEvent",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~featurenarrativedetected",
    "/modules/core/class/src/events/FeatureNarrativeDetected.ts~FeatureNarrativeDetected.html",
    "@serenity-js/core/lib/events~FeatureNarrativeDetected",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~interactionfinished",
    "/modules/core/class/src/events/InteractionFinished.ts~InteractionFinished.html",
    "@serenity-js/core/lib/events~InteractionFinished",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~interactionstarts",
    "/modules/core/class/src/events/InteractionStarts.ts~InteractionStarts.html",
    "@serenity-js/core/lib/events~InteractionStarts",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~scenebackgrounddetected",
    "/modules/core/class/src/events/SceneBackgroundDetected.ts~SceneBackgroundDetected.html",
    "@serenity-js/core/lib/events~SceneBackgroundDetected",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~scenedescriptiondetected",
    "/modules/core/class/src/events/SceneDescriptionDetected.ts~SceneDescriptionDetected.html",
    "@serenity-js/core/lib/events~SceneDescriptionDetected",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~scenefinished",
    "/modules/core/class/src/events/SceneFinished.ts~SceneFinished.html",
    "@serenity-js/core/lib/events~SceneFinished",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~scenefinishes",
    "/modules/core/class/src/events/SceneFinishes.ts~SceneFinishes.html",
    "@serenity-js/core/lib/events~SceneFinishes",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~sceneparametersdetected",
    "/modules/core/class/src/events/SceneParametersDetected.ts~SceneParametersDetected.html",
    "@serenity-js/core/lib/events~SceneParametersDetected",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~scenesequencedetected",
    "/modules/core/class/src/events/SceneSequenceDetected.ts~SceneSequenceDetected.html",
    "@serenity-js/core/lib/events~SceneSequenceDetected",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~scenestarts",
    "/modules/core/class/src/events/SceneStarts.ts~SceneStarts.html",
    "@serenity-js/core/lib/events~SceneStarts",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~scenetagged",
    "/modules/core/class/src/events/SceneTagged.ts~SceneTagged.html",
    "@serenity-js/core/lib/events~SceneTagged",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~scenetemplatedetected",
    "/modules/core/class/src/events/SceneTemplateDetected.ts~SceneTemplateDetected.html",
    "@serenity-js/core/lib/events~SceneTemplateDetected",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~taskfinished",
    "/modules/core/class/src/events/TaskFinished.ts~TaskFinished.html",
    "@serenity-js/core/lib/events~TaskFinished",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~taskstarts",
    "/modules/core/class/src/events/TaskStarts.ts~TaskStarts.html",
    "@serenity-js/core/lib/events~TaskStarts",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~testrunfinished",
    "/modules/core/class/src/events/TestRunFinished.ts~TestRunFinished.html",
    "@serenity-js/core/lib/events~TestRunFinished",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~testrunfinishes",
    "/modules/core/class/src/events/TestRunFinishes.ts~TestRunFinishes.html",
    "@serenity-js/core/lib/events~TestRunFinishes",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~testrunnerdetected",
    "/modules/core/class/src/events/TestRunnerDetected.ts~TestRunnerDetected.html",
    "@serenity-js/core/lib/events~TestRunnerDetected",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~testsuitefinished",
    "/modules/core/class/src/events/TestSuiteFinished.ts~TestSuiteFinished.html",
    "@serenity-js/core/lib/events~TestSuiteFinished",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~testsuitestarts",
    "/modules/core/class/src/events/TestSuiteStarts.ts~TestSuiteStarts.html",
    "@serenity-js/core/lib/events~TestSuiteStarts",
    "external"
  ],
  [
    "@serenity-js/core/lib/io~assertionreportdiffer",
    "/modules/core/class/src/io/AssertionReportDiffer.ts~AssertionReportDiffer.html",
    "@serenity-js/core/lib/io~AssertionReportDiffer",
    "external"
  ],
  [
    "@serenity-js/core/lib/io~errorserialiser",
    "/modules/core/class/src/io/ErrorSerialiser.ts~ErrorSerialiser.html",
    "@serenity-js/core/lib/io~ErrorSerialiser",
    "external"
  ],
  [
    "@serenity-js/core/lib/io~filesystem",
    "/modules/core/class/src/io/FileSystem.ts~FileSystem.html",
    "@serenity-js/core/lib/io~FileSystem",
    "external"
  ],
  [
    "@serenity-js/core/lib/io~filesystemlocation",
    "/modules/core/class/src/io/FileSystemLocation.ts~FileSystemLocation.html",
    "@serenity-js/core/lib/io~FileSystemLocation",
    "external"
  ],
  [
    "@serenity-js/core/lib/io~moduleloader",
    "/modules/core/class/src/io/ModuleLoader.ts~ModuleLoader.html",
    "@serenity-js/core/lib/io~ModuleLoader",
    "external"
  ],
  [
    "@serenity-js/core/lib/io~path",
    "/modules/core/class/src/io/Path.ts~Path.html",
    "@serenity-js/core/lib/io~Path",
    "external"
  ],
  [
    "@serenity-js/core/lib/io~serialisederror",
    "/modules/core/class/src/io/ErrorSerialiser.ts~SerialisedError.html",
    "@serenity-js/core/lib/io~SerialisedError",
    "external"
  ],
  [
    "@serenity-js/core/lib/io~version",
    "/modules/core/class/src/io/Version.ts~Version.html",
    "@serenity-js/core/lib/io~Version",
    "external"
  ],
  [
    "@serenity-js/core/lib/io~formatted",
    "/modules/core/function/src/io/formatted.ts~formatted.html",
    "@serenity-js/core/lib/io~formatted",
    "external"
  ],
  [
    "@serenity-js/core/lib/io~inspected",
    "/modules/core/function/src/io/inspected.ts~inspected.html",
    "@serenity-js/core/lib/io~inspected",
    "external"
  ],
  [
    "@serenity-js/core/lib/io~trimmed",
    "/modules/core/function/src/io/trimmed.ts~trimmed.html",
    "@serenity-js/core/lib/io~trimmed",
    "external"
  ],
  [
    "@serenity-js/core/lib/model/artifacts~assertionreport",
    "/modules/core/class/src/model/artifacts/AssertionReport.ts~AssertionReport.html",
    "@serenity-js/core/lib/model/artifacts~AssertionReport",
    "external"
  ],
  [
    "@serenity-js/core/lib/model/artifacts~httprequestresponse",
    "/modules/core/class/src/model/artifacts/HTTPRequestResponse.ts~HTTPRequestResponse.html",
    "@serenity-js/core/lib/model/artifacts~HTTPRequestResponse",
    "external"
  ],
  [
    "@serenity-js/core/lib/model/artifacts~jsondata",
    "/modules/core/class/src/model/artifacts/JSONData.ts~JSONData.html",
    "@serenity-js/core/lib/model/artifacts~JSONData",
    "external"
  ],
  [
    "@serenity-js/core/lib/model/artifacts~logentry",
    "/modules/core/class/src/model/artifacts/LogEntry.ts~LogEntry.html",
    "@serenity-js/core/lib/model/artifacts~LogEntry",
    "external"
  ],
  [
    "@serenity-js/core/lib/model/artifacts~photo",
    "/modules/core/class/src/model/artifacts/Photo.ts~Photo.html",
    "@serenity-js/core/lib/model/artifacts~Photo",
    "external"
  ],
  [
    "@serenity-js/core/lib/model/artifacts~requestandresponse",
    "/modules/core/class/src/model/artifacts/HTTPRequestResponse.ts~RequestAndResponse.html",
    "@serenity-js/core/lib/model/artifacts~RequestAndResponse",
    "external"
  ],
  [
    "@serenity-js/core/lib/model/artifacts~testreport",
    "/modules/core/class/src/model/artifacts/TestReport.ts~TestReport.html",
    "@serenity-js/core/lib/model/artifacts~TestReport",
    "external"
  ],
  [
    "@serenity-js/core/lib/model/artifacts~textdata",
    "/modules/core/class/src/model/artifacts/TextData.ts~TextData.html",
    "@serenity-js/core/lib/model/artifacts~TextData",
    "external"
  ],
  [
    "@serenity-js/core/lib/model/tags~arbitrarytag",
    "/modules/core/class/src/model/tags/ArbitraryTag.ts~ArbitraryTag.html",
    "@serenity-js/core/lib/model/tags~ArbitraryTag",
    "external"
  ],
  [
    "@serenity-js/core/lib/model/tags~browsertag",
    "/modules/core/class/src/model/tags/BrowserTag.ts~BrowserTag.html",
    "@serenity-js/core/lib/model/tags~BrowserTag",
    "external"
  ],
  [
    "@serenity-js/core/lib/model/tags~capabilitytag",
    "/modules/core/class/src/model/tags/CapabilityTag.ts~CapabilityTag.html",
    "@serenity-js/core/lib/model/tags~CapabilityTag",
    "external"
  ],
  [
    "@serenity-js/core/lib/model/tags~contexttag",
    "/modules/core/class/src/model/tags/ContextTag.ts~ContextTag.html",
    "@serenity-js/core/lib/model/tags~ContextTag",
    "external"
  ],
  [
    "@serenity-js/core/lib/model/tags~featuretag",
    "/modules/core/class/src/model/tags/FeatureTag.ts~FeatureTag.html",
    "@serenity-js/core/lib/model/tags~FeatureTag",
    "external"
  ],
  [
    "@serenity-js/core/lib/model/tags~issuetag",
    "/modules/core/class/src/model/tags/IssueTag.ts~IssueTag.html",
    "@serenity-js/core/lib/model/tags~IssueTag",
    "external"
  ],
  [
    "@serenity-js/core/lib/model/tags~manualtag",
    "/modules/core/class/src/model/tags/ManualTag.ts~ManualTag.html",
    "@serenity-js/core/lib/model/tags~ManualTag",
    "external"
  ],
  [
    "@serenity-js/core/lib/model/tags~tag",
    "/modules/core/class/src/model/tags/Tag.ts~Tag.html",
    "@serenity-js/core/lib/model/tags~Tag",
    "external"
  ],
  [
    "@serenity-js/core/lib/model/tags~themetag",
    "/modules/core/class/src/model/tags/ThemeTag.ts~ThemeTag.html",
    "@serenity-js/core/lib/model/tags~ThemeTag",
    "external"
  ],
  [
    "@serenity-js/core/lib/model~activitydetails",
    "/modules/core/class/src/model/ActivityDetails.ts~ActivityDetails.html",
    "@serenity-js/core/lib/model~ActivityDetails",
    "external"
  ],
  [
    "@serenity-js/core/lib/model~artifact",
    "/modules/core/class/src/model/Artifact.ts~Artifact.html",
    "@serenity-js/core/lib/model~Artifact",
    "external"
  ],
  [
    "@serenity-js/core/lib/model~category",
    "/modules/core/class/src/model/Category.ts~Category.html",
    "@serenity-js/core/lib/model~Category",
    "external"
  ],
  [
    "@serenity-js/core/lib/model~correlationid",
    "/modules/core/class/src/model/CorrelationId.ts~CorrelationId.html",
    "@serenity-js/core/lib/model~CorrelationId",
    "external"
  ],
  [
    "@serenity-js/core/lib/model~description",
    "/modules/core/class/src/model/Description.ts~Description.html",
    "@serenity-js/core/lib/model~Description",
    "external"
  ],
  [
    "@serenity-js/core/lib/model~duration",
    "/modules/core/class/src/model/Duration.ts~Duration.html",
    "@serenity-js/core/lib/model~Duration",
    "external"
  ],
  [
    "@serenity-js/core/lib/model~executioncompromised",
    "/modules/core/class/src/model/outcomes.ts~ExecutionCompromised.html",
    "@serenity-js/core/lib/model~ExecutionCompromised",
    "external"
  ],
  [
    "@serenity-js/core/lib/model~executionfailedwithassertionerror",
    "/modules/core/class/src/model/outcomes.ts~ExecutionFailedWithAssertionError.html",
    "@serenity-js/core/lib/model~ExecutionFailedWithAssertionError",
    "external"
  ],
  [
    "@serenity-js/core/lib/model~executionfailedwitherror",
    "/modules/core/class/src/model/outcomes.ts~ExecutionFailedWithError.html",
    "@serenity-js/core/lib/model~ExecutionFailedWithError",
    "external"
  ],
  [
    "@serenity-js/core/lib/model~executionignored",
    "/modules/core/class/src/model/outcomes.ts~ExecutionIgnored.html",
    "@serenity-js/core/lib/model~ExecutionIgnored",
    "external"
  ],
  [
    "@serenity-js/core/lib/model~executionskipped",
    "/modules/core/class/src/model/outcomes.ts~ExecutionSkipped.html",
    "@serenity-js/core/lib/model~ExecutionSkipped",
    "external"
  ],
  [
    "@serenity-js/core/lib/model~executionsuccessful",
    "/modules/core/class/src/model/outcomes.ts~ExecutionSuccessful.html",
    "@serenity-js/core/lib/model~ExecutionSuccessful",
    "external"
  ],
  [
    "@serenity-js/core/lib/model~implementationpending",
    "/modules/core/class/src/model/outcomes.ts~ImplementationPending.html",
    "@serenity-js/core/lib/model~ImplementationPending",
    "external"
  ],
  [
    "@serenity-js/core/lib/model~name",
    "/modules/core/class/src/model/Name.ts~Name.html",
    "@serenity-js/core/lib/model~Name",
    "external"
  ],
  [
    "@serenity-js/core/lib/model~outcome",
    "/modules/core/class/src/model/outcomes.ts~Outcome.html",
    "@serenity-js/core/lib/model~Outcome",
    "external"
  ],
  [
    "@serenity-js/core/lib/model~problemindication",
    "/modules/core/class/src/model/outcomes.ts~ProblemIndication.html",
    "@serenity-js/core/lib/model~ProblemIndication",
    "external"
  ],
  [
    "@serenity-js/core/lib/model~scenariodetails",
    "/modules/core/class/src/model/ScenarioDetails.ts~ScenarioDetails.html",
    "@serenity-js/core/lib/model~ScenarioDetails",
    "external"
  ],
  [
    "@serenity-js/core/lib/model~scenarioparameters",
    "/modules/core/class/src/model/ScenarioParameters.ts~ScenarioParameters.html",
    "@serenity-js/core/lib/model~ScenarioParameters",
    "external"
  ],
  [
    "@serenity-js/core/lib/model~testsuitedetails",
    "/modules/core/class/src/model/TestSuiteDetails.ts~TestSuiteDetails.html",
    "@serenity-js/core/lib/model~TestSuiteDetails",
    "external"
  ],
  [
    "@serenity-js/core/lib/model~timestamp",
    "/modules/core/class/src/model/Timestamp.ts~Timestamp.html",
    "@serenity-js/core/lib/model~Timestamp",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay/abilities~takenotes",
    "/modules/core/class/src/screenplay/abilities/TakeNotes.ts~TakeNotes.html",
    "@serenity-js/core/lib/screenplay/abilities~TakeNotes",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay/actor~actor",
    "/modules/core/class/src/screenplay/actor/Actor.ts~Actor.html",
    "@serenity-js/core/lib/screenplay/actor~Actor",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay/actor~answersquestions",
    "/modules/core/class/src/screenplay/actor/AnswersQuestions.ts~AnswersQuestions.html",
    "@serenity-js/core/lib/screenplay/actor~AnswersQuestions",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay/actor~canhaveabilities",
    "/modules/core/class/src/screenplay/actor/CanHaveAbilities.ts~CanHaveAbilities.html",
    "@serenity-js/core/lib/screenplay/actor~CanHaveAbilities",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay/actor~collectsartifacts",
    "/modules/core/class/src/screenplay/actor/CollectsArtifacts.ts~CollectsArtifacts.html",
    "@serenity-js/core/lib/screenplay/actor~CollectsArtifacts",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay/actor~performsactivities",
    "/modules/core/class/src/screenplay/actor/PerformsActivities.ts~PerformsActivities.html",
    "@serenity-js/core/lib/screenplay/actor~PerformsActivities",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay/actor~usesabilities",
    "/modules/core/class/src/screenplay/actor/UsesAbilities.ts~UsesAbilities.html",
    "@serenity-js/core/lib/screenplay/actor~UsesAbilities",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay/interactions~log",
    "/modules/core/class/src/screenplay/interactions/Log.ts~Log.html",
    "@serenity-js/core/lib/screenplay/interactions~Log",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay/interactions~see",
    "/modules/core/class/src/screenplay/interactions/See.ts~See.html",
    "@serenity-js/core/lib/screenplay/interactions~See",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay/interactions~takenote",
    "/modules/core/class/src/screenplay/interactions/TakeNote.ts~TakeNote.html",
    "@serenity-js/core/lib/screenplay/interactions~TakeNote",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay/questions~note",
    "/modules/core/class/src/screenplay/questions/Note.ts~Note.html",
    "@serenity-js/core/lib/screenplay/questions~Note",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay/questions~transform",
    "/modules/core/class/src/screenplay/questions/Transform.ts~Transform.html",
    "@serenity-js/core/lib/screenplay/questions~Transform",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay~ability",
    "/modules/core/class/src/screenplay/Ability.ts~Ability.html",
    "@serenity-js/core/lib/screenplay~Ability",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay~abilitytype",
    "/modules/core/class/src/screenplay/AbilityType.ts~AbilityType.html",
    "@serenity-js/core/lib/screenplay~AbilityType",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay~activity",
    "/modules/core/class/src/screenplay/Activity.ts~Activity.html",
    "@serenity-js/core/lib/screenplay~Activity",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay~interaction",
    "/modules/core/class/src/screenplay/Interaction.ts~Interaction.html",
    "@serenity-js/core/lib/screenplay~Interaction",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay~question",
    "/modules/core/class/src/screenplay/Question.ts~Question.html",
    "@serenity-js/core/lib/screenplay~Question",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay~task",
    "/modules/core/class/src/screenplay/Task.ts~Task.html",
    "@serenity-js/core/lib/screenplay~Task",
    "external"
  ],
  [
    "@serenity-js/core/lib/stage/crew/artifact-archiver~artifactarchiver",
    "/modules/core/class/src/stage/crew/artifact-archiver/ArtifactArchiver.ts~ArtifactArchiver.html",
    "@serenity-js/core/lib/stage/crew/artifact-archiver~ArtifactArchiver",
    "external"
  ],
  [
    "@serenity-js/core/lib/stage/crew/stream-reporter~streamreporter",
    "/modules/core/class/src/stage/crew/stream-reporter/StreamReporter.ts~StreamReporter.html",
    "@serenity-js/core/lib/stage/crew/stream-reporter~StreamReporter",
    "external"
  ],
  [
    "@serenity-js/core/lib/stage~cast",
    "/modules/core/class/src/stage/Cast.ts~Cast.html",
    "@serenity-js/core/lib/stage~Cast",
    "external"
  ],
  [
    "@serenity-js/core/lib/stage~clock",
    "/modules/core/class/src/stage/Clock.ts~Clock.html",
    "@serenity-js/core/lib/stage~Clock",
    "external"
  ],
  [
    "@serenity-js/core/lib/stage~dressingroom",
    "/modules/core/class/src/stage/DressingRoom.ts~DressingRoom.html",
    "@serenity-js/core/lib/stage~DressingRoom",
    "external"
  ],
  [
    "@serenity-js/core/lib/stage~stage",
    "/modules/core/class/src/stage/Stage.ts~Stage.html",
    "@serenity-js/core/lib/stage~Stage",
    "external"
  ],
  [
    "@serenity-js/core/lib/stage~stagecrewmember",
    "/modules/core/class/src/stage/StageCrewMember.ts~StageCrewMember.html",
    "@serenity-js/core/lib/stage~StageCrewMember",
    "external"
  ],
  [
    "@serenity-js/core/lib/stage~stagemanager",
    "/modules/core/class/src/stage/StageManager.ts~StageManager.html",
    "@serenity-js/core/lib/stage~StageManager",
    "external"
  ],
  [
    "@serenity-js/core/lib/stage~withstage",
    "/modules/core/class/src/stage/WithStage.ts~WithStage.html",
    "@serenity-js/core/lib/stage~WithStage",
    "external"
  ],
  [
    "@serenity-js/core~serenity",
    "/modules/core/class/src/Serenity.ts~Serenity.html",
    "@serenity-js/core~Serenity",
    "external"
  ],
  [
    "@serenity-js/core~serenityconfig",
    "/modules/core/class/src/SerenityConfig.ts~SerenityConfig.html",
    "@serenity-js/core~SerenityConfig",
    "external"
  ],
  [
    "@serenity-js/core~actorcalled",
    "/modules/core/function/src/instance.ts~actorCalled.html",
    "@serenity-js/core~actorCalled",
    "external"
  ],
  [
    "@serenity-js/core~actorinthespotlight",
    "/modules/core/function/src/instance.ts~actorInTheSpotlight.html",
    "@serenity-js/core~actorInTheSpotlight",
    "external"
  ],
  [
    "@serenity-js/core~configure",
    "/modules/core/function/src/instance.ts~configure.html",
    "@serenity-js/core~configure",
    "external"
  ],
  [
    "@serenity-js/core~engage",
    "/modules/core/function/src/instance.ts~engage.html",
    "@serenity-js/core~engage",
    "external"
  ],
  [
    "@serenity-js/core~serenity",
    "/modules/core/variable/src/instance.ts~serenity.html",
    "@serenity-js/core~serenity",
    "external"
  ],
  [
    "callanapi src/screenplay/abilities/callanapi.ts~callanapi,callanapi",
    "test-file/spec/screenplay/abilities/CallAnApi.spec.ts.html#lineNumber12",
    "CallAnApi",
    "test"
  ],
  [
    "callanapi callanapi.request callanapi.maplastresponse src/screenplay/abilities/callanapi.ts~callanapi,callanapi src/screenplay/abilities/callanapi.ts~callanapi#request,callanapi.request src/screenplay/abilities/callanapi.ts~callanapi#maplastresponse,callanapi.maplastresponse",
    "test-file/spec/screenplay/abilities/CallAnApi.spec.ts.html#lineNumber81",
    "CallAnApi caches the last response even when the server responds with an error. As long is it responds.",
    "test"
  ],
  [
    "callanapi callanapi.maplastresponse src/screenplay/abilities/callanapi.ts~callanapi,callanapi src/screenplay/abilities/callanapi.ts~callanapi#maplastresponse,callanapi.maplastresponse",
    "test-file/spec/screenplay/abilities/CallAnApi.spec.ts.html#lineNumber64",
    "CallAnApi caches the last response so that it can be easily asserted on",
    "test"
  ],
  [
    "callanapi callanapi.at src/screenplay/abilities/callanapi.ts~callanapi,callanapi src/screenplay/abilities/callanapi.ts~callanapi.at,callanapi.at",
    "test-file/spec/screenplay/abilities/CallAnApi.spec.ts.html#lineNumber38",
    "CallAnApi provides a convenient factory method to be used when no custom configuration is required",
    "test"
  ],
  [
    "callanapi callanapi.using src/screenplay/abilities/callanapi.ts~callanapi,callanapi src/screenplay/abilities/callanapi.ts~callanapi.using,callanapi.using",
    "test-file/spec/screenplay/abilities/CallAnApi.spec.ts.html#lineNumber51",
    "CallAnApi provides a factory method to be used when custom configuration is required",
    "test"
  ],
  [
    "",
    "test-file/spec/screenplay/abilities/CallAnApi.spec.ts.html#lineNumber93",
    "CallAnApi when dealing with errors",
    "test"
  ],
  [
    "callanapi callanapi.maplastresponse src/screenplay/abilities/callanapi.ts~callanapi,callanapi src/screenplay/abilities/callanapi.ts~callanapi#maplastresponse,callanapi.maplastresponse",
    "test-file/spec/screenplay/abilities/CallAnApi.spec.ts.html#lineNumber98",
    "CallAnApi when dealing with errors complains if you try to retrieve the last response before making an API call",
    "test"
  ],
  [
    "callanapi callanapi.request src/screenplay/abilities/callanapi.ts~callanapi,callanapi src/screenplay/abilities/callanapi.ts~callanapi#request,callanapi.request",
    "test-file/spec/screenplay/abilities/CallAnApi.spec.ts.html#lineNumber109",
    "CallAnApi when dealing with errors complains when provided with invalid Axios configuration",
    "test"
  ],
  [
    "callanapi callanapi.request src/screenplay/abilities/callanapi.ts~callanapi,callanapi src/screenplay/abilities/callanapi.ts~callanapi#request,callanapi.request",
    "test-file/spec/screenplay/abilities/CallAnApi.spec.ts.html#lineNumber127",
    "CallAnApi when dealing with errors complains when the API call times out",
    "test"
  ],
  [
    "callanapi callanapi.request src/screenplay/abilities/callanapi.ts~callanapi,callanapi src/screenplay/abilities/callanapi.ts~callanapi#request,callanapi.request",
    "test-file/spec/screenplay/abilities/CallAnApi.spec.ts.html#lineNumber159",
    "CallAnApi when dealing with errors complains when the Axios client rejects its promise",
    "test"
  ],
  [
    "callanapi callanapi.request src/screenplay/abilities/callanapi.ts~callanapi,callanapi src/screenplay/abilities/callanapi.ts~callanapi#request,callanapi.request",
    "test-file/spec/screenplay/abilities/CallAnApi.spec.ts.html#lineNumber143",
    "CallAnApi when dealing with errors complains when the a network error occurs",
    "test"
  ],
  [
    "deleterequest src/model/deleterequest.ts~deleterequest,deleterequest",
    "test-file/spec/model/DeleteRequest.spec.ts.html#lineNumber7",
    "DeleteRequest",
    "test"
  ],
  [
    "deleterequest.to deleterequest#using src/model/deleterequest.ts~deleterequest.to,deleterequest.to src/model/deleterequest.ts~deleterequest#using,deleterequest#using",
    "test-file/spec/model/DeleteRequest.spec.ts.html#lineNumber23",
    "DeleteRequest allows for additional request properties to be specified",
    "test"
  ],
  [
    "deleterequest#tostring src/model/httprequest.ts~httprequest#tostring,deleterequest#tostring",
    "test-file/spec/model/DeleteRequest.spec.ts.html#lineNumber38",
    "DeleteRequest provides a sensible description of the interaction being performed",
    "test"
  ],
  [
    "deleterequest.to src/model/deleterequest.ts~deleterequest.to,deleterequest.to",
    "test-file/spec/model/DeleteRequest.spec.ts.html#lineNumber12",
    "DeleteRequest represents an Axios request",
    "test"
  ],
  [
    "getrequest src/model/getrequest.ts~getrequest,getrequest",
    "test-file/spec/model/GetRequest.spec.ts.html#lineNumber7",
    "GetRequest",
    "test"
  ],
  [
    "getrequest.to getrequest#using src/model/getrequest.ts~getrequest.to,getrequest.to src/model/getrequest.ts~getrequest#using,getrequest#using",
    "test-file/spec/model/GetRequest.spec.ts.html#lineNumber23",
    "GetRequest allows for additional request properties to be specified",
    "test"
  ],
  [
    "getrequest#tostring src/model/httprequest.ts~httprequest#tostring,getrequest#tostring",
    "test-file/spec/model/GetRequest.spec.ts.html#lineNumber38",
    "GetRequest provides a sensible description of the interaction being performed",
    "test"
  ],
  [
    "getrequest.to src/model/getrequest.ts~getrequest.to,getrequest.to",
    "test-file/spec/model/GetRequest.spec.ts.html#lineNumber12",
    "GetRequest represents an Axios request",
    "test"
  ],
  [
    "headrequest src/model/headrequest.ts~headrequest,headrequest",
    "test-file/spec/model/HeadRequest.spec.ts.html#lineNumber7",
    "HeadRequest",
    "test"
  ],
  [
    "headrequest.to headrequest#using src/model/headrequest.ts~headrequest.to,headrequest.to src/model/headrequest.ts~headrequest#using,headrequest#using",
    "test-file/spec/model/HeadRequest.spec.ts.html#lineNumber23",
    "HeadRequest allows for additional request properties to be specified",
    "test"
  ],
  [
    "headrequest#tostring src/model/httprequest.ts~httprequest#tostring,headrequest#tostring",
    "test-file/spec/model/HeadRequest.spec.ts.html#lineNumber38",
    "HeadRequest provides a sensible description of the interaction being performed",
    "test"
  ],
  [
    "headrequest.to src/model/headrequest.ts~headrequest.to,headrequest.to",
    "test-file/spec/model/HeadRequest.spec.ts.html#lineNumber12",
    "HeadRequest represents an Axios request",
    "test"
  ],
  [
    "lastresponse src/screenplay/questions/lastresponse.ts~lastresponse,lastresponse",
    "test-file/spec/screenplay/questions/LastResponse.spec.ts.html#lineNumber10",
    "LastResponse",
    "test"
  ],
  [
    "callanapi.maplastresponse src/screenplay/abilities/callanapi.ts~callanapi#maplastresponse,callanapi.maplastresponse",
    "test-file/spec/screenplay/questions/LastResponse.spec.ts.html#lineNumber65",
    "LastResponse complains if the last response is attempted to be retrieved without making a request first",
    "test"
  ],
  [
    "",
    "test-file/spec/screenplay/questions/LastResponse.spec.ts.html#lineNumber16",
    "LastResponse when asserting on the response to the last HTTP request",
    "test"
  ],
  [
    "lastresponse lastresponse.header src/screenplay/questions/lastresponse.ts~lastresponse,lastresponse src/screenplay/questions/lastresponse.ts~lastresponse.header,lastresponse.header",
    "test-file/spec/screenplay/questions/LastResponse.spec.ts.html#lineNumber47",
    "LastResponse when asserting on the response to the last HTTP request enables access to a specific response header",
    "test"
  ],
  [
    "lastresponse lastresponse.headers src/screenplay/questions/lastresponse.ts~lastresponse,lastresponse src/screenplay/questions/lastresponse.ts~lastresponse.headers,lastresponse.headers",
    "test-file/spec/screenplay/questions/LastResponse.spec.ts.html#lineNumber56",
    "LastResponse when asserting on the response to the last HTTP request enables access to all response headers",
    "test"
  ],
  [
    "lastresponse lastresponse.body src/screenplay/questions/lastresponse.ts~lastresponse,lastresponse src/screenplay/questions/lastresponse.ts~lastresponse.body,lastresponse.body",
    "test-file/spec/screenplay/questions/LastResponse.spec.ts.html#lineNumber38",
    "LastResponse when asserting on the response to the last HTTP request enables access to the response body",
    "test"
  ],
  [
    "lastresponse lastresponse.status src/screenplay/questions/lastresponse.ts~lastresponse,lastresponse src/screenplay/questions/lastresponse.ts~lastresponse.status,lastresponse.status",
    "test-file/spec/screenplay/questions/LastResponse.spec.ts.html#lineNumber29",
    "LastResponse when asserting on the response to the last HTTP request enables access to the response status",
    "test"
  ],
  [
    "optionsrequest src/model/optionsrequest.ts~optionsrequest,optionsrequest",
    "test-file/spec/model/OptionsRequest.spec.ts.html#lineNumber7",
    "OptionsRequest",
    "test"
  ],
  [
    "optionsrequest.to optionsrequest#using src/model/optionsrequest.ts~optionsrequest.to,optionsrequest.to src/model/optionsrequest.ts~optionsrequest#using,optionsrequest#using",
    "test-file/spec/model/OptionsRequest.spec.ts.html#lineNumber23",
    "OptionsRequest allows for additional request properties to be specified",
    "test"
  ],
  [
    "options#tostring options#tostring,options#tostring",
    "test-file/spec/model/OptionsRequest.spec.ts.html#lineNumber38",
    "OptionsRequest provides a sensible description of the interaction being performed",
    "test"
  ],
  [
    "optionsrequest.to src/model/optionsrequest.ts~optionsrequest.to,optionsrequest.to",
    "test-file/spec/model/OptionsRequest.spec.ts.html#lineNumber12",
    "OptionsRequest represents an Axios request",
    "test"
  ],
  [
    "patchrequest src/model/patchrequest.ts~patchrequest,patchrequest",
    "test-file/spec/model/PatchRequest.spec.ts.html#lineNumber7",
    "PatchRequest",
    "test"
  ],
  [
    "patchrequest.to patchrequest#with patchrequest#using src/model/patchrequest.ts~patchrequest.to,patchrequest.to src/model/patchrequest.ts~patchrequest#with,patchrequest#with src/model/patchrequest.ts~patchrequest#using,patchrequest#using",
    "test-file/spec/model/PatchRequest.spec.ts.html#lineNumber36",
    "PatchRequest allows for additional request properties to be specified",
    "test"
  ],
  [
    "patchrequest.to patchrequest#with src/model/patchrequest.ts~patchrequest.to,patchrequest.to src/model/patchrequest.ts~patchrequest#with,patchrequest#with",
    "test-file/spec/model/PatchRequest.spec.ts.html#lineNumber23",
    "PatchRequest can have a request body",
    "test"
  ],
  [
    "patchrequest#tostring src/model/httprequest.ts~httprequest#tostring,patchrequest#tostring",
    "test-file/spec/model/PatchRequest.spec.ts.html#lineNumber52",
    "PatchRequest provides a sensible description of the interaction being performed",
    "test"
  ],
  [
    "patchrequest.to src/model/patchrequest.ts~patchrequest.to,patchrequest.to",
    "test-file/spec/model/PatchRequest.spec.ts.html#lineNumber12",
    "PatchRequest represents an Axios request",
    "test"
  ],
  [
    "postrequest src/model/postrequest.ts~postrequest,postrequest",
    "test-file/spec/model/PostRequest.spec.ts.html#lineNumber7",
    "PostRequest",
    "test"
  ],
  [
    "",
    "test-file/spec/model/PostRequest.spec.ts.html#lineNumber27",
    "PostRequest allows for additional request properties to be specified",
    "test"
  ],
  [
    "",
    "test-file/spec/model/PostRequest.spec.ts.html#lineNumber19",
    "PostRequest can have a request body",
    "test"
  ],
  [
    "postrequest#tostring src/model/httprequest.ts~httprequest#tostring,postrequest#tostring",
    "test-file/spec/model/PostRequest.spec.ts.html#lineNumber43",
    "PostRequest provides a sensible description of the interaction being performed",
    "test"
  ],
  [
    "postrequest.to src/model/postrequest.ts~postrequest.to,postrequest.to",
    "test-file/spec/model/PostRequest.spec.ts.html#lineNumber12",
    "PostRequest represents an Axios request",
    "test"
  ],
  [
    "putrequest src/model/putrequest.ts~putrequest,putrequest",
    "test-file/spec/model/PutRequest.spec.ts.html#lineNumber7",
    "PutRequest",
    "test"
  ],
  [
    "putrequest.to putrequest#with putrequest#using src/model/putrequest.ts~putrequest.to,putrequest.to src/model/putrequest.ts~putrequest#with,putrequest#with src/model/putrequest.ts~putrequest#using,putrequest#using",
    "test-file/spec/model/PutRequest.spec.ts.html#lineNumber36",
    "PutRequest allows for additional request properties to be specified",
    "test"
  ],
  [
    "putrequest.to putrequest#with src/model/putrequest.ts~putrequest.to,putrequest.to src/model/putrequest.ts~putrequest#with,putrequest#with",
    "test-file/spec/model/PutRequest.spec.ts.html#lineNumber23",
    "PutRequest can have a request body",
    "test"
  ],
  [
    "putrequest#tostring src/model/httprequest.ts~httprequest#tostring,putrequest#tostring",
    "test-file/spec/model/PutRequest.spec.ts.html#lineNumber52",
    "PutRequest provides a sensible description of the interaction being performed",
    "test"
  ],
  [
    "putrequest.to src/model/putrequest.ts~putrequest.to,putrequest.to",
    "test-file/spec/model/PutRequest.spec.ts.html#lineNumber12",
    "PutRequest represents an Axios request",
    "test"
  ],
  [
    "send src/screenplay/interactions/send.ts~send,send",
    "test-file/spec/screenplay/interactions/Send.spec.ts.html#lineNumber18",
    "Send",
    "test"
  ],
  [
    "send.a httprequest getrequest.to src/screenplay/interactions/send.ts~send.a,send.a src/model/httprequest.ts~httprequest,httprequest src/model/getrequest.ts~getrequest.to,getrequest.to",
    "test-file/spec/screenplay/interactions/Send.spec.ts.html#lineNumber70",
    "Send emits the events so that the details of the HTTP interaction can be reported",
    "test"
  ],
  [
    "send.a httprequest getrequest.to lastresponse.status lastresponse.body src/screenplay/interactions/send.ts~send.a,send.a src/model/httprequest.ts~httprequest,httprequest src/model/getrequest.ts~getrequest.to,getrequest.to src/screenplay/questions/lastresponse.ts~lastresponse.status,lastresponse.status src/screenplay/questions/lastresponse.ts~lastresponse.body,lastresponse.body",
    "test-file/spec/screenplay/interactions/Send.spec.ts.html#lineNumber27",
    "Send enables the actor to send a HTTPRequest",
    "test"
  ],
  [
    "send.a httprequest getrequest.to lastresponse.status lastresponse.body src/screenplay/interactions/send.ts~send.a,send.a src/model/httprequest.ts~httprequest,httprequest src/model/getrequest.ts~getrequest.to,getrequest.to src/screenplay/questions/lastresponse.ts~lastresponse.status,lastresponse.status src/screenplay/questions/lastresponse.ts~lastresponse.body,lastresponse.body",
    "test-file/spec/screenplay/interactions/Send.spec.ts.html#lineNumber48",
    "Send enables the actor to send an Axios Request",
    "test"
  ],
  [
    "spec/model/deleterequest.spec.ts",
    "test-file/spec/model/DeleteRequest.spec.ts.html",
    "spec/model/DeleteRequest.spec.ts",
    "testFile"
  ],
  [
    "spec/model/getrequest.spec.ts",
    "test-file/spec/model/GetRequest.spec.ts.html",
    "spec/model/GetRequest.spec.ts",
    "testFile"
  ],
  [
    "spec/model/headrequest.spec.ts",
    "test-file/spec/model/HeadRequest.spec.ts.html",
    "spec/model/HeadRequest.spec.ts",
    "testFile"
  ],
  [
    "spec/model/optionsrequest.spec.ts",
    "test-file/spec/model/OptionsRequest.spec.ts.html",
    "spec/model/OptionsRequest.spec.ts",
    "testFile"
  ],
  [
    "spec/model/patchrequest.spec.ts",
    "test-file/spec/model/PatchRequest.spec.ts.html",
    "spec/model/PatchRequest.spec.ts",
    "testFile"
  ],
  [
    "spec/model/postrequest.spec.ts",
    "test-file/spec/model/PostRequest.spec.ts.html",
    "spec/model/PostRequest.spec.ts",
    "testFile"
  ],
  [
    "spec/model/putrequest.spec.ts",
    "test-file/spec/model/PutRequest.spec.ts.html",
    "spec/model/PutRequest.spec.ts",
    "testFile"
  ],
  [
    "spec/screenplay/abilities/callanapi.spec.ts",
    "test-file/spec/screenplay/abilities/CallAnApi.spec.ts.html",
    "spec/screenplay/abilities/CallAnApi.spec.ts",
    "testFile"
  ],
  [
    "spec/screenplay/interactions/send.spec.ts",
    "test-file/spec/screenplay/interactions/Send.spec.ts.html",
    "spec/screenplay/interactions/Send.spec.ts",
    "testFile"
  ],
  [
    "spec/screenplay/questions/lastresponse.spec.ts",
    "test-file/spec/screenplay/questions/LastResponse.spec.ts.html",
    "spec/screenplay/questions/LastResponse.spec.ts",
    "testFile"
  ],
  [
    "spec/setup.spec.ts",
    "test-file/spec/setup.spec.ts.html",
    "spec/setup.spec.ts",
    "testFile"
  ],
  [
    "src/index.ts",
    "file/src/index.ts.html",
    "src/index.ts",
    "file"
  ],
  [
    "src/model/deleterequest.ts",
    "file/src/model/DeleteRequest.ts.html",
    "src/model/DeleteRequest.ts",
    "file"
  ],
  [
    "src/model/deleterequest.ts~deleterequest#using",
    "class/src/model/DeleteRequest.ts~DeleteRequest.html#instance-method-using",
    "src/model/DeleteRequest.ts~DeleteRequest#using",
    "method"
  ],
  [
    "src/model/deleterequest.ts~deleterequest.to",
    "class/src/model/DeleteRequest.ts~DeleteRequest.html#static-method-to",
    "src/model/DeleteRequest.ts~DeleteRequest.to",
    "method"
  ],
  [
    "src/model/getrequest.ts",
    "file/src/model/GetRequest.ts.html",
    "src/model/GetRequest.ts",
    "file"
  ],
  [
    "src/model/getrequest.ts~getrequest#using",
    "class/src/model/GetRequest.ts~GetRequest.html#instance-method-using",
    "src/model/GetRequest.ts~GetRequest#using",
    "method"
  ],
  [
    "src/model/getrequest.ts~getrequest.to",
    "class/src/model/GetRequest.ts~GetRequest.html#static-method-to",
    "src/model/GetRequest.ts~GetRequest.to",
    "method"
  ],
  [
    "src/model/httprequest.ts",
    "file/src/model/HTTPRequest.ts.html",
    "src/model/HTTPRequest.ts",
    "file"
  ],
  [
    "src/model/httprequest.ts~httprequest#answeredby",
    "class/src/model/HTTPRequest.ts~HTTPRequest.html#instance-method-answeredBy",
    "src/model/HTTPRequest.ts~HTTPRequest#answeredBy",
    "method"
  ],
  [
    "src/model/httprequest.ts~httprequest#constructor",
    "class/src/model/HTTPRequest.ts~HTTPRequest.html#instance-constructor-constructor",
    "src/model/HTTPRequest.ts~HTTPRequest#constructor",
    "method"
  ],
  [
    "src/model/httprequest.ts~httprequest#tostring",
    "class/src/model/HTTPRequest.ts~HTTPRequest.html#instance-method-toString",
    "src/model/HTTPRequest.ts~HTTPRequest#toString",
    "method"
  ],
  [
    "src/model/headrequest.ts",
    "file/src/model/HeadRequest.ts.html",
    "src/model/HeadRequest.ts",
    "file"
  ],
  [
    "src/model/headrequest.ts~headrequest#using",
    "class/src/model/HeadRequest.ts~HeadRequest.html#instance-method-using",
    "src/model/HeadRequest.ts~HeadRequest#using",
    "method"
  ],
  [
    "src/model/headrequest.ts~headrequest.to",
    "class/src/model/HeadRequest.ts~HeadRequest.html#static-method-to",
    "src/model/HeadRequest.ts~HeadRequest.to",
    "method"
  ],
  [
    "src/model/optionsrequest.ts",
    "file/src/model/OptionsRequest.ts.html",
    "src/model/OptionsRequest.ts",
    "file"
  ],
  [
    "src/model/optionsrequest.ts~optionsrequest#using",
    "class/src/model/OptionsRequest.ts~OptionsRequest.html#instance-method-using",
    "src/model/OptionsRequest.ts~OptionsRequest#using",
    "method"
  ],
  [
    "src/model/optionsrequest.ts~optionsrequest.to",
    "class/src/model/OptionsRequest.ts~OptionsRequest.html#static-method-to",
    "src/model/OptionsRequest.ts~OptionsRequest.to",
    "method"
  ],
  [
    "src/model/patchrequest.ts",
    "file/src/model/PatchRequest.ts.html",
    "src/model/PatchRequest.ts",
    "file"
  ],
  [
    "src/model/patchrequest.ts~patchrequest#using",
    "class/src/model/PatchRequest.ts~PatchRequest.html#instance-method-using",
    "src/model/PatchRequest.ts~PatchRequest#using",
    "method"
  ],
  [
    "src/model/patchrequest.ts~patchrequest#with",
    "class/src/model/PatchRequest.ts~PatchRequest.html#instance-method-with",
    "src/model/PatchRequest.ts~PatchRequest#with",
    "method"
  ],
  [
    "src/model/patchrequest.ts~patchrequest.to",
    "class/src/model/PatchRequest.ts~PatchRequest.html#static-method-to",
    "src/model/PatchRequest.ts~PatchRequest.to",
    "method"
  ],
  [
    "src/model/postrequest.ts",
    "file/src/model/PostRequest.ts.html",
    "src/model/PostRequest.ts",
    "file"
  ],
  [
    "src/model/postrequest.ts~postrequest#using",
    "class/src/model/PostRequest.ts~PostRequest.html#instance-method-using",
    "src/model/PostRequest.ts~PostRequest#using",
    "method"
  ],
  [
    "src/model/postrequest.ts~postrequest#with",
    "class/src/model/PostRequest.ts~PostRequest.html#instance-method-with",
    "src/model/PostRequest.ts~PostRequest#with",
    "method"
  ],
  [
    "src/model/postrequest.ts~postrequest.to",
    "class/src/model/PostRequest.ts~PostRequest.html#static-method-to",
    "src/model/PostRequest.ts~PostRequest.to",
    "method"
  ],
  [
    "src/model/putrequest.ts",
    "file/src/model/PutRequest.ts.html",
    "src/model/PutRequest.ts",
    "file"
  ],
  [
    "src/model/putrequest.ts~putrequest#using",
    "class/src/model/PutRequest.ts~PutRequest.html#instance-method-using",
    "src/model/PutRequest.ts~PutRequest#using",
    "method"
  ],
  [
    "src/model/putrequest.ts~putrequest#with",
    "class/src/model/PutRequest.ts~PutRequest.html#instance-method-with",
    "src/model/PutRequest.ts~PutRequest#with",
    "method"
  ],
  [
    "src/model/putrequest.ts~putrequest.to",
    "class/src/model/PutRequest.ts~PutRequest.html#static-method-to",
    "src/model/PutRequest.ts~PutRequest.to",
    "method"
  ],
  [
    "src/model/index.ts",
    "file/src/model/index.ts.html",
    "src/model/index.ts",
    "file"
  ],
  [
    "src/screenplay/abilities/callanapi.ts",
    "file/src/screenplay/abilities/CallAnApi.ts.html",
    "src/screenplay/abilities/CallAnApi.ts",
    "file"
  ],
  [
    "src/screenplay/abilities/callanapi.ts~callanapi#constructor",
    "class/src/screenplay/abilities/CallAnApi.ts~CallAnApi.html#instance-constructor-constructor",
    "src/screenplay/abilities/CallAnApi.ts~CallAnApi#constructor",
    "method"
  ],
  [
    "src/screenplay/abilities/callanapi.ts~callanapi#maplastresponse",
    "class/src/screenplay/abilities/CallAnApi.ts~CallAnApi.html#instance-method-mapLastResponse",
    "src/screenplay/abilities/CallAnApi.ts~CallAnApi#mapLastResponse",
    "method"
  ],
  [
    "src/screenplay/abilities/callanapi.ts~callanapi#modifyconfig",
    "class/src/screenplay/abilities/CallAnApi.ts~CallAnApi.html#instance-method-modifyConfig",
    "src/screenplay/abilities/CallAnApi.ts~CallAnApi#modifyConfig",
    "method"
  ],
  [
    "src/screenplay/abilities/callanapi.ts~callanapi#request",
    "class/src/screenplay/abilities/CallAnApi.ts~CallAnApi.html#instance-method-request",
    "src/screenplay/abilities/CallAnApi.ts~CallAnApi#request",
    "method"
  ],
  [
    "src/screenplay/abilities/callanapi.ts~callanapi.as",
    "class/src/screenplay/abilities/CallAnApi.ts~CallAnApi.html#static-method-as",
    "src/screenplay/abilities/CallAnApi.ts~CallAnApi.as",
    "method"
  ],
  [
    "src/screenplay/abilities/callanapi.ts~callanapi.at",
    "class/src/screenplay/abilities/CallAnApi.ts~CallAnApi.html#static-method-at",
    "src/screenplay/abilities/CallAnApi.ts~CallAnApi.at",
    "method"
  ],
  [
    "src/screenplay/abilities/callanapi.ts~callanapi.using",
    "class/src/screenplay/abilities/CallAnApi.ts~CallAnApi.html#static-method-using",
    "src/screenplay/abilities/CallAnApi.ts~CallAnApi.using",
    "method"
  ],
  [
    "src/screenplay/abilities/index.ts",
    "file/src/screenplay/abilities/index.ts.html",
    "src/screenplay/abilities/index.ts",
    "file"
  ],
  [
    "src/screenplay/index.ts",
    "file/src/screenplay/index.ts.html",
    "src/screenplay/index.ts",
    "file"
  ],
  [
    "src/screenplay/interactions/changeapiurl.ts",
    "file/src/screenplay/interactions/ChangeApiUrl.ts.html",
    "src/screenplay/interactions/ChangeApiUrl.ts",
    "file"
  ],
  [
    "src/screenplay/interactions/changeapiurl.ts~changeapiurl#constructor",
    "class/src/screenplay/interactions/ChangeApiUrl.ts~ChangeApiUrl.html#instance-constructor-constructor",
    "src/screenplay/interactions/ChangeApiUrl.ts~ChangeApiUrl#constructor",
    "method"
  ],
  [
    "src/screenplay/interactions/changeapiurl.ts~changeapiurl#performas",
    "class/src/screenplay/interactions/ChangeApiUrl.ts~ChangeApiUrl.html#instance-method-performAs",
    "src/screenplay/interactions/ChangeApiUrl.ts~ChangeApiUrl#performAs",
    "method"
  ],
  [
    "src/screenplay/interactions/changeapiurl.ts~changeapiurl#tostring",
    "class/src/screenplay/interactions/ChangeApiUrl.ts~ChangeApiUrl.html#instance-method-toString",
    "src/screenplay/interactions/ChangeApiUrl.ts~ChangeApiUrl#toString",
    "method"
  ],
  [
    "src/screenplay/interactions/changeapiurl.ts~changeapiurl.to",
    "class/src/screenplay/interactions/ChangeApiUrl.ts~ChangeApiUrl.html#static-method-to",
    "src/screenplay/interactions/ChangeApiUrl.ts~ChangeApiUrl.to",
    "method"
  ],
  [
    "src/screenplay/interactions/send.ts",
    "file/src/screenplay/interactions/Send.ts.html",
    "src/screenplay/interactions/Send.ts",
    "file"
  ],
  [
    "src/screenplay/interactions/send.ts~send#constructor",
    "class/src/screenplay/interactions/Send.ts~Send.html#instance-constructor-constructor",
    "src/screenplay/interactions/Send.ts~Send#constructor",
    "method"
  ],
  [
    "src/screenplay/interactions/send.ts~send#performas",
    "class/src/screenplay/interactions/Send.ts~Send.html#instance-method-performAs",
    "src/screenplay/interactions/Send.ts~Send#performAs",
    "method"
  ],
  [
    "src/screenplay/interactions/send.ts~send#tostring",
    "class/src/screenplay/interactions/Send.ts~Send.html#instance-method-toString",
    "src/screenplay/interactions/Send.ts~Send#toString",
    "method"
  ],
  [
    "src/screenplay/interactions/send.ts~send.a",
    "class/src/screenplay/interactions/Send.ts~Send.html#static-method-a",
    "src/screenplay/interactions/Send.ts~Send.a",
    "method"
  ],
  [
    "src/screenplay/interactions/index.ts",
    "file/src/screenplay/interactions/index.ts.html",
    "src/screenplay/interactions/index.ts",
    "file"
  ],
  [
    "src/screenplay/questions/lastresponse.ts",
    "file/src/screenplay/questions/LastResponse.ts.html",
    "src/screenplay/questions/LastResponse.ts",
    "file"
  ],
  [
    "src/screenplay/questions/lastresponse.ts~lastresponse.body",
    "class/src/screenplay/questions/LastResponse.ts~LastResponse.html#static-method-body",
    "src/screenplay/questions/LastResponse.ts~LastResponse.body",
    "method"
  ],
  [
    "src/screenplay/questions/lastresponse.ts~lastresponse.header",
    "class/src/screenplay/questions/LastResponse.ts~LastResponse.html#static-method-header",
    "src/screenplay/questions/LastResponse.ts~LastResponse.header",
    "method"
  ],
  [
    "src/screenplay/questions/lastresponse.ts~lastresponse.headers",
    "class/src/screenplay/questions/LastResponse.ts~LastResponse.html#static-method-headers",
    "src/screenplay/questions/LastResponse.ts~LastResponse.headers",
    "method"
  ],
  [
    "src/screenplay/questions/lastresponse.ts~lastresponse.status",
    "class/src/screenplay/questions/LastResponse.ts~LastResponse.html#static-method-status",
    "src/screenplay/questions/LastResponse.ts~LastResponse.status",
    "method"
  ],
  [
    "src/screenplay/questions/index.ts",
    "file/src/screenplay/questions/index.ts.html",
    "src/screenplay/questions/index.ts",
    "file"
  ]
]