/** @external {@serenity-js/assertions~Check} /modules/assertions/class/src/Check.ts~Check.html */
/** @external {@serenity-js/assertions~Ensure} /modules/assertions/class/src/Ensure.ts~Ensure.html */
/** @external {@serenity-js/assertions~Expectation} /modules/assertions/class/src/Expectation.ts~Expectation.html */
/** @external {@serenity-js/assertions/lib/expectations~and} /modules/assertions/function/src/expectations/and.ts~and.html */
/** @external {@serenity-js/assertions/lib/expectations~contain} /modules/assertions/function/src/expectations/contain.ts~contain.html */
/** @external {@serenity-js/assertions/lib/expectations~containAtLeastOneItemThat} /modules/assertions/function/src/expectations/containAtLeastOneItemThat.ts~containAtLeastOneItemThat.html */
/** @external {@serenity-js/assertions/lib/expectations~containItemsWhereEachItem} /modules/assertions/function/src/expectations/containItemsWhereEachItem.ts~containItemsWhereEachItem.html */
/** @external {@serenity-js/assertions/lib/expectations~endsWith} /modules/assertions/function/src/expectations/endsWith.ts~endsWith.html */
/** @external {@serenity-js/assertions/lib/expectations~equals} /modules/assertions/function/src/expectations/equals.ts~equals.html */
/** @external {@serenity-js/assertions/lib/expectations~includes} /modules/assertions/function/src/expectations/includes.ts~includes.html */
/** @external {@serenity-js/assertions/lib/expectations~isAfter} /modules/assertions/function/src/expectations/isAfter.ts~isAfter.html */
/** @external {@serenity-js/assertions/lib/expectations~isBefore} /modules/assertions/function/src/expectations/isBefore.ts~isBefore.html */
/** @external {@serenity-js/assertions/lib/expectations~isGreaterThan} /modules/assertions/function/src/expectations/isGreaterThan.ts~isGreaterThan.html */
/** @external {@serenity-js/assertions/lib/expectations~isLessThan} /modules/assertions/function/src/expectations/isLessThan.ts~isLessThan.html */
/** @external {@serenity-js/assertions/lib/expectations~matches} /modules/assertions/function/src/expectations/matches.ts~matches.html */
/** @external {@serenity-js/assertions/lib/expectations~not} /modules/assertions/function/src/expectations/not.ts~not.html */
/** @external {@serenity-js/assertions/lib/expectations~or} /modules/assertions/function/src/expectations/or.ts~or.html */
/** @external {@serenity-js/assertions/lib/expectations~property} /modules/assertions/function/src/expectations/property.ts~property.html */
/** @external {@serenity-js/assertions/lib/expectations~startsWith} /modules/assertions/function/src/expectations/startsWith.ts~startsWith.html */
/** @external {@serenity-js/assertions~Outcome} /modules/assertions/class/src/outcomes.ts~Outcome.html */
/** @external {@serenity-js/assertions~ExpectationMet} /modules/assertions/class/src/outcomes.ts~ExpectationMet.html */
/** @external {@serenity-js/assertions~ExpectationNotMet} /modules/assertions/class/src/outcomes.ts~ExpectationNotMet.html */