/** @external {@serenity-js/assertions~Check} /modules/assertions/class/src/Check.ts~Check.html */
/** @external {@serenity-js/assertions~Ensure} /modules/assertions/class/src/Ensure.ts~Ensure.html */
/** @external {@serenity-js/assertions~Expectation} /modules/assertions/class/src/Expectation.ts~Expectation.html */
/** @external {@serenity-js/assertions/lib/expectations~and} /modules/assertions/function/index.html#static-function-and */
/** @external {@serenity-js/assertions/lib/expectations~contain} /modules/assertions/function/index.html#static-function-contain */
/** @external {@serenity-js/assertions/lib/expectations~containAtLeastOneItemThat} /modules/assertions/function/index.html#static-function-containAtLeastOneItemThat */
/** @external {@serenity-js/assertions/lib/expectations~containItemsWhereEachItem} /modules/assertions/function/index.html#static-function-containItemsWhereEachItem */
/** @external {@serenity-js/assertions/lib/expectations~endsWith} /modules/assertions/function/index.html#static-function-endsWith */
/** @external {@serenity-js/assertions/lib/expectations~equals} /modules/assertions/function/index.html#static-function-equals */
/** @external {@serenity-js/assertions/lib/expectations~includes} /modules/assertions/function/index.html#static-function-includes */
/** @external {@serenity-js/assertions/lib/expectations~isAfter} /modules/assertions/function/index.html#static-function-isAfter */
/** @external {@serenity-js/assertions/lib/expectations~isBefore} /modules/assertions/function/index.html#static-function-isBefore */
/** @external {@serenity-js/assertions/lib/expectations~isFalse} /modules/assertions/function/index.html#static-function-isFalse */
/** @external {@serenity-js/assertions/lib/expectations~isGreaterThan} /modules/assertions/function/index.html#static-function-isGreaterThan */
/** @external {@serenity-js/assertions/lib/expectations~isLessThan} /modules/assertions/function/index.html#static-function-isLessThan */
/** @external {@serenity-js/assertions/lib/expectations~isTrue} /modules/assertions/function/index.html#static-function-isTrue */
/** @external {@serenity-js/assertions/lib/expectations~matches} /modules/assertions/function/index.html#static-function-matches */
/** @external {@serenity-js/assertions/lib/expectations~not} /modules/assertions/function/index.html#static-function-not */
/** @external {@serenity-js/assertions/lib/expectations~or} /modules/assertions/function/index.html#static-function-or */
/** @external {@serenity-js/assertions/lib/expectations~property} /modules/assertions/function/index.html#static-function-property */
/** @external {@serenity-js/assertions/lib/expectations~startsWith} /modules/assertions/function/index.html#static-function-startsWith */
/** @external {@serenity-js/assertions~Outcome} /modules/assertions/class/src/outcomes.ts~Outcome.html */
/** @external {@serenity-js/assertions~ExpectationMet} /modules/assertions/class/src/outcomes.ts~ExpectationMet.html */
/** @external {@serenity-js/assertions~ExpectationNotMet} /modules/assertions/class/src/outcomes.ts~ExpectationNotMet.html */