// Serenity/JS HTML Reporter - Mock Data
// This file is loaded via <script src="./data.js"></script> in the report template.
// In production, it is generated by the @serenity-js/html-reporter StageCrewMember.
//
// Mock data represents: examples/cucumber-reporting project
// Features: frequent_flyers, reporting_results, reporting_special_step_arguments
// Test runner: Cucumber.js 12.x
// Total scenarios: 53 (3 frequent flyers + 8 individual + 42 outline)

window.__SERENITY_REPORT_DATA__ = {
  summary: {
    title: "Serenity/JS Cucumber Reporting",
    totalScenarios: 53,
    outcomes: { passed: 46, failed: 4, pending: 1, skipped: 0, compromised: 1, error: 1 },
    duration: 4200,
    startedAt: "2024-06-15T14:30:00.000Z",
    finishedAt: "2024-06-15T14:30:04.200Z",
    testRunner: "Cucumber.js",
  },

  scenarios: [
    // ─────────────────────────────────────────────────────────────────────────────
    // Feature: Transferring points between members (frequent_flyers)
    // ─────────────────────────────────────────────────────────────────────────────

    {
      id: "scenario-1",
      name: "Transfer points between existing members",
      category: "Frequent Flyers › Transferring Points Between Members",
      outcome: "SUCCESS",
      duration: 85,
      startedAt: "2024-06-15T14:30:00.000Z",
      source: { path: "frequent_flyers/transferring_points_between_members.feature", line: 22 },
      narrative: "As a Frequent Flyer Member\nI want to transfer points that I don't need to members of my family\nSo that the points don't go to waste",
      tags: [
        { type: "feature", name: "Transferring Points Between Members" },
      ],
      retries: 0,
      cast: [
        { name: "Sarah", abilities: [
          { name: "PerformActivities" },
          { name: "AnswerQuestions" },
          { name: "TakeNotes", details: "{ notepad: {} }" },
          { name: "ManageFrequentFlyerAccounts", details: "{ provider: FlyHighAirlines }" }
        ] },
        { name: "Steve", abilities: [
          { name: "PerformActivities" },
          { name: "AnswerQuestions" },
          { name: "TakeNotes", details: "{ notepad: {} }" },
          { name: "ManageFrequentFlyerAccounts", details: "{ provider: FlyHighAirlines }" }
        ] },
      ],
      executionHistory: [
        { run: "#85", outcome: "SUCCESS" },
        { run: "#86", outcome: "SUCCESS" },
        { run: "#87", outcome: "SUCCESS" },
        { run: "#88", outcome: "SUCCESS" },
        { run: "#89", outcome: "SUCCESS" },
      ],
      activities: [
        {
          type: "Interaction", name: "Given the following Frequent Flyer members:", outcome: "SUCCESS", duration: 12,
          children: [],
          dataTable: {
            headers: ["Name", "Surname", "Family Code"],
            rows: [
              ["Sarah", "Sparrow", "FAM-101"],
              ["Steve", "Sparrow", "FAM-101"],
              ["Fred", "Falcon", "FAM-202"],
            ],
          },
        },
        {
          type: "Interaction", name: "Given the following Frequent Flyer account balances:", outcome: "SUCCESS", duration: 8,
          children: [],
          dataTable: {
            headers: ["owner", "points", "status-points"],
            rows: [
              ["Sarah", "100000", "800"],
              ["Steve", "50000", "50"],
            ],
          },
        },
        {
          type: "Interaction", name: "When Sarah transfers 40000 points to Steve", outcome: "SUCCESS", duration: 35,
          children: [],
        },
        {
          type: "Interaction", name: "Then the accounts should be as follows:", outcome: "SUCCESS", duration: 30,
          children: [],
          dataTable: {
            headers: ["owner", "points", "status-points"],
            rows: [
              ["Sarah", "140000", "800"],
              ["Steve", "10000", "50"],
            ],
          },
        },
      ],
    },

    {
      id: "scenario-2",
      name: "Transfer points between non-family members",
      category: "Frequent Flyers › Transferring Points Between Members",
      outcome: "SUCCESS",
      duration: 72,
      startedAt: "2024-06-15T14:30:00.085Z",
      source: { path: "frequent_flyers/transferring_points_between_members.feature", line: 36 },
      narrative: "As a Frequent Flyer Member\nI want to transfer points that I don't need to members of my family\nSo that the points don't go to waste",
      tags: [
        { type: "feature", name: "Transferring Points Between Members" },
      ],
      retries: 0,
      cast: [
        { name: "Sarah", abilities: [
          { name: "PerformActivities" },
          { name: "AnswerQuestions" },
          { name: "TakeNotes", details: "{ notepad: {} }" },
          { name: "ManageFrequentFlyerAccounts", details: "{ provider: FlyHighAirlines }" }
        ] },
        { name: "Fred", abilities: [
          { name: "PerformActivities" },
          { name: "AnswerQuestions" },
          { name: "TakeNotes", details: "{ notepad: {} }" },
          { name: "ManageFrequentFlyerAccounts", details: "{ provider: FlyHighAirlines }" }
        ] },
      ],
      activities: [
        {
          type: "Interaction", name: "Given the following Frequent Flyer members:", outcome: "SUCCESS", duration: 10,
          children: [],
          dataTable: {
            headers: ["Name", "Surname", "Family Code"],
            rows: [
              ["Sarah", "Sparrow", "FAM-101"],
              ["Steve", "Sparrow", "FAM-101"],
              ["Fred", "Falcon", "FAM-202"],
            ],
          },
        },
        {
          type: "Interaction", name: "Given the following Frequent Flyer account balances:", outcome: "SUCCESS", duration: 7,
          children: [],
          dataTable: {
            headers: ["owner", "points", "status-points"],
            rows: [
              ["Sarah", "100000", "800"],
              ["Fred", "20000", "50"],
            ],
          },
        },
        {
          type: "Interaction", name: "When Sarah tries to transfer 10000 points to Fred", outcome: "SUCCESS", duration: 30,
          children: [],
        },
        {
          type: "Interaction", name: "Then the transfer should not be allowed", outcome: "SUCCESS", duration: 25,
          children: [],
        },
      ],
    },

    {
      id: "scenario-3",
      name: "Steve tries to transfer more points than he has",
      category: "Frequent Flyers › Transferring Points Between Members",
      outcome: "SUCCESS",
      duration: 68,
      startedAt: "2024-06-15T14:30:00.157Z",
      source: { path: "frequent_flyers/transferring_points_between_members.feature", line: 49 },
      narrative: "As a Frequent Flyer Member\nI want to transfer points that I don't need to members of my family\nSo that the points don't go to waste",
      tags: [
        { type: "feature", name: "Transferring Points Between Members" },
      ],
      retries: 0,
      cast: [
        { name: "Steve", abilities: [
          { name: "PerformActivities" },
          { name: "AnswerQuestions" },
          { name: "TakeNotes", details: "{ notepad: {} }" },
          { name: "ManageFrequentFlyerAccounts", details: "{ provider: FlyHighAirlines }" }
        ] },
        { name: "Sarah", abilities: [
          { name: "PerformActivities" },
          { name: "AnswerQuestions" },
          { name: "TakeNotes", details: "{ notepad: {} }" },
          { name: "ManageFrequentFlyerAccounts", details: "{ provider: FlyHighAirlines }" }
        ] },
      ],
      activities: [
        {
          type: "Interaction", name: "Given the following Frequent Flyer members:", outcome: "SUCCESS", duration: 9,
          children: [],
          dataTable: {
            headers: ["Name", "Surname", "Family Code"],
            rows: [
              ["Sarah", "Sparrow", "FAM-101"],
              ["Steve", "Sparrow", "FAM-101"],
              ["Fred", "Falcon", "FAM-202"],
            ],
          },
        },
        {
          type: "Interaction", name: "Given the following Frequent Flyer account balances:", outcome: "SUCCESS", duration: 7,
          children: [],
          dataTable: {
            headers: ["owner", "points", "status-points"],
            rows: [
              ["Sarah", "100000", "800"],
              ["Steve", "50000", "50"],
            ],
          },
        },
        {
          type: "Interaction", name: "When Steve tries to transfer 100000 points to Sarah", outcome: "SUCCESS", duration: 28,
          children: [],
        },
        {
          type: "Interaction", name: "Then the transfer should not be allowed", outcome: "SUCCESS", duration: 24,
          children: [],
        },
      ],
    },

    // ─────────────────────────────────────────────────────────────────────────────
    // Feature: Reports passing scenarios (reporting_results)
    // ─────────────────────────────────────────────────────────────────────────────

    {
      id: "scenario-4",
      name: "A passing scenario",
      category: "Reporting Results › Reports Passing Scenarios",
      outcome: "SUCCESS",
      duration: 45,
      startedAt: "2024-06-15T14:30:00.225Z",
      source: { path: "reporting_results/reports_passing_scenarios.feature", line: 8 },
      narrative: "In order to see how Serenity/JS reports a passing Cucumber scenario\nAs a curious developer\nI'd like to see an example implementation",
      tags: [
        { type: "feature", name: "Reports Passing Scenarios" },
        { type: "issue", name: "GH-5678" },
      ],
      retries: 0,
      cast: [],
      activities: [
        {
          type: "Interaction", name: "Given a step that passes", outcome: "SUCCESS", duration: 15,
          children: [],
        },
        {
          type: "Interaction", name: "When another step passes", outcome: "SUCCESS", duration: 14,
          children: [],
        },
        {
          type: "Interaction", name: "Then the third step passes", outcome: "SUCCESS", duration: 16,
          children: [],
        },
      ],
    },

    // ─────────────────────────────────────────────────────────────────────────────
    // Feature: Reports failing scenarios (reporting_results)
    // ─────────────────────────────────────────────────────────────────────────────

    {
      id: "scenario-5",
      name: "A scenario failing with a Serenity/JS AssertionError",
      category: "Reporting Results › Reports Failing Scenarios",
      outcome: "FAILURE",
      duration: 62,
      startedAt: "2024-06-15T14:30:00.270Z",
      source: { path: "reporting_results/reports_failing_scenarios.feature", line: 8 },
      narrative: "In order to see how Serenity/JS reports a failing Cucumber scenario\nAs a curious developer\nI'd like to see an example implementation",
      tags: [
        { type: "feature", name: "Reports Failing Scenarios" },
        { type: "issue", name: "GH-1234" },
      ],
      retries: 0,
      cast: [],
      executionHistory: [
        { run: "#85", outcome: "FAILURE" },
        { run: "#86", outcome: "FAILURE" },
        { run: "#87", outcome: "FAILURE" },
        { run: "#88", outcome: "FAILURE" },
        { run: "#89", outcome: "FAILURE" },
      ],
      activities: [
        {
          type: "Interaction", name: "Given a step that passes", outcome: "SUCCESS", duration: 12,
          children: [],
        },
        {
          type: "Interaction", name: "And a step that fails with a Serenity/JS AssertionError", outcome: "FAILURE", duration: 50,
          children: [],
          error: {
            name: "AssertionError",
            message: "expected true to equal false",
            stack: "AssertionError: expected true to equal false\n    at World.<anonymous> (features/step_definitions/sample.steps.ts:12:11)\n    at Runtime.execute (node_modules/@cucumber/cucumber/src/runtime/index.ts:45:22)",
          },
        },
      ],
      error: {
        name: "AssertionError",
        message: "expected true to equal false",
        stack: "AssertionError: expected true to equal false\n    at World.<anonymous> (features/step_definitions/sample.steps.ts:12:11)\n    at Runtime.execute (node_modules/@cucumber/cucumber/src/runtime/index.ts:45:22)",
      },
    },

    {
      id: "scenario-6",
      name: "A scenario failing with a Serenity/JS AssertionError in an async step",
      category: "Reporting Results › Reports Failing Scenarios",
      outcome: "FAILURE",
      duration: 58,
      startedAt: "2024-06-15T14:30:00.332Z",
      source: { path: "reporting_results/reports_failing_scenarios.feature", line: 17 },
      narrative: "In order to see how Serenity/JS reports a failing Cucumber scenario\nAs a curious developer\nI'd like to see an example implementation",
      tags: [
        { type: "feature", name: "Reports Failing Scenarios" },
        { type: "issue", name: "GH-1234" },
      ],
      retries: 0,
      cast: [],
      activities: [
        {
          type: "Interaction", name: "Given a step that passes", outcome: "SUCCESS", duration: 10,
          children: [],
        },
        {
          type: "Interaction", name: "And an async step that fails with a Serenity/JS AssertionError", outcome: "FAILURE", duration: 48,
          children: [],
          error: {
            name: "AssertionError",
            message: "expected true to equal false",
            stack: "AssertionError: expected true to equal false\n    at World.<anonymous> (features/step_definitions/sample.steps.ts:16:11)\n    at Runtime.execute (node_modules/@cucumber/cucumber/src/runtime/index.ts:45:22)",
          },
        },
      ],
      error: {
        name: "AssertionError",
        message: "expected true to equal false",
        stack: "AssertionError: expected true to equal false\n    at World.<anonymous> (features/step_definitions/sample.steps.ts:16:11)\n    at Runtime.execute (node_modules/@cucumber/cucumber/src/runtime/index.ts:45:22)",
      },
    },

    {
      id: "scenario-7",
      name: "A scenario failing with a Serenity/JS Screenplay AssertionError",
      category: "Reporting Results › Reports Failing Scenarios",
      outcome: "FAILURE",
      duration: 95,
      startedAt: "2024-06-15T14:30:00.390Z",
      source: { path: "reporting_results/reports_failing_scenarios.feature", line: 24 },
      narrative: "In order to see how Serenity/JS reports a failing Cucumber scenario\nAs a curious developer\nI'd like to see an example implementation",
      tags: [
        { type: "feature", name: "Reports Failing Scenarios" },
      ],
      retries: 0,
      cast: [{ name: "Alice", abilities: [
          { name: "PerformActivities" },
          { name: "AnswerQuestions" },
          { name: "RaiseErrors" },
          { name: "ScheduleWork", details: "{ scheduler: { clock: { timeAdjustment: { milliseconds: 0 } }, interactionTimeout: { milliseconds: 5000 } } }" },
          { name: "BrowseTheWeb", details: "(BrowseTheWebWithPlaywright)" },
          { name: "CallAnApi", details: "{ baseURL: \"https://the-internet.herokuapp.com/\", headers: { common: { Accept: \"application/json, text/plain, */*\" } }, timeout: 10000 }" },
          { name: "TakeNotes", details: "{ notepad: {} }" }
        ] }],
      activities: [
        {
          type: "Interaction", name: "Given a step that passes", outcome: "SUCCESS", duration: 11,
          children: [],
        },
        {
          type: "Task", name: "And a step that fails with a Serenity/JS Screenplay AssertionError", outcome: "FAILURE", duration: 84,
          children: [
            {
              type: "Interaction", name: "Alice ensures that true does equal false", outcome: "FAILURE", duration: 78,
              children: [],
              error: {
                name: "AssertionError",
                message: "Expected true to equal false",
                stack: "AssertionError: Expected true to equal false\n    at Ensure.that (packages/assertions/src/Ensure.ts:45:19)\n    at Actor.answer (packages/core/src/screenplay/Actor.ts:132:20)\n    at features/step_definitions/sample.steps.ts:22:5",
              },
            },
          ],
          error: {
            name: "AssertionError",
            message: "Expected true to equal false",
            stack: "AssertionError: Expected true to equal false\n    at Ensure.that (packages/assertions/src/Ensure.ts:45:19)\n    at Actor.answer (packages/core/src/screenplay/Actor.ts:132:20)\n    at features/step_definitions/sample.steps.ts:22:5",
          },
        },
      ],
      error: {
        name: "AssertionError",
        message: "Expected true to equal false",
        stack: "AssertionError: Expected true to equal false\n    at Ensure.that (packages/assertions/src/Ensure.ts:45:19)\n    at Actor.answer (packages/core/src/screenplay/Actor.ts:132:20)\n    at features/step_definitions/sample.steps.ts:22:5",
      },
    },

    {
      id: "scenario-8",
      name: "A scenario failing with a Node.js AssertionError",
      category: "Reporting Results › Reports Failing Scenarios",
      outcome: "FAILURE",
      duration: 55,
      startedAt: "2024-06-15T14:30:00.485Z",
      source: { path: "reporting_results/reports_failing_scenarios.feature", line: 31 },
      narrative: "In order to see how Serenity/JS reports a failing Cucumber scenario\nAs a curious developer\nI'd like to see an example implementation",
      tags: [
        { type: "feature", name: "Reports Failing Scenarios" },
      ],
      retries: 0,
      cast: [],
      activities: [
        {
          type: "Interaction", name: "Given a step that passes", outcome: "SUCCESS", duration: 10,
          children: [],
        },
        {
          type: "Interaction", name: "And a step that fails with a Node.js AssertionError", outcome: "FAILURE", duration: 45,
          children: [],
          error: {
            name: "AssertionError [ERR_ASSERTION]",
            message: "Expected values to be strictly equal:\n\ntrue !== false",
            stack: "AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:\n\ntrue !== false\n    at World.<anonymous> (features/step_definitions/sample.steps.ts:28:5)\n    at Runtime.execute (node_modules/@cucumber/cucumber/src/runtime/index.ts:45:22)",
          },
        },
      ],
      error: {
        name: "AssertionError [ERR_ASSERTION]",
        message: "Expected values to be strictly equal:\n\ntrue !== false",
        stack: "AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:\n\ntrue !== false\n    at World.<anonymous> (features/step_definitions/sample.steps.ts:28:5)\n    at Runtime.execute (node_modules/@cucumber/cucumber/src/runtime/index.ts:45:22)",
      },
    },

    // ─────────────────────────────────────────────────────────────────────────────
    // Feature: Reports pending scenarios (reporting_results)
    // ─────────────────────────────────────────────────────────────────────────────

    {
      id: "scenario-9",
      name: "A pending scenario",
      category: "Reporting Results › Reports Pending Scenarios",
      outcome: "PENDING",
      duration: 28,
      startedAt: "2024-06-15T14:30:00.540Z",
      source: { path: "reporting_results/reports_pending_scenarios.feature", line: 8 },
      narrative: "In order to see how Serenity/JS reports a pending Cucumber scenario\nAs a curious developer\nI'd like to see an example implementation",
      tags: [
        { type: "feature", name: "Reports Pending Scenarios" },
      ],
      retries: 0,
      cast: [],
      activities: [
        {
          type: "Interaction", name: "Given a step that passes", outcome: "SUCCESS", duration: 10,
          children: [],
        },
        {
          type: "Interaction", name: "And a step that's marked as pending", outcome: "PENDING", duration: 8,
          children: [],
        },
        {
          type: "Interaction", name: "And a step that passes", outcome: "SKIPPED", duration: 0,
          children: [],
        },
      ],
    },

    // ─────────────────────────────────────────────────────────────────────────────
    // Feature: Reports compromised scenarios (reporting_results)
    // ─────────────────────────────────────────────────────────────────────────────

    {
      id: "scenario-10",
      name: "A compromised scenario",
      category: "Reporting Results › Reports Compromised Scenarios",
      outcome: "COMPROMISED",
      duration: 42,
      startedAt: "2024-06-15T14:30:00.568Z",
      source: { path: "reporting_results/reports_compromised_scenarios.feature", line: 8 },
      narrative: "In order to see how Serenity/JS reports a compromised Cucumber scenario\nAs a curious developer\nI'd like to see an example implementation",
      tags: [
        { type: "feature", name: "Reports Compromised Scenarios" },
      ],
      retries: 0,
      cast: [],
      activities: [
        {
          type: "Interaction", name: "Given a step that fails with an error compromising the test", outcome: "COMPROMISED", duration: 42,
          children: [],
          error: {
            name: "TestCompromisedError",
            message: "Something's wrong",
            stack: "TestCompromisedError: Something's wrong\n    at World.<anonymous> (features/step_definitions/sample.steps.ts:36:26)\n    at Runtime.execute (node_modules/@cucumber/cucumber/src/runtime/index.ts:45:22)",
          },
        },
      ],
      error: {
        name: "TestCompromisedError",
        message: "Something's wrong",
        stack: "TestCompromisedError: Something's wrong\n    at World.<anonymous> (features/step_definitions/sample.steps.ts:36:26)\n    at Runtime.execute (node_modules/@cucumber/cucumber/src/runtime/index.ts:45:22)",
      },
    },

    // ─────────────────────────────────────────────────────────────────────────────
    // Feature: Reports errors in scenarios (reporting_results)
    // ─────────────────────────────────────────────────────────────────────────────

    {
      id: "scenario-11",
      name: "A broken scenario",
      category: "Reporting Results › Reports Errors In Scenarios",
      outcome: "ERROR",
      duration: 38,
      startedAt: "2024-06-15T14:30:00.610Z",
      source: { path: "reporting_results/reports_errors_in_scenarios.feature", line: 8 },
      narrative: "In order to see how Serenity/JS reports a failing Cucumber scenario\nAs a curious developer\nI'd like to see an example implementation",
      tags: [
        { type: "feature", name: "Reports Errors In Scenarios" },
      ],
      retries: 0,
      cast: [],
      activities: [
        {
          type: "Interaction", name: "Given a step that fails with a generic error", outcome: "ERROR", duration: 38,
          children: [],
          error: {
            name: "Error",
            message: "Something's wrong",
            stack: "Error: Something's wrong\n    at World.<anonymous> (features/step_definitions/sample.steps.ts:32:26)\n    at Runtime.execute (node_modules/@cucumber/cucumber/src/runtime/index.ts:45:22)",
          },
        },
      ],
      error: {
        name: "Error",
        message: "Something's wrong",
        stack: "Error: Something's wrong\n    at World.<anonymous> (features/step_definitions/sample.steps.ts:32:26)\n    at Runtime.execute (node_modules/@cucumber/cucumber/src/runtime/index.ts:45:22)",
      },
    },

    // ─────────────────────────────────────────────────────────────────────────────
    // Feature: Reports timed out scenarios (reporting_results)
    // Includes one retry attempt
    // ─────────────────────────────────────────────────────────────────────────────

    {
      id: "scenario-12",
      name: "A timed out scenario",
      category: "Reporting Results › Reports Timed Out Scenarios",
      outcome: "FAILURE",
      duration: 310,
      startedAt: "2024-06-15T14:30:00.648Z",
      source: { path: "reporting_results/reports_timed_out_scenarios.feature", line: 8 },
      narrative: "In order to see how Serenity/JS reports a timed out Cucumber scenario\nAs a curious developer\nI'd like to see an example implementation",
      tags: [
        { type: "feature", name: "Reports Timed Out Scenarios" },
      ],
      retries: 1,
      cast: [],
      executionHistory: [
        { run: "#85", outcome: "FAILURE" },
        { run: "#86", outcome: "SUCCESS" },
        { run: "#87", outcome: "FAILURE" },
        { run: "#88", outcome: "SUCCESS" },
        { run: "#89", outcome: "FAILURE" },
      ],
      attempts: [
        {
          attemptNumber: 1,
          outcome: "FAILURE",
          duration: 155,
          activities: [
            {
              type: "Interaction", name: "Given a step that passes", outcome: "SUCCESS", duration: 10,
              children: [],
            },
            {
              type: "Interaction", name: "And a step that times out", outcome: "FAILURE", duration: 105,
              children: [],
              error: {
                name: "Error",
                message: "function timed out, ensure the promise resolves within 100 milliseconds",
                stack: "Error: function timed out, ensure the promise resolves within 100 milliseconds\n    at Timeout._onTimeout (node_modules/@cucumber/cucumber/src/runtime/helpers.ts:28:11)",
              },
            },
            {
              type: "Interaction", name: "And a step that passes", outcome: "SKIPPED", duration: 0,
              children: [],
            },
          ],
          error: {
            name: "Error",
            message: "function timed out, ensure the promise resolves within 100 milliseconds",
            stack: "Error: function timed out, ensure the promise resolves within 100 milliseconds\n    at Timeout._onTimeout (node_modules/@cucumber/cucumber/src/runtime/helpers.ts:28:11)",
          },
        },
        {
          attemptNumber: 2,
          outcome: "FAILURE",
          duration: 155,
          activities: [
            {
              type: "Interaction", name: "Given a step that passes", outcome: "SUCCESS", duration: 10,
              children: [],
            },
            {
              type: "Interaction", name: "And a step that times out", outcome: "FAILURE", duration: 105,
              children: [],
              error: {
                name: "Error",
                message: "function timed out, ensure the promise resolves within 100 milliseconds",
                stack: "Error: function timed out, ensure the promise resolves within 100 milliseconds\n    at Timeout._onTimeout (node_modules/@cucumber/cucumber/src/runtime/helpers.ts:28:11)",
              },
            },
            {
              type: "Interaction", name: "And a step that passes", outcome: "SKIPPED", duration: 0,
              children: [],
            },
          ],
          error: {
            name: "Error",
            message: "function timed out, ensure the promise resolves within 100 milliseconds",
            stack: "Error: function timed out, ensure the promise resolves within 100 milliseconds\n    at Timeout._onTimeout (node_modules/@cucumber/cucumber/src/runtime/helpers.ts:28:11)",
          },
        },
      ],
      activities: [
        {
          type: "Interaction", name: "Given a step that passes", outcome: "SUCCESS", duration: 10,
          children: [],
        },
        {
          type: "Interaction", name: "And a step that times out", outcome: "FAILURE", duration: 105,
          children: [],
          error: {
            name: "Error",
            message: "function timed out, ensure the promise resolves within 100 milliseconds",
            stack: "Error: function timed out, ensure the promise resolves within 100 milliseconds\n    at Timeout._onTimeout (node_modules/@cucumber/cucumber/src/runtime/helpers.ts:28:11)",
          },
        },
        {
          type: "Interaction", name: "And a step that passes", outcome: "SKIPPED", duration: 0,
          children: [],
        },
      ],
      error: {
        name: "Error",
        message: "function timed out, ensure the promise resolves within 100 milliseconds",
        stack: "Error: function timed out, ensure the promise resolves within 100 milliseconds\n    at Timeout._onTimeout (node_modules/@cucumber/cucumber/src/runtime/helpers.ts:28:11)",
      },
    },

    // ─────────────────────────────────────────────────────────────────────────────
    // Feature: Reports scenario outlines (reporting_results)
    // 42 total examples: 12 from @set-1, 30 from @set-2
    // Showing 5 from @set-1 and 3 from @set-2 as representative sample
    // ─────────────────────────────────────────────────────────────────────────────

    {
      id: "scenario-13",
      name: "People who make Serenity happen — jan-molak",
      category: "Reporting Results › Reports Scenario Outlines",
      outcome: "SUCCESS",
      duration: 48,
      startedAt: "2024-06-15T14:30:00.958Z",
      source: { path: "reporting_results/reports_scenario_outlines.feature", line: 8 },
      narrative: "In order to see how Serenity/JS reports Cucumber scenario outlines\nAs a curious developer\nI'd like to see an example implementation",
      tags: [
        { type: "feature", name: "Reports Scenario Outlines" },
        { type: "tag", name: "@set-1" },
      ],
      retries: 0,
      cast: [],
      activities: [
        {
          type: "Interaction", name: "When jan-molak makes a contribution of:", outcome: "SUCCESS", duration: 28,
          children: [],
          dataTable: {
            headers: ["value"],
            rows: [["time"], ["talent"], ["great code"]],
          },
        },
        {
          type: "Interaction", name: "Then they help bring serenity to fellow devs", outcome: "SUCCESS", duration: 20,
          children: [],
        },
      ],
    },

    {
      id: "scenario-14",
      name: "People who make Serenity happen — InvictusMB",
      category: "Reporting Results › Reports Scenario Outlines",
      outcome: "SUCCESS",
      duration: 42,
      startedAt: "2024-06-15T14:30:01.006Z",
      source: { path: "reporting_results/reports_scenario_outlines.feature", line: 8 },
      narrative: "In order to see how Serenity/JS reports Cucumber scenario outlines\nAs a curious developer\nI'd like to see an example implementation",
      tags: [
        { type: "feature", name: "Reports Scenario Outlines" },
        { type: "tag", name: "@set-1" },
      ],
      retries: 0,
      cast: [],
      activities: [
        {
          type: "Interaction", name: "When InvictusMB makes a contribution of:", outcome: "SUCCESS", duration: 24,
          children: [],
          dataTable: {
            headers: ["value"],
            rows: [["time"], ["talent"], ["great code"]],
          },
        },
        {
          type: "Interaction", name: "Then they help bring serenity to fellow devs", outcome: "SUCCESS", duration: 18,
          children: [],
        },
      ],
    },

    {
      id: "scenario-15",
      name: "People who make Serenity happen — asnov",
      category: "Reporting Results › Reports Scenario Outlines",
      outcome: "SUCCESS",
      duration: 40,
      startedAt: "2024-06-15T14:30:01.048Z",
      source: { path: "reporting_results/reports_scenario_outlines.feature", line: 8 },
      tags: [
        { type: "feature", name: "Reports Scenario Outlines" },
        { type: "tag", name: "@set-1" },
      ],
      retries: 0,
      cast: [],
      activities: [
        {
          type: "Interaction", name: "When asnov makes a contribution of:", outcome: "SUCCESS", duration: 22,
          children: [],
          dataTable: {
            headers: ["value"],
            rows: [["time"], ["talent"], ["great code"]],
          },
        },
        {
          type: "Interaction", name: "Then they help bring serenity to fellow devs", outcome: "SUCCESS", duration: 18,
          children: [],
        },
      ],
    },

    {
      id: "scenario-16",
      name: "People who make Serenity happen — wakaleo",
      category: "Reporting Results › Reports Scenario Outlines",
      outcome: "SUCCESS",
      duration: 39,
      startedAt: "2024-06-15T14:30:01.088Z",
      source: { path: "reporting_results/reports_scenario_outlines.feature", line: 8 },
      tags: [
        { type: "feature", name: "Reports Scenario Outlines" },
        { type: "tag", name: "@set-1" },
      ],
      retries: 0,
      cast: [],
      activities: [
        {
          type: "Interaction", name: "When wakaleo makes a contribution of:", outcome: "SUCCESS", duration: 22,
          children: [],
          dataTable: {
            headers: ["value"],
            rows: [["time"], ["talent"], ["great code"]],
          },
        },
        {
          type: "Interaction", name: "Then they help bring serenity to fellow devs", outcome: "SUCCESS", duration: 17,
          children: [],
        },
      ],
    },

    {
      id: "scenario-17",
      name: "People who make Serenity happen — mustafa-turab-ali",
      category: "Reporting Results › Reports Scenario Outlines",
      outcome: "SUCCESS",
      duration: 41,
      startedAt: "2024-06-15T14:30:01.127Z",
      source: { path: "reporting_results/reports_scenario_outlines.feature", line: 8 },
      tags: [
        { type: "feature", name: "Reports Scenario Outlines" },
        { type: "tag", name: "@set-1" },
      ],
      retries: 0,
      cast: [],
      activities: [
        {
          type: "Interaction", name: "When mustafa-turab-ali makes a contribution of:", outcome: "SUCCESS", duration: 23,
          children: [],
          dataTable: {
            headers: ["value"],
            rows: [["time"], ["talent"], ["great code"]],
          },
        },
        {
          type: "Interaction", name: "Then they help bring serenity to fellow devs", outcome: "SUCCESS", duration: 18,
          children: [],
        },
      ],
    },

    // @set-2 examples (representative sample of 3)

    {
      id: "scenario-18",
      name: "People who make Serenity happen — YamStranger",
      category: "Reporting Results › Reports Scenario Outlines",
      outcome: "SUCCESS",
      duration: 43,
      startedAt: "2024-06-15T14:30:01.650Z",
      source: { path: "reporting_results/reports_scenario_outlines.feature", line: 8 },
      tags: [
        { type: "feature", name: "Reports Scenario Outlines" },
        { type: "tag", name: "@set-2" },
      ],
      retries: 0,
      cast: [],
      activities: [
        {
          type: "Interaction", name: "When YamStranger makes a contribution of:", outcome: "SUCCESS", duration: 25,
          children: [],
          dataTable: {
            headers: ["value"],
            rows: [["time"], ["talent"], ["great code"]],
          },
        },
        {
          type: "Interaction", name: "Then they help bring serenity to fellow devs", outcome: "SUCCESS", duration: 18,
          children: [],
        },
      ],
    },

    {
      id: "scenario-19",
      name: "People who make Serenity happen — cliviu",
      category: "Reporting Results › Reports Scenario Outlines",
      outcome: "SUCCESS",
      duration: 40,
      startedAt: "2024-06-15T14:30:01.693Z",
      source: { path: "reporting_results/reports_scenario_outlines.feature", line: 8 },
      tags: [
        { type: "feature", name: "Reports Scenario Outlines" },
        { type: "tag", name: "@set-2" },
      ],
      retries: 0,
      cast: [],
      activities: [
        {
          type: "Interaction", name: "When cliviu makes a contribution of:", outcome: "SUCCESS", duration: 22,
          children: [],
          dataTable: {
            headers: ["value"],
            rows: [["time"], ["talent"], ["great code"]],
          },
        },
        {
          type: "Interaction", name: "Then they help bring serenity to fellow devs", outcome: "SUCCESS", duration: 18,
          children: [],
        },
      ],
    },

    {
      id: "scenario-20",
      name: "People who make Serenity happen — verhagen",
      category: "Reporting Results › Reports Scenario Outlines",
      outcome: "SUCCESS",
      duration: 41,
      startedAt: "2024-06-15T14:30:01.733Z",
      source: { path: "reporting_results/reports_scenario_outlines.feature", line: 8 },
      tags: [
        { type: "feature", name: "Reports Scenario Outlines" },
        { type: "tag", name: "@set-2" },
      ],
      retries: 0,
      cast: [],
      activities: [
        {
          type: "Interaction", name: "When verhagen makes a contribution of:", outcome: "SUCCESS", duration: 23,
          children: [],
          dataTable: {
            headers: ["value"],
            rows: [["time"], ["talent"], ["great code"]],
          },
        },
        {
          type: "Interaction", name: "Then they help bring serenity to fellow devs", outcome: "SUCCESS", duration: 18,
          children: [],
        },
      ],
    },

    // ─────────────────────────────────────────────────────────────────────────────
    // Feature: Reports Data Table arguments (reporting_special_step_arguments)
    // ─────────────────────────────────────────────────────────────────────────────

    {
      id: "scenario-21",
      name: "A Data Table argument",
      category: "Reporting Special Step Arguments › Reports Data Table Arguments",
      outcome: "SUCCESS",
      duration: 32,
      startedAt: "2024-06-15T14:30:03.800Z",
      source: { path: "reporting_special_step_arguments/reports_data_table_arguments.feature", line: 8 },
      narrative: "In order to see how Serenity/JS reports a Data Table argument\nAs a curious developer\nI'd like to see an example implementation",
      tags: [
        { type: "feature", name: "Reports Data Table Arguments" },
      ],
      retries: 0,
      cast: [],
      activities: [
        {
          type: "Interaction", name: "Given a step that receives a table:", outcome: "SUCCESS", duration: 32,
          children: [],
          dataTable: {
            headers: ["Developer", "Website"],
            rows: [["Jan Molak", "janmolak.com"]],
          },
        },
      ],
    },

    // ─────────────────────────────────────────────────────────────────────────────
    // Feature: Reports DocString arguments (reporting_special_step_arguments)
    // ─────────────────────────────────────────────────────────────────────────────

    {
      id: "scenario-22",
      name: "A DocString argument",
      category: "Reporting Special Step Arguments › Reports DocString Arguments",
      outcome: "SUCCESS",
      duration: 28,
      startedAt: "2024-06-15T14:30:03.832Z",
      source: { path: "reporting_special_step_arguments/reports_docstring_arguments.feature", line: 8 },
      narrative: "In order to see how Serenity/JS reports a DocString argument\nAs a curious developer\nI'd like to see an example implementation",
      tags: [
        { type: "feature", name: "Reports DocString Arguments" },
      ],
      retries: 0,
      cast: [],
      activities: [
        {
          type: "Interaction", name: "Given a step that receives a doc string:", outcome: "SUCCESS", duration: 28,
          children: [],
          docString: "Dear customer,\n\nPlease click this link to reset your password.",
        },
      ],
    },
  ],

  tags: [
    { type: "feature", name: "Transferring Points Between Members", scenarioCount: 3, passed: 3, failed: 0 },
    { type: "feature", name: "Reports Passing Scenarios", scenarioCount: 1, passed: 1, failed: 0 },
    { type: "feature", name: "Reports Failing Scenarios", scenarioCount: 4, passed: 0, failed: 4 },
    { type: "feature", name: "Reports Pending Scenarios", scenarioCount: 1, passed: 0, failed: 0 },
    { type: "feature", name: "Reports Compromised Scenarios", scenarioCount: 1, passed: 0, failed: 0 },
    { type: "feature", name: "Reports Errors In Scenarios", scenarioCount: 1, passed: 0, failed: 1 },
    { type: "feature", name: "Reports Timed Out Scenarios", scenarioCount: 1, passed: 0, failed: 1 },
    { type: "feature", name: "Reports Scenario Outlines", scenarioCount: 42, passed: 42, failed: 0 },
    { type: "feature", name: "Reports Data Table Arguments", scenarioCount: 1, passed: 1, failed: 0 },
    { type: "feature", name: "Reports DocString Arguments", scenarioCount: 1, passed: 1, failed: 0 },
    { type: "tag", name: "@set-1", scenarioCount: 12, passed: 12, failed: 0 },
    { type: "tag", name: "@set-2", scenarioCount: 30, passed: 30, failed: 0 },
    { type: "issue", name: "GH-1234", scenarioCount: 2, passed: 0, failed: 2 },
    { type: "issue", name: "GH-5678", scenarioCount: 1, passed: 1, failed: 0 },
  ],

  history: [
    { timestamp: "2024-06-11T10:00:00.000Z", outcomes: { passed: 40, failed: 8, pending: 2, skipped: 0, compromised: 2, error: 1 }, duration: 5800, label: "build #85", ciJobUrl: "https://github.com/serenity-js/serenity-js/actions/runs/9485242001" },
    { timestamp: "2024-06-12T14:30:00.000Z", outcomes: { passed: 43, failed: 6, pending: 1, skipped: 0, compromised: 2, error: 1 }, duration: 5100, label: "build #86", ciJobUrl: "https://github.com/serenity-js/serenity-js/actions/runs/9485242002" },
    { timestamp: "2024-06-13T09:15:00.000Z", outcomes: { passed: 45, failed: 5, pending: 1, skipped: 0, compromised: 1, error: 1 }, duration: 4600, label: "build #87", ciJobUrl: "https://github.com/serenity-js/serenity-js/actions/runs/9485242003" },
    { timestamp: "2024-06-14T16:45:00.000Z", outcomes: { passed: 45, failed: 5, pending: 1, skipped: 0, compromised: 1, error: 1 }, duration: 4400, label: "build #88", ciJobUrl: "https://github.com/serenity-js/serenity-js/actions/runs/9485242004" },
    { timestamp: "2024-06-15T14:30:00.000Z", outcomes: { passed: 46, failed: 4, pending: 1, skipped: 0, compromised: 1, error: 1 }, duration: 4200, label: "build #89", ciJobUrl: "https://github.com/serenity-js/serenity-js/actions/runs/9485242005" },
  ],

  // Requirements hierarchy with coverage information
  // Represents the directory structure under the configured specDirectory
  requirements: {
    name: "features",
    path: "",
    type: "directory",
    readme: "In order to quickly learn how to use Serenity/JS with Cucumber\nAs a busy developer\nI'd like to see examples demonstrating how Serenity/JS reports the result of executing Cucumber test scenarios.",
    outcomes: { passed: 46, failed: 4, pending: 1, skipped: 0, compromised: 1, error: 1 },
    children: [
      {
        name: "frequent_flyers",
        displayName: "Frequent Flyers",
        path: "frequent_flyers",
        type: "directory",
        outcomes: { passed: 3, failed: 0, pending: 0, skipped: 0, compromised: 0, error: 0 },
        children: [
          { name: "transferring_points_between_members.feature", displayName: "Transferring Points Between Members", path: "frequent_flyers/transferring_points_between_members.feature", type: "file", outcomes: { passed: 3, failed: 0, pending: 0, skipped: 0, compromised: 0, error: 0 }, scenarioCount: 3 },
        ],
      },
      {
        name: "reporting_results",
        displayName: "Reporting Results",
        path: "reporting_results",
        type: "directory",
        outcomes: { passed: 43, failed: 4, pending: 1, skipped: 0, compromised: 1, error: 1 },
        children: [
          { name: "reports_passing_scenarios.feature", displayName: "Reports Passing Scenarios", path: "reporting_results/reports_passing_scenarios.feature", type: "file", outcomes: { passed: 1, failed: 0, pending: 0, skipped: 0, compromised: 0, error: 0 }, scenarioCount: 1 },
          { name: "reports_failing_scenarios.feature", displayName: "Reports Failing Scenarios", path: "reporting_results/reports_failing_scenarios.feature", type: "file", outcomes: { passed: 0, failed: 4, pending: 0, skipped: 0, compromised: 0, error: 0 }, scenarioCount: 4 },
          { name: "reports_scenario_outlines.feature", displayName: "Reports Scenario Outlines", path: "reporting_results/reports_scenario_outlines.feature", type: "file", outcomes: { passed: 42, failed: 0, pending: 0, skipped: 0, compromised: 0, error: 0 }, scenarioCount: 42 },
          { name: "reports_compromised_scenarios.feature", displayName: "Reports Compromised Scenarios", path: "reporting_results/reports_compromised_scenarios.feature", type: "file", outcomes: { passed: 0, failed: 0, pending: 0, skipped: 0, compromised: 1, error: 0 }, scenarioCount: 1 },
          { name: "reports_pending_scenarios.feature", displayName: "Reports Pending Scenarios", path: "reporting_results/reports_pending_scenarios.feature", type: "file", outcomes: { passed: 0, failed: 0, pending: 1, skipped: 0, compromised: 0, error: 0 }, scenarioCount: 1 },
          { name: "reports_errors_in_scenarios.feature", displayName: "Reports Errors In Scenarios", path: "reporting_results/reports_errors_in_scenarios.feature", type: "file", outcomes: { passed: 0, failed: 0, pending: 0, skipped: 0, compromised: 0, error: 1 }, scenarioCount: 1 },
          { name: "reports_timed_out_scenarios.feature", displayName: "Reports Timed Out Scenarios", path: "reporting_results/reports_timed_out_scenarios.feature", type: "file", outcomes: { passed: 0, failed: 1, pending: 0, skipped: 0, compromised: 0, error: 0 }, scenarioCount: 1 },
        ],
      },
      {
        name: "reporting_special_step_arguments",
        displayName: "Reporting Special Step Arguments",
        path: "reporting_special_step_arguments",
        type: "directory",
        outcomes: { passed: 2, failed: 0, pending: 0, skipped: 0, compromised: 0, error: 0 },
        children: [
          { name: "reports_data_table_arguments.feature", displayName: "Reports Data Table Arguments", path: "reporting_special_step_arguments/reports_data_table_arguments.feature", type: "file", outcomes: { passed: 1, failed: 0, pending: 0, skipped: 0, compromised: 0, error: 0 }, scenarioCount: 1 },
          { name: "reports_docstring_arguments.feature", displayName: "Reports DocString Arguments", path: "reporting_special_step_arguments/reports_docstring_arguments.feature", type: "file", outcomes: { passed: 1, failed: 0, pending: 0, skipped: 0, compromised: 0, error: 0 }, scenarioCount: 1 },
        ],
      },
      // Coverage gaps — directories/files with no tests or mostly pending/skipped
      {
        name: "booking_flights",
        displayName: "Booking Flights",
        path: "booking_flights",
        type: "directory",
        outcomes: { passed: 0, failed: 0, pending: 0, skipped: 0, compromised: 0, error: 0 },
        children: [
          { name: "searching_for_flights.feature", displayName: "Searching For Flights", path: "booking_flights/searching_for_flights.feature", type: "file", outcomes: { passed: 0, failed: 0, pending: 0, skipped: 0, compromised: 0, error: 0 }, scenarioCount: 0 },
          { name: "selecting_seats.feature", displayName: "Selecting Seats", path: "booking_flights/selecting_seats.feature", type: "file", outcomes: { passed: 0, failed: 0, pending: 0, skipped: 0, compromised: 0, error: 0 }, scenarioCount: 0 },
          { name: "payment_processing.feature", displayName: "Payment Processing", path: "booking_flights/payment_processing.feature", type: "file", outcomes: { passed: 0, failed: 0, pending: 0, skipped: 0, compromised: 0, error: 0 }, scenarioCount: 0 },
        ],
      },
      {
        name: "member_registration",
        displayName: "Member Registration",
        path: "member_registration",
        type: "directory",
        outcomes: { passed: 0, failed: 0, pending: 2, skipped: 1, compromised: 0, error: 0 },
        children: [
          { name: "registering_new_members.feature", displayName: "Registering New Members", path: "member_registration/registering_new_members.feature", type: "file", outcomes: { passed: 0, failed: 0, pending: 2, skipped: 0, compromised: 0, error: 0 }, scenarioCount: 2 },
          { name: "email_verification.feature", displayName: "Email Verification", path: "member_registration/email_verification.feature", type: "file", outcomes: { passed: 0, failed: 0, pending: 0, skipped: 1, compromised: 0, error: 0 }, scenarioCount: 1 },
        ],
      },
    ],
  },

  flakyTests: [
    {
      id: "scenario-12",
      name: "A timed out scenario",
      category: "Reporting Results › Reports Timed Out Scenarios",
      source: { path: "reporting_results/reports_timed_out_scenarios.feature", line: 8 },
      flakinessRate: 0.6,
      history: ["FAILURE", "SUCCESS", "FAILURE", "SUCCESS", "FAILURE"],
      labels: ["#85", "#86", "#87", "#88", "#89"],
    },
    {
      id: "scenario-7",
      name: "should allow me to edit a todo item",
      category: "Reporting Results › Reports Failing Scenarios",
      source: { path: "reporting_results/reports_failing_scenarios.feature", line: 24 },
      flakinessRate: 0.4,
      history: ["SUCCESS", "FAILURE", "SUCCESS", "SUCCESS", "FAILURE"],
      labels: ["#85", "#86", "#87", "#88", "#89"],
    },
    {
      id: "scenario-11",
      name: "should persist data after page reload",
      category: "Reporting Results › Reports Compromised Scenarios",
      source: { path: "reporting_results/reports_compromised_scenarios.feature", line: 8 },
      flakinessRate: 0.25,
      history: ["SUCCESS", "SUCCESS", "COMPROMISED", "SUCCESS", "COMPROMISED"],
      labels: ["#85", "#86", "#87", "#88", "#89"],
    },
  ],

  systemContext: {
    nodeVersion: "v22.4.0",
    testRunner: { name: "Cucumber.js", version: "12.2.0" },
    browsers: [],
    os: { name: "macOS", version: "14.5", arch: "arm64" },
    serenityVersion: "3.25.4",
    ci: {
      provider: "GitHub Actions",
      buildNumber: "89",
      branch: "main",
      commit: "f7e8a2b",
      commitMessage: "test(cucumber): demonstrate reporting capabilities",
    },
  },
};
