name: 'Set up JRE'
description: 'Sets up Java Runtime Environment'

inputs:
  java-version:
    description: 'The Java version to set up. Takes a whole or semver Java version. See examples of supported syntax in README file'
    type: string
    required: true
    default: '17'

# See https://github.com/serenity-bdd/serenity-core/blob/58beebe356d63feee8a9b83e2702116578108eba/.github/workflows/ci_build.yml

runs:
  using: 'composite'
  steps:
    - name: Set up JDK 17
      uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4
      with:
        distribution: 'temurin' # 'temurin' distribution provides OpenJ9 builds of the OpenJDK
        java-version: ${{ inputs.java-version }}
        java-package: 'jre'
