check-leaks: false
color: true
diff: true
exit: true
full-trace: true
reporter: '@serenity-js/mocha'
require:
  - 'ts-node/register'
  - './setup.ts'
timeout: 60000
v8-stack-trace-limit: 100
spec:
  - './spec/**/*.spec.ts'
