window.esdocSearchIndex = [
  [
    "@serenity-js/jasmine/lib/adapter~jasmineadapter",
    "class/src/adapter/JasmineAdapter.ts~JasmineAdapter.html",
    "<span>JasmineAdapter</span> <span class=\"search-result-import-path\">@serenity-js/jasmine/lib/adapter</span>",
    "class"
  ],
  [
    "@serenity-js/jasmine/lib/adapter~jasmineconfig",
    "class/src/adapter/JasmineConfig.ts~JasmineConfig.html",
    "<span>JasmineConfig</span> <span class=\"search-result-import-path\">@serenity-js/jasmine/lib/adapter</span>",
    "class"
  ],
  [
    "@serenity-js/jasmine~serenityreporterforjasmine",
    "class/src/SerenityReporterForJasmine.ts~SerenityReporterForJasmine.html",
    "<span>SerenityReporterForJasmine</span> <span class=\"search-result-import-path\">@serenity-js/jasmine</span>",
    "class"
  ],
  [
    "@serenity-js/jasmine~bootstrap",
    "function/index.html#static-function-bootstrap",
    "<span>bootstrap</span> <span class=\"search-result-import-path\">@serenity-js/jasmine</span>",
    "function"
  ],
  [
    "@serenity-js/jasmine~monkeypatched",
    "function/index.html#static-function-monkeyPatched",
    "<span>monkeyPatched</span> <span class=\"search-result-import-path\">@serenity-js/jasmine</span>",
    "function"
  ],
  [
    "@serenity-js/core/lib/errors~assertionerror",
    "/modules/core/class/src/errors/AssertionError.ts~AssertionError.html",
    "@serenity-js/core/lib/errors~AssertionError",
    "external"
  ],
  [
    "@serenity-js/core/lib/errors~configurationerror",
    "/modules/core/class/src/errors/ConfigurationError.ts~ConfigurationError.html",
    "@serenity-js/core/lib/errors~ConfigurationError",
    "external"
  ],
  [
    "@serenity-js/core/lib/errors~implementationpendingerror",
    "/modules/core/class/src/errors/ImplementationPendingError.ts~ImplementationPendingError.html",
    "@serenity-js/core/lib/errors~ImplementationPendingError",
    "external"
  ],
  [
    "@serenity-js/core/lib/errors~logicerror",
    "/modules/core/class/src/errors/LogicError.ts~LogicError.html",
    "@serenity-js/core/lib/errors~LogicError",
    "external"
  ],
  [
    "@serenity-js/core/lib/errors~runtimeerror",
    "/modules/core/class/src/errors/RuntimeError.ts~RuntimeError.html",
    "@serenity-js/core/lib/errors~RuntimeError",
    "external"
  ],
  [
    "@serenity-js/core/lib/errors~testcompromisederror",
    "/modules/core/class/src/errors/TestCompromisedError.ts~TestCompromisedError.html",
    "@serenity-js/core/lib/errors~TestCompromisedError",
    "external"
  ],
  [
    "@serenity-js/core/lib/errors~unknownerror",
    "/modules/core/class/src/errors/UnknownError.ts~UnknownError.html",
    "@serenity-js/core/lib/errors~UnknownError",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~activityfinished",
    "/modules/core/class/src/events/ActivityFinished.ts~ActivityFinished.html",
    "@serenity-js/core/lib/events~ActivityFinished",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~activityrelatedartifactarchived",
    "/modules/core/class/src/events/ActivityRelatedArtifactArchived.ts~ActivityRelatedArtifactArchived.html",
    "@serenity-js/core/lib/events~ActivityRelatedArtifactArchived",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~activityrelatedartifactgenerated",
    "/modules/core/class/src/events/ActivityRelatedArtifactGenerated.ts~ActivityRelatedArtifactGenerated.html",
    "@serenity-js/core/lib/events~ActivityRelatedArtifactGenerated",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~activitystarts",
    "/modules/core/class/src/events/ActivityStarts.ts~ActivityStarts.html",
    "@serenity-js/core/lib/events~ActivityStarts",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~artifactarchived",
    "/modules/core/class/src/events/ArtifactArchived.ts~ArtifactArchived.html",
    "@serenity-js/core/lib/events~ArtifactArchived",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~artifactgenerated",
    "/modules/core/class/src/events/ArtifactGenerated.ts~ArtifactGenerated.html",
    "@serenity-js/core/lib/events~ArtifactGenerated",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~asyncoperationattempted",
    "/modules/core/class/src/events/AsyncOperationAttempted.ts~AsyncOperationAttempted.html",
    "@serenity-js/core/lib/events~AsyncOperationAttempted",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~asyncoperationcompleted",
    "/modules/core/class/src/events/AsyncOperationCompleted.ts~AsyncOperationCompleted.html",
    "@serenity-js/core/lib/events~AsyncOperationCompleted",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~asyncoperationfailed",
    "/modules/core/class/src/events/AsyncOperationFailed.ts~AsyncOperationFailed.html",
    "@serenity-js/core/lib/events~AsyncOperationFailed",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~domainevent",
    "/modules/core/class/src/events/DomainEvent.ts~DomainEvent.html",
    "@serenity-js/core/lib/events~DomainEvent",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~featurenarrativedetected",
    "/modules/core/class/src/events/FeatureNarrativeDetected.ts~FeatureNarrativeDetected.html",
    "@serenity-js/core/lib/events~FeatureNarrativeDetected",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~interactionfinished",
    "/modules/core/class/src/events/InteractionFinished.ts~InteractionFinished.html",
    "@serenity-js/core/lib/events~InteractionFinished",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~interactionstarts",
    "/modules/core/class/src/events/InteractionStarts.ts~InteractionStarts.html",
    "@serenity-js/core/lib/events~InteractionStarts",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~scenebackgrounddetected",
    "/modules/core/class/src/events/SceneBackgroundDetected.ts~SceneBackgroundDetected.html",
    "@serenity-js/core/lib/events~SceneBackgroundDetected",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~scenedescriptiondetected",
    "/modules/core/class/src/events/SceneDescriptionDetected.ts~SceneDescriptionDetected.html",
    "@serenity-js/core/lib/events~SceneDescriptionDetected",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~scenefinished",
    "/modules/core/class/src/events/SceneFinished.ts~SceneFinished.html",
    "@serenity-js/core/lib/events~SceneFinished",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~scenefinishes",
    "/modules/core/class/src/events/SceneFinishes.ts~SceneFinishes.html",
    "@serenity-js/core/lib/events~SceneFinishes",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~sceneparametersdetected",
    "/modules/core/class/src/events/SceneParametersDetected.ts~SceneParametersDetected.html",
    "@serenity-js/core/lib/events~SceneParametersDetected",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~scenesequencedetected",
    "/modules/core/class/src/events/SceneSequenceDetected.ts~SceneSequenceDetected.html",
    "@serenity-js/core/lib/events~SceneSequenceDetected",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~scenestarts",
    "/modules/core/class/src/events/SceneStarts.ts~SceneStarts.html",
    "@serenity-js/core/lib/events~SceneStarts",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~scenetagged",
    "/modules/core/class/src/events/SceneTagged.ts~SceneTagged.html",
    "@serenity-js/core/lib/events~SceneTagged",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~scenetemplatedetected",
    "/modules/core/class/src/events/SceneTemplateDetected.ts~SceneTemplateDetected.html",
    "@serenity-js/core/lib/events~SceneTemplateDetected",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~taskfinished",
    "/modules/core/class/src/events/TaskFinished.ts~TaskFinished.html",
    "@serenity-js/core/lib/events~TaskFinished",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~taskstarts",
    "/modules/core/class/src/events/TaskStarts.ts~TaskStarts.html",
    "@serenity-js/core/lib/events~TaskStarts",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~testrunfinished",
    "/modules/core/class/src/events/TestRunFinished.ts~TestRunFinished.html",
    "@serenity-js/core/lib/events~TestRunFinished",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~testrunfinishes",
    "/modules/core/class/src/events/TestRunFinishes.ts~TestRunFinishes.html",
    "@serenity-js/core/lib/events~TestRunFinishes",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~testrunnerdetected",
    "/modules/core/class/src/events/TestRunnerDetected.ts~TestRunnerDetected.html",
    "@serenity-js/core/lib/events~TestRunnerDetected",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~testsuitefinished",
    "/modules/core/class/src/events/TestSuiteFinished.ts~TestSuiteFinished.html",
    "@serenity-js/core/lib/events~TestSuiteFinished",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~testsuitestarts",
    "/modules/core/class/src/events/TestSuiteStarts.ts~TestSuiteStarts.html",
    "@serenity-js/core/lib/events~TestSuiteStarts",
    "external"
  ],
  [
    "@serenity-js/core/lib/io~assertionreportdiffer",
    "/modules/core/class/src/io/AssertionReportDiffer.ts~AssertionReportDiffer.html",
    "@serenity-js/core/lib/io~AssertionReportDiffer",
    "external"
  ],
  [
    "@serenity-js/core/lib/io~errorserialiser",
    "/modules/core/class/src/io/ErrorSerialiser.ts~ErrorSerialiser.html",
    "@serenity-js/core/lib/io~ErrorSerialiser",
    "external"
  ],
  [
    "@serenity-js/core/lib/io~filesystem",
    "/modules/core/class/src/io/FileSystem.ts~FileSystem.html",
    "@serenity-js/core/lib/io~FileSystem",
    "external"
  ],
  [
    "@serenity-js/core/lib/io~filesystemlocation",
    "/modules/core/class/src/io/FileSystemLocation.ts~FileSystemLocation.html",
    "@serenity-js/core/lib/io~FileSystemLocation",
    "external"
  ],
  [
    "@serenity-js/core/lib/io~moduleloader",
    "/modules/core/class/src/io/ModuleLoader.ts~ModuleLoader.html",
    "@serenity-js/core/lib/io~ModuleLoader",
    "external"
  ],
  [
    "@serenity-js/core/lib/io~path",
    "/modules/core/class/src/io/Path.ts~Path.html",
    "@serenity-js/core/lib/io~Path",
    "external"
  ],
  [
    "@serenity-js/core/lib/io~serialisederror",
    "/modules/core/class/src/io/ErrorSerialiser.ts~SerialisedError.html",
    "@serenity-js/core/lib/io~SerialisedError",
    "external"
  ],
  [
    "@serenity-js/core/lib/io~version",
    "/modules/core/class/src/io/Version.ts~Version.html",
    "@serenity-js/core/lib/io~Version",
    "external"
  ],
  [
    "@serenity-js/core/lib/io~commaseparated",
    "/modules/core/function/src/io/commaSeparated.ts~commaSeparated.html",
    "@serenity-js/core/lib/io~commaSeparated",
    "external"
  ],
  [
    "@serenity-js/core/lib/io~formatted",
    "/modules/core/function/src/io/formatted.ts~formatted.html",
    "@serenity-js/core/lib/io~formatted",
    "external"
  ],
  [
    "@serenity-js/core/lib/io~inspected",
    "/modules/core/function/src/io/inspected.ts~inspected.html",
    "@serenity-js/core/lib/io~inspected",
    "external"
  ],
  [
    "@serenity-js/core/lib/io~trimmed",
    "/modules/core/function/src/io/trimmed.ts~trimmed.html",
    "@serenity-js/core/lib/io~trimmed",
    "external"
  ],
  [
    "@serenity-js/core/lib/model/artifacts~assertionreport",
    "/modules/core/class/src/model/artifacts/AssertionReport.ts~AssertionReport.html",
    "@serenity-js/core/lib/model/artifacts~AssertionReport",
    "external"
  ],
  [
    "@serenity-js/core/lib/model/artifacts~httprequestresponse",
    "/modules/core/class/src/model/artifacts/HTTPRequestResponse.ts~HTTPRequestResponse.html",
    "@serenity-js/core/lib/model/artifacts~HTTPRequestResponse",
    "external"
  ],
  [
    "@serenity-js/core/lib/model/artifacts~jsondata",
    "/modules/core/class/src/model/artifacts/JSONData.ts~JSONData.html",
    "@serenity-js/core/lib/model/artifacts~JSONData",
    "external"
  ],
  [
    "@serenity-js/core/lib/model/artifacts~logentry",
    "/modules/core/class/src/model/artifacts/LogEntry.ts~LogEntry.html",
    "@serenity-js/core/lib/model/artifacts~LogEntry",
    "external"
  ],
  [
    "@serenity-js/core/lib/model/artifacts~photo",
    "/modules/core/class/src/model/artifacts/Photo.ts~Photo.html",
    "@serenity-js/core/lib/model/artifacts~Photo",
    "external"
  ],
  [
    "@serenity-js/core/lib/model/artifacts~requestandresponse",
    "/modules/core/class/src/model/artifacts/HTTPRequestResponse.ts~RequestAndResponse.html",
    "@serenity-js/core/lib/model/artifacts~RequestAndResponse",
    "external"
  ],
  [
    "@serenity-js/core/lib/model/artifacts~testreport",
    "/modules/core/class/src/model/artifacts/TestReport.ts~TestReport.html",
    "@serenity-js/core/lib/model/artifacts~TestReport",
    "external"
  ],
  [
    "@serenity-js/core/lib/model/artifacts~textdata",
    "/modules/core/class/src/model/artifacts/TextData.ts~TextData.html",
    "@serenity-js/core/lib/model/artifacts~TextData",
    "external"
  ],
  [
    "@serenity-js/core/lib/model/tags~arbitrarytag",
    "/modules/core/class/src/model/tags/ArbitraryTag.ts~ArbitraryTag.html",
    "@serenity-js/core/lib/model/tags~ArbitraryTag",
    "external"
  ],
  [
    "@serenity-js/core/lib/model/tags~browsertag",
    "/modules/core/class/src/model/tags/BrowserTag.ts~BrowserTag.html",
    "@serenity-js/core/lib/model/tags~BrowserTag",
    "external"
  ],
  [
    "@serenity-js/core/lib/model/tags~capabilitytag",
    "/modules/core/class/src/model/tags/CapabilityTag.ts~CapabilityTag.html",
    "@serenity-js/core/lib/model/tags~CapabilityTag",
    "external"
  ],
  [
    "@serenity-js/core/lib/model/tags~contexttag",
    "/modules/core/class/src/model/tags/ContextTag.ts~ContextTag.html",
    "@serenity-js/core/lib/model/tags~ContextTag",
    "external"
  ],
  [
    "@serenity-js/core/lib/model/tags~executionretriedtag",
    "/modules/core/class/src/model/tags/ExecutionRetriedTag.ts~ExecutionRetriedTag.html",
    "@serenity-js/core/lib/model/tags~ExecutionRetriedTag",
    "external"
  ],
  [
    "@serenity-js/core/lib/model/tags~featuretag",
    "/modules/core/class/src/model/tags/FeatureTag.ts~FeatureTag.html",
    "@serenity-js/core/lib/model/tags~FeatureTag",
    "external"
  ],
  [
    "@serenity-js/core/lib/model/tags~issuetag",
    "/modules/core/class/src/model/tags/IssueTag.ts~IssueTag.html",
    "@serenity-js/core/lib/model/tags~IssueTag",
    "external"
  ],
  [
    "@serenity-js/core/lib/model/tags~manualtag",
    "/modules/core/class/src/model/tags/ManualTag.ts~ManualTag.html",
    "@serenity-js/core/lib/model/tags~ManualTag",
    "external"
  ],
  [
    "@serenity-js/core/lib/model/tags~platformtag",
    "/modules/core/class/src/model/tags/PlatformTag.ts~PlatformTag.html",
    "@serenity-js/core/lib/model/tags~PlatformTag",
    "external"
  ],
  [
    "@serenity-js/core/lib/model/tags~tag",
    "/modules/core/class/src/model/tags/Tag.ts~Tag.html",
    "@serenity-js/core/lib/model/tags~Tag",
    "external"
  ],
  [
    "@serenity-js/core/lib/model/tags~themetag",
    "/modules/core/class/src/model/tags/ThemeTag.ts~ThemeTag.html",
    "@serenity-js/core/lib/model/tags~ThemeTag",
    "external"
  ],
  [
    "@serenity-js/core/lib/model~activitydetails",
    "/modules/core/class/src/model/ActivityDetails.ts~ActivityDetails.html",
    "@serenity-js/core/lib/model~ActivityDetails",
    "external"
  ],
  [
    "@serenity-js/core/lib/model~artifact",
    "/modules/core/class/src/model/Artifact.ts~Artifact.html",
    "@serenity-js/core/lib/model~Artifact",
    "external"
  ],
  [
    "@serenity-js/core/lib/model~category",
    "/modules/core/class/src/model/Category.ts~Category.html",
    "@serenity-js/core/lib/model~Category",
    "external"
  ],
  [
    "@serenity-js/core/lib/model~correlationid",
    "/modules/core/class/src/model/CorrelationId.ts~CorrelationId.html",
    "@serenity-js/core/lib/model~CorrelationId",
    "external"
  ],
  [
    "@serenity-js/core/lib/model~description",
    "/modules/core/class/src/model/Description.ts~Description.html",
    "@serenity-js/core/lib/model~Description",
    "external"
  ],
  [
    "@serenity-js/core/lib/model~duration",
    "/modules/core/class/src/model/Duration.ts~Duration.html",
    "@serenity-js/core/lib/model~Duration",
    "external"
  ],
  [
    "@serenity-js/core/lib/model~executioncompromised",
    "/modules/core/class/src/model/outcomes.ts~ExecutionCompromised.html",
    "@serenity-js/core/lib/model~ExecutionCompromised",
    "external"
  ],
  [
    "@serenity-js/core/lib/model~executionfailedwithassertionerror",
    "/modules/core/class/src/model/outcomes.ts~ExecutionFailedWithAssertionError.html",
    "@serenity-js/core/lib/model~ExecutionFailedWithAssertionError",
    "external"
  ],
  [
    "@serenity-js/core/lib/model~executionfailedwitherror",
    "/modules/core/class/src/model/outcomes.ts~ExecutionFailedWithError.html",
    "@serenity-js/core/lib/model~ExecutionFailedWithError",
    "external"
  ],
  [
    "@serenity-js/core/lib/model~executionignored",
    "/modules/core/class/src/model/outcomes.ts~ExecutionIgnored.html",
    "@serenity-js/core/lib/model~ExecutionIgnored",
    "external"
  ],
  [
    "@serenity-js/core/lib/model~executionskipped",
    "/modules/core/class/src/model/outcomes.ts~ExecutionSkipped.html",
    "@serenity-js/core/lib/model~ExecutionSkipped",
    "external"
  ],
  [
    "@serenity-js/core/lib/model~executionsuccessful",
    "/modules/core/class/src/model/outcomes.ts~ExecutionSuccessful.html",
    "@serenity-js/core/lib/model~ExecutionSuccessful",
    "external"
  ],
  [
    "@serenity-js/core/lib/model~implementationpending",
    "/modules/core/class/src/model/outcomes.ts~ImplementationPending.html",
    "@serenity-js/core/lib/model~ImplementationPending",
    "external"
  ],
  [
    "@serenity-js/core/lib/model~name",
    "/modules/core/class/src/model/Name.ts~Name.html",
    "@serenity-js/core/lib/model~Name",
    "external"
  ],
  [
    "@serenity-js/core/lib/model~outcome",
    "/modules/core/class/src/model/outcomes.ts~Outcome.html",
    "@serenity-js/core/lib/model~Outcome",
    "external"
  ],
  [
    "@serenity-js/core/lib/model~problemindication",
    "/modules/core/class/src/model/outcomes.ts~ProblemIndication.html",
    "@serenity-js/core/lib/model~ProblemIndication",
    "external"
  ],
  [
    "@serenity-js/core/lib/model~scenariodetails",
    "/modules/core/class/src/model/ScenarioDetails.ts~ScenarioDetails.html",
    "@serenity-js/core/lib/model~ScenarioDetails",
    "external"
  ],
  [
    "@serenity-js/core/lib/model~scenarioparameters",
    "/modules/core/class/src/model/ScenarioParameters.ts~ScenarioParameters.html",
    "@serenity-js/core/lib/model~ScenarioParameters",
    "external"
  ],
  [
    "@serenity-js/core/lib/model~testsuitedetails",
    "/modules/core/class/src/model/TestSuiteDetails.ts~TestSuiteDetails.html",
    "@serenity-js/core/lib/model~TestSuiteDetails",
    "external"
  ],
  [
    "@serenity-js/core/lib/model~timestamp",
    "/modules/core/class/src/model/Timestamp.ts~Timestamp.html",
    "@serenity-js/core/lib/model~Timestamp",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay/abilities~takenotes",
    "/modules/core/class/src/screenplay/abilities/TakeNotes.ts~TakeNotes.html",
    "@serenity-js/core/lib/screenplay/abilities~TakeNotes",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay/actor~actor",
    "/modules/core/class/src/screenplay/actor/Actor.ts~Actor.html",
    "@serenity-js/core/lib/screenplay/actor~Actor",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay/actor~answersquestions",
    "/modules/core/class/src/screenplay/actor/AnswersQuestions.ts~AnswersQuestions.html",
    "@serenity-js/core/lib/screenplay/actor~AnswersQuestions",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay/actor~canhaveabilities",
    "/modules/core/class/src/screenplay/actor/CanHaveAbilities.ts~CanHaveAbilities.html",
    "@serenity-js/core/lib/screenplay/actor~CanHaveAbilities",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay/actor~collectsartifacts",
    "/modules/core/class/src/screenplay/actor/CollectsArtifacts.ts~CollectsArtifacts.html",
    "@serenity-js/core/lib/screenplay/actor~CollectsArtifacts",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay/actor~listenstodomainevents",
    "/modules/core/class/src/screenplay/actor/ListensToDomainEvents.ts~ListensToDomainEvents.html",
    "@serenity-js/core/lib/screenplay/actor~ListensToDomainEvents",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay/actor~performsactivities",
    "/modules/core/class/src/screenplay/actor/PerformsActivities.ts~PerformsActivities.html",
    "@serenity-js/core/lib/screenplay/actor~PerformsActivities",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay/actor~usesabilities",
    "/modules/core/class/src/screenplay/actor/UsesAbilities.ts~UsesAbilities.html",
    "@serenity-js/core/lib/screenplay/actor~UsesAbilities",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay/interactions~log",
    "/modules/core/class/src/screenplay/interactions/Log.ts~Log.html",
    "@serenity-js/core/lib/screenplay/interactions~Log",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay/interactions~see",
    "/modules/core/class/src/screenplay/interactions/See.ts~See.html",
    "@serenity-js/core/lib/screenplay/interactions~See",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay/interactions~takenote",
    "/modules/core/class/src/screenplay/interactions/TakeNote.ts~TakeNote.html",
    "@serenity-js/core/lib/screenplay/interactions~TakeNote",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay/questions~note",
    "/modules/core/class/src/screenplay/questions/Note.ts~Note.html",
    "@serenity-js/core/lib/screenplay/questions~Note",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay/questions~transform",
    "/modules/core/class/src/screenplay/questions/Transform.ts~Transform.html",
    "@serenity-js/core/lib/screenplay/questions~Transform",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay~ability",
    "/modules/core/class/src/screenplay/Ability.ts~Ability.html",
    "@serenity-js/core/lib/screenplay~Ability",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay~abilitytype",
    "/modules/core/class/src/screenplay/AbilityType.ts~AbilityType.html",
    "@serenity-js/core/lib/screenplay~AbilityType",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay~activity",
    "/modules/core/class/src/screenplay/Activity.ts~Activity.html",
    "@serenity-js/core/lib/screenplay~Activity",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay~discardable",
    "/modules/core/class/src/screenplay/Discardable.ts~Discardable.html",
    "@serenity-js/core/lib/screenplay~Discardable",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay~interaction",
    "/modules/core/class/src/screenplay/Interaction.ts~Interaction.html",
    "@serenity-js/core/lib/screenplay~Interaction",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay~question",
    "/modules/core/class/src/screenplay/Question.ts~Question.html",
    "@serenity-js/core/lib/screenplay~Question",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay~task",
    "/modules/core/class/src/screenplay/Task.ts~Task.html",
    "@serenity-js/core/lib/screenplay~Task",
    "external"
  ],
  [
    "@serenity-js/core/lib/stage/crew/artifact-archiver~artifactarchiver",
    "/modules/core/class/src/stage/crew/artifact-archiver/ArtifactArchiver.ts~ArtifactArchiver.html",
    "@serenity-js/core/lib/stage/crew/artifact-archiver~ArtifactArchiver",
    "external"
  ],
  [
    "@serenity-js/core/lib/stage/crew/stream-reporter~streamreporter",
    "/modules/core/class/src/stage/crew/stream-reporter/StreamReporter.ts~StreamReporter.html",
    "@serenity-js/core/lib/stage/crew/stream-reporter~StreamReporter",
    "external"
  ],
  [
    "@serenity-js/core/lib/stage~cast",
    "/modules/core/class/src/stage/Cast.ts~Cast.html",
    "@serenity-js/core/lib/stage~Cast",
    "external"
  ],
  [
    "@serenity-js/core/lib/stage~clock",
    "/modules/core/class/src/stage/Clock.ts~Clock.html",
    "@serenity-js/core/lib/stage~Clock",
    "external"
  ],
  [
    "@serenity-js/core/lib/stage~dressingroom",
    "/modules/core/class/src/stage/DressingRoom.ts~DressingRoom.html",
    "@serenity-js/core/lib/stage~DressingRoom",
    "external"
  ],
  [
    "@serenity-js/core/lib/stage~stage",
    "/modules/core/class/src/stage/Stage.ts~Stage.html",
    "@serenity-js/core/lib/stage~Stage",
    "external"
  ],
  [
    "@serenity-js/core/lib/stage~stagecrewmember",
    "/modules/core/class/src/stage/StageCrewMember.ts~StageCrewMember.html",
    "@serenity-js/core/lib/stage~StageCrewMember",
    "external"
  ],
  [
    "@serenity-js/core/lib/stage~stagemanager",
    "/modules/core/class/src/stage/StageManager.ts~StageManager.html",
    "@serenity-js/core/lib/stage~StageManager",
    "external"
  ],
  [
    "@serenity-js/core/lib/stage~withstage",
    "/modules/core/class/src/stage/WithStage.ts~WithStage.html",
    "@serenity-js/core/lib/stage~WithStage",
    "external"
  ],
  [
    "@serenity-js/core~serenity",
    "/modules/core/class/src/Serenity.ts~Serenity.html",
    "@serenity-js/core~Serenity",
    "external"
  ],
  [
    "@serenity-js/core~serenityconfig",
    "/modules/core/class/src/SerenityConfig.ts~SerenityConfig.html",
    "@serenity-js/core~SerenityConfig",
    "external"
  ],
  [
    "@serenity-js/core~actorcalled",
    "/modules/core/function/src/instance.ts~actorCalled.html",
    "@serenity-js/core~actorCalled",
    "external"
  ],
  [
    "@serenity-js/core~actorinthespotlight",
    "/modules/core/function/src/instance.ts~actorInTheSpotlight.html",
    "@serenity-js/core~actorInTheSpotlight",
    "external"
  ],
  [
    "@serenity-js/core~configure",
    "/modules/core/function/src/instance.ts~configure.html",
    "@serenity-js/core~configure",
    "external"
  ],
  [
    "@serenity-js/core~engage",
    "/modules/core/function/src/instance.ts~engage.html",
    "@serenity-js/core~engage",
    "external"
  ],
  [
    "@serenity-js/core~serenity",
    "/modules/core/variable/src/instance.ts~serenity.html",
    "@serenity-js/core~serenity",
    "external"
  ],
  [
    "",
    "test-file/spec/monkeyPatched.spec.ts.html#lineNumber6",
    "@serenity-js/jasmine",
    "test"
  ],
  [
    "",
    "test-file/spec/monkeyPatched.spec.ts.html#lineNumber45",
    "@serenity-js/jasmine monkey-patches Jasmine",
    "test"
  ],
  [
    "",
    "test-file/spec/monkeyPatched.spec.ts.html#lineNumber47",
    "@serenity-js/jasmine monkey-patches Jasmine so that the Spec",
    "test"
  ],
  [
    "",
    "test-file/spec/monkeyPatched.spec.ts.html#lineNumber90",
    "@serenity-js/jasmine monkey-patches Jasmine so that the Spec correctly reports the stacktrace of an error",
    "test"
  ],
  [
    "bootstrap monkeypatched src/bootstrap.ts~bootstrap,bootstrap src/monkeypatched.ts~monkeypatched,monkeypatched",
    "test-file/spec/monkeyPatched.spec.ts.html#lineNumber53",
    "@serenity-js/jasmine monkey-patches Jasmine so that the Spec defaults to an unknown location if the real one could not be determined",
    "test"
  ],
  [
    "bootstrap monkeypatched src/bootstrap.ts~bootstrap,bootstrap src/monkeypatched.ts~monkeypatched,monkeypatched",
    "test-file/spec/monkeyPatched.spec.ts.html#lineNumber68",
    "@serenity-js/jasmine monkey-patches Jasmine so that the Spec has all the static members of the original constructor function",
    "test"
  ],
  [
    "bootstrap monkeypatched src/bootstrap.ts~bootstrap,bootstrap src/monkeypatched.ts~monkeypatched,monkeypatched",
    "test-file/spec/monkeyPatched.spec.ts.html#lineNumber81",
    "@serenity-js/jasmine monkey-patches Jasmine so that the Spec has all the static members of the original constructor function",
    "test"
  ],
  [
    "",
    "test-file/spec/monkeyPatched.spec.ts.html#lineNumber105",
    "@serenity-js/jasmine monkey-patches Jasmine so that the Suite",
    "test"
  ],
  [
    "",
    "test-file/spec/monkeyPatched.spec.ts.html#lineNumber122",
    "@serenity-js/jasmine monkey-patches Jasmine so that the Suite correctly reports the stacktrace of an error",
    "test"
  ],
  [
    "bootstrap monkeypatched src/bootstrap.ts~bootstrap,bootstrap src/monkeypatched.ts~monkeypatched,monkeypatched",
    "test-file/spec/monkeyPatched.spec.ts.html#lineNumber111",
    "@serenity-js/jasmine monkey-patches Jasmine so that the Suite defaults to an unknown location if the real one could not be determined",
    "test"
  ],
  [
    "axioserror",
    "https://github.com/axios/axios/blob/v0.19.2/index.d.ts#L82",
    "AxiosError",
    "external"
  ],
  [
    "axiosinstance",
    "https://github.com/axios/axios/blob/v0.19.2/index.d.ts#L127",
    "AxiosInstance",
    "external"
  ],
  [
    "axiospromise",
    "https://github.com/axios/axios/blob/v0.19.2/index.d.ts#L91",
    "AxiosPromise",
    "external"
  ],
  [
    "axiosrequestconfig",
    "https://github.com/axios/axios/blob/v0.19.2/index.d.ts#L43",
    "AxiosRequestConfig",
    "external"
  ],
  [
    "axiosresponse",
    "https://github.com/axios/axios/blob/v0.19.2/index.d.ts#L73",
    "AxiosResponse",
    "external"
  ],
  [
    "elementarrayfinder",
    "https://www.protractortest.org/#/api?view=ElementArrayFinder",
    "ElementArrayFinder",
    "external"
  ],
  [
    "elementfinder",
    "https://www.protractortest.org/#/api?view=ElementFinder",
    "ElementFinder",
    "external"
  ],
  [
    "* *,*",
    "test-file/spec/adapter/JasmineAdapter.spec.ts.html#lineNumber8",
    "JasmineAdapter",
    "test"
  ],
  [
    "* *,*",
    "test-file/spec/adapter/JasmineAdapter.spec.ts.html#lineNumber62",
    "JasmineAdapter configures the default timeout interval if required",
    "test"
  ],
  [
    "* *,*",
    "test-file/spec/adapter/JasmineAdapter.spec.ts.html#lineNumber42",
    "JasmineAdapter defaults to running tests sequentially rather than in a random order",
    "test"
  ],
  [
    "protractorbrowser",
    "https://www.protractortest.org/#/api?view=ProtractorBrowser",
    "ProtractorBrowser",
    "external"
  ],
  [
    "serenityreporterforjasmine src/serenityreporterforjasmine.ts~serenityreporterforjasmine,serenityreporterforjasmine",
    "test-file/spec/SerenityReporterForJasmine.spec.ts.html#lineNumber31",
    "SerenityReporterForJasmine",
    "test"
  ],
  [
    "",
    "test-file/spec/SerenityReporterForJasmine.spec.ts.html#lineNumber47",
    "SerenityReporterForJasmine notifies Serenity when",
    "test"
  ],
  [
    "",
    "test-file/spec/SerenityReporterForJasmine.spec.ts.html#lineNumber663",
    "SerenityReporterForJasmine notifies Serenity when the `it` block is not nested within a `describe` block and",
    "test"
  ],
  [
    "serenityreporterforjasmine#specstarted serenityreporterforjasmine#specdone src/serenityreporterforjasmine.ts~serenityreporterforjasmine#specstarted,serenityreporterforjasmine#specstarted src/serenityreporterforjasmine.ts~serenityreporterforjasmine#specdone,serenityreporterforjasmine#specdone",
    "test-file/spec/SerenityReporterForJasmine.spec.ts.html#lineNumber719",
    "SerenityReporterForJasmine notifies Serenity when the `it` block is not nested within a `describe` block and correctly derives the name of the spec",
    "test"
  ],
  [
    "serenityreporterforjasmine#specstarted serenityreporterforjasmine#specdone src/serenityreporterforjasmine.ts~serenityreporterforjasmine#specstarted,serenityreporterforjasmine#specstarted src/serenityreporterforjasmine.ts~serenityreporterforjasmine#specdone,serenityreporterforjasmine#specdone",
    "test-file/spec/SerenityReporterForJasmine.spec.ts.html#lineNumber710",
    "SerenityReporterForJasmine notifies Serenity when the `it` block is not nested within a `describe` block and tags the feature as \"unknown\"",
    "test"
  ],
  [
    "",
    "test-file/spec/SerenityReporterForJasmine.spec.ts.html#lineNumber49",
    "SerenityReporterForJasmine notifies Serenity when the test run",
    "test"
  ],
  [
    "serenityreporterforjasmine#jasminedone src/serenityreporterforjasmine.ts~serenityreporterforjasmine#jasminedone,serenityreporterforjasmine#jasminedone",
    "test-file/spec/SerenityReporterForJasmine.spec.ts.html#lineNumber51",
    "SerenityReporterForJasmine notifies Serenity when the test run ends",
    "test"
  ],
  [
    "",
    "test-file/spec/SerenityReporterForJasmine.spec.ts.html#lineNumber266",
    "SerenityReporterForJasmine notifies Serenity when the test spec",
    "test"
  ],
  [
    "",
    "test-file/spec/SerenityReporterForJasmine.spec.ts.html#lineNumber404",
    "SerenityReporterForJasmine notifies Serenity when the test spec ends and",
    "test"
  ],
  [
    "",
    "test-file/spec/SerenityReporterForJasmine.spec.ts.html#lineNumber498",
    "SerenityReporterForJasmine notifies Serenity when the test spec ends and as compromised",
    "test"
  ],
  [
    "serenityreporterforjasmine#specdone src/serenityreporterforjasmine.ts~serenityreporterforjasmine#specdone,serenityreporterforjasmine#specdone",
    "test-file/spec/SerenityReporterForJasmine.spec.ts.html#lineNumber423",
    "SerenityReporterForJasmine notifies Serenity when the test spec ends and has been excluded",
    "test"
  ],
  [
    "serenityreporterforjasmine#specdone src/serenityreporterforjasmine.ts~serenityreporterforjasmine#specdone,serenityreporterforjasmine#specdone",
    "test-file/spec/SerenityReporterForJasmine.spec.ts.html#lineNumber562",
    "SerenityReporterForJasmine notifies Serenity when the test spec ends and has failed with an assertion error",
    "test"
  ],
  [
    "serenityreporterforjasmine#specdone src/serenityreporterforjasmine.ts~serenityreporterforjasmine#specdone,serenityreporterforjasmine#specdone",
    "test-file/spec/SerenityReporterForJasmine.spec.ts.html#lineNumber469",
    "SerenityReporterForJasmine notifies Serenity when the test spec ends and has failed with an error",
    "test"
  ],
  [
    "serenityreporterforjasmine#specdone src/serenityreporterforjasmine.ts~serenityreporterforjasmine#specdone,serenityreporterforjasmine#specdone",
    "test-file/spec/SerenityReporterForJasmine.spec.ts.html#lineNumber596",
    "SerenityReporterForJasmine notifies Serenity when the test spec ends and has failed with multiple errors",
    "test"
  ],
  [
    "serenityreporterforjasmine#specdone src/serenityreporterforjasmine.ts~serenityreporterforjasmine#specdone,serenityreporterforjasmine#specdone",
    "test-file/spec/SerenityReporterForJasmine.spec.ts.html#lineNumber530",
    "SerenityReporterForJasmine notifies Serenity when the test spec ends and has failed with no stack trace",
    "test"
  ],
  [
    "serenityreporterforjasmine#specdone src/serenityreporterforjasmine.ts~serenityreporterforjasmine#specdone,serenityreporterforjasmine#specdone",
    "test-file/spec/SerenityReporterForJasmine.spec.ts.html#lineNumber444",
    "SerenityReporterForJasmine notifies Serenity when the test spec ends and is marked as pending",
    "test"
  ],
  [
    "",
    "test-file/spec/SerenityReporterForJasmine.spec.ts.html#lineNumber268",
    "SerenityReporterForJasmine notifies Serenity when the test spec starts and",
    "test"
  ],
  [
    "serenityreporterforjasmine#suitestarted serenityreporterforjasmine#suitedone serenityreporterforjasmine#specstarted serenityreporterforjasmine#specdone src/serenityreporterforjasmine.ts~serenityreporterforjasmine#suitestarted,serenityreporterforjasmine#suitestarted src/serenityreporterforjasmine.ts~serenityreporterforjasmine#suitedone,serenityreporterforjasmine#suitedone src/serenityreporterforjasmine.ts~serenityreporterforjasmine#specstarted,serenityreporterforjasmine#specstarted src/serenityreporterforjasmine.ts~serenityreporterforjasmine#specdone,serenityreporterforjasmine#specdone",
    "test-file/spec/SerenityReporterForJasmine.spec.ts.html#lineNumber387",
    "SerenityReporterForJasmine notifies Serenity when the test spec starts and derives the name of the feature from the outer-most `describe` block",
    "test"
  ],
  [
    "serenityreporterforjasmine#suitestarted serenityreporterforjasmine#suitedone serenityreporterforjasmine#specstarted serenityreporterforjasmine#specdone src/serenityreporterforjasmine.ts~serenityreporterforjasmine#suitestarted,serenityreporterforjasmine#suitestarted src/serenityreporterforjasmine.ts~serenityreporterforjasmine#suitedone,serenityreporterforjasmine#suitedone src/serenityreporterforjasmine.ts~serenityreporterforjasmine#specstarted,serenityreporterforjasmine#specstarted src/serenityreporterforjasmine.ts~serenityreporterforjasmine#specdone,serenityreporterforjasmine#specdone",
    "test-file/spec/SerenityReporterForJasmine.spec.ts.html#lineNumber375",
    "SerenityReporterForJasmine notifies Serenity when the test spec starts and derives the name of the scenario from the nested `describe` blocks",
    "test"
  ],
  [
    "serenityreporterforjasmine#suitestarted serenityreporterforjasmine#suitedone serenityreporterforjasmine#specstarted serenityreporterforjasmine#specdone src/serenityreporterforjasmine.ts~serenityreporterforjasmine#suitestarted,serenityreporterforjasmine#suitestarted src/serenityreporterforjasmine.ts~serenityreporterforjasmine#suitedone,serenityreporterforjasmine#suitedone src/serenityreporterforjasmine.ts~serenityreporterforjasmine#specstarted,serenityreporterforjasmine#specstarted src/serenityreporterforjasmine.ts~serenityreporterforjasmine#specdone,serenityreporterforjasmine#specdone",
    "test-file/spec/SerenityReporterForJasmine.spec.ts.html#lineNumber398",
    "SerenityReporterForJasmine notifies Serenity when the test spec starts and detects the test runner",
    "test"
  ],
  [
    "",
    "test-file/spec/SerenityReporterForJasmine.spec.ts.html#lineNumber69",
    "SerenityReporterForJasmine notifies Serenity when the test suite",
    "test"
  ],
  [
    "serenityreporterforjasmine#suitestarted serenityreporterforjasmine#suitedone src/serenityreporterforjasmine.ts~serenityreporterforjasmine#suitestarted,serenityreporterforjasmine#suitestarted src/serenityreporterforjasmine.ts~serenityreporterforjasmine#suitedone,serenityreporterforjasmine#suitedone",
    "test-file/spec/SerenityReporterForJasmine.spec.ts.html#lineNumber107",
    "SerenityReporterForJasmine notifies Serenity when the test suite ends",
    "test"
  ],
  [
    "serenityreporterforjasmine#suitestarted serenityreporterforjasmine#suitedone src/serenityreporterforjasmine.ts~serenityreporterforjasmine#suitestarted,serenityreporterforjasmine#suitestarted src/serenityreporterforjasmine.ts~serenityreporterforjasmine#suitedone,serenityreporterforjasmine#suitedone",
    "test-file/spec/SerenityReporterForJasmine.spec.ts.html#lineNumber160",
    "SerenityReporterForJasmine notifies Serenity when the test suite ends with an error, reporting the first error that has occurred",
    "test"
  ],
  [
    "serenityreporterforjasmine#suitestarted serenityreporterforjasmine#suitedone src/serenityreporterforjasmine.ts~serenityreporterforjasmine#suitestarted,serenityreporterforjasmine#suitestarted src/serenityreporterforjasmine.ts~serenityreporterforjasmine#suitedone,serenityreporterforjasmine#suitedone",
    "test-file/spec/SerenityReporterForJasmine.spec.ts.html#lineNumber225",
    "SerenityReporterForJasmine notifies Serenity when the test suite is pending",
    "test"
  ],
  [
    "serenityreporterforjasmine#suitestarted src/serenityreporterforjasmine.ts~serenityreporterforjasmine#suitestarted,serenityreporterforjasmine#suitestarted",
    "test-file/spec/SerenityReporterForJasmine.spec.ts.html#lineNumber72",
    "SerenityReporterForJasmine notifies Serenity when the test suite starts",
    "test"
  ],
  [
    "selenium-webdriver~actions",
    "https://www.selenium.dev/selenium/docs/api/javascript/module/selenium-webdriver/lib/input_exports_Actions.html",
    "selenium-webdriver~Actions",
    "external"
  ],
  [
    "selenium-webdriver~alertpromise",
    "https://www.selenium.dev/selenium/docs/api/javascript/module/selenium-webdriver/lib/webdriver_exports_AlertPromise.html",
    "selenium-webdriver~AlertPromise",
    "external"
  ],
  [
    "selenium-webdriver~by",
    "https://www.selenium.dev/selenium/docs/api/javascript/module/selenium-webdriver/lib/by_exports_By.html",
    "selenium-webdriver~By",
    "external"
  ],
  [
    "selenium-webdriver~capabilities",
    "https://www.selenium.dev/selenium/docs/api/javascript/module/selenium-webdriver/index_exports_Capabilities.html",
    "selenium-webdriver~Capabilities",
    "external"
  ],
  [
    "selenium-webdriver~navigation",
    "https://www.selenium.dev/selenium/docs/api/javascript/module/selenium-webdriver/lib/webdriver_exports_Navigation.html",
    "selenium-webdriver~Navigation",
    "external"
  ],
  [
    "selenium-webdriver~options",
    "https://www.selenium.dev/selenium/docs/api/javascript/module/selenium-webdriver/ie_exports_Options.html",
    "selenium-webdriver~Options",
    "external"
  ],
  [
    "spec/serenityreporterforjasmine.spec.ts",
    "test-file/spec/SerenityReporterForJasmine.spec.ts.html",
    "spec/SerenityReporterForJasmine.spec.ts",
    "testFile"
  ],
  [
    "spec/adapter/jasmineadapter.spec.ts",
    "test-file/spec/adapter/JasmineAdapter.spec.ts.html",
    "spec/adapter/JasmineAdapter.spec.ts",
    "testFile"
  ],
  [
    "spec/monkeypatched.spec.ts",
    "test-file/spec/monkeyPatched.spec.ts.html",
    "spec/monkeyPatched.spec.ts",
    "testFile"
  ],
  [
    "src/serenityreporterforjasmine.ts",
    "file/src/SerenityReporterForJasmine.ts.html",
    "src/SerenityReporterForJasmine.ts",
    "file"
  ],
  [
    "src/serenityreporterforjasmine.ts~serenityreporterforjasmine#constructor",
    "class/src/SerenityReporterForJasmine.ts~SerenityReporterForJasmine.html#instance-constructor-constructor",
    "src/SerenityReporterForJasmine.ts~SerenityReporterForJasmine#constructor",
    "method"
  ],
  [
    "src/serenityreporterforjasmine.ts~serenityreporterforjasmine#jasminedone",
    "class/src/SerenityReporterForJasmine.ts~SerenityReporterForJasmine.html#instance-method-jasmineDone",
    "src/SerenityReporterForJasmine.ts~SerenityReporterForJasmine#jasmineDone",
    "method"
  ],
  [
    "src/serenityreporterforjasmine.ts~serenityreporterforjasmine#specdone",
    "class/src/SerenityReporterForJasmine.ts~SerenityReporterForJasmine.html#instance-method-specDone",
    "src/SerenityReporterForJasmine.ts~SerenityReporterForJasmine#specDone",
    "method"
  ],
  [
    "src/serenityreporterforjasmine.ts~serenityreporterforjasmine#specstarted",
    "class/src/SerenityReporterForJasmine.ts~SerenityReporterForJasmine.html#instance-method-specStarted",
    "src/SerenityReporterForJasmine.ts~SerenityReporterForJasmine#specStarted",
    "method"
  ],
  [
    "src/serenityreporterforjasmine.ts~serenityreporterforjasmine#suitedone",
    "class/src/SerenityReporterForJasmine.ts~SerenityReporterForJasmine.html#instance-method-suiteDone",
    "src/SerenityReporterForJasmine.ts~SerenityReporterForJasmine#suiteDone",
    "method"
  ],
  [
    "src/serenityreporterforjasmine.ts~serenityreporterforjasmine#suitestarted",
    "class/src/SerenityReporterForJasmine.ts~SerenityReporterForJasmine.html#instance-method-suiteStarted",
    "src/SerenityReporterForJasmine.ts~SerenityReporterForJasmine#suiteStarted",
    "method"
  ],
  [
    "src/adapter/jasmineadapter.ts",
    "file/src/adapter/JasmineAdapter.ts.html",
    "src/adapter/JasmineAdapter.ts",
    "file"
  ],
  [
    "src/adapter/jasmineadapter.ts~jasmineadapter#constructor",
    "class/src/adapter/JasmineAdapter.ts~JasmineAdapter.html#instance-constructor-constructor",
    "src/adapter/JasmineAdapter.ts~JasmineAdapter#constructor",
    "method"
  ],
  [
    "src/adapter/jasmineadapter.ts~jasmineadapter#run",
    "class/src/adapter/JasmineAdapter.ts~JasmineAdapter.html#instance-method-run",
    "src/adapter/JasmineAdapter.ts~JasmineAdapter#run",
    "method"
  ],
  [
    "src/adapter/jasmineconfig.ts",
    "file/src/adapter/JasmineConfig.ts.html",
    "src/adapter/JasmineConfig.ts",
    "file"
  ],
  [
    "src/adapter/jasmineconfig.ts~jasmineconfig#defaulttimeoutinterval",
    "class/src/adapter/JasmineConfig.ts~JasmineConfig.html#instance-member-defaultTimeoutInterval",
    "src/adapter/JasmineConfig.ts~JasmineConfig#defaultTimeoutInterval",
    "member"
  ],
  [
    "src/adapter/jasmineconfig.ts~jasmineconfig#grep",
    "class/src/adapter/JasmineConfig.ts~JasmineConfig.html#instance-member-grep",
    "src/adapter/JasmineConfig.ts~JasmineConfig#grep",
    "member"
  ],
  [
    "src/adapter/jasmineconfig.ts~jasmineconfig#helpers",
    "class/src/adapter/JasmineConfig.ts~JasmineConfig.html#instance-member-helpers",
    "src/adapter/JasmineConfig.ts~JasmineConfig#helpers",
    "member"
  ],
  [
    "src/adapter/jasmineconfig.ts~jasmineconfig#random",
    "class/src/adapter/JasmineConfig.ts~JasmineConfig.html#instance-member-random",
    "src/adapter/JasmineConfig.ts~JasmineConfig#random",
    "member"
  ],
  [
    "src/adapter/jasmineconfig.ts~jasmineconfig#requires",
    "class/src/adapter/JasmineConfig.ts~JasmineConfig.html#instance-member-requires",
    "src/adapter/JasmineConfig.ts~JasmineConfig#requires",
    "member"
  ],
  [
    "src/adapter/jasmineconfig.ts~jasmineconfig#seed",
    "class/src/adapter/JasmineConfig.ts~JasmineConfig.html#instance-member-seed",
    "src/adapter/JasmineConfig.ts~JasmineConfig#seed",
    "member"
  ],
  [
    "src/adapter/index.ts",
    "file/src/adapter/index.ts.html",
    "src/adapter/index.ts",
    "file"
  ],
  [
    "src/bootstrap.ts",
    "file/src/bootstrap.ts.html",
    "src/bootstrap.ts",
    "file"
  ],
  [
    "src/index.ts",
    "file/src/index.ts.html",
    "src/index.ts",
    "file"
  ],
  [
    "src/jasmine/expectation.ts",
    "file/src/jasmine/Expectation.ts.html",
    "src/jasmine/Expectation.ts",
    "file"
  ],
  [
    "src/jasmine/jasminedoneinfo.ts",
    "file/src/jasmine/JasmineDoneInfo.ts.html",
    "src/jasmine/JasmineDoneInfo.ts",
    "file"
  ],
  [
    "src/jasmine/jasminestartedinfo.ts",
    "file/src/jasmine/JasmineStartedInfo.ts.html",
    "src/jasmine/JasmineStartedInfo.ts",
    "file"
  ],
  [
    "src/jasmine/location.ts",
    "file/src/jasmine/Location.ts.html",
    "src/jasmine/Location.ts",
    "file"
  ],
  [
    "src/jasmine/order.ts",
    "file/src/jasmine/Order.ts.html",
    "src/jasmine/Order.ts",
    "file"
  ],
  [
    "src/jasmine/result.ts",
    "file/src/jasmine/Result.ts.html",
    "src/jasmine/Result.ts",
    "file"
  ],
  [
    "src/jasmine/specresult.ts",
    "file/src/jasmine/SpecResult.ts.html",
    "src/jasmine/SpecResult.ts",
    "file"
  ],
  [
    "src/jasmine/suiteresult.ts",
    "file/src/jasmine/SuiteResult.ts.html",
    "src/jasmine/SuiteResult.ts",
    "file"
  ],
  [
    "src/jasmine/index.ts",
    "file/src/jasmine/index.ts.html",
    "src/jasmine/index.ts",
    "file"
  ],
  [
    "src/monkeypatched.ts",
    "file/src/monkeyPatched.ts.html",
    "src/monkeyPatched.ts",
    "file"
  ]
]