window.esdocSearchIndex = [
  [
    "@serenity-js/local-server/lib/screenplay/questions~localserver",
    "class/src/screenplay/questions/LocalServer.ts~LocalServer.html",
    "<span>LocalServer</span> <span class=\"search-result-import-path\">@serenity-js/local-server/lib/screenplay/questions</span>",
    "class"
  ],
  [
    "@serenity-js/local-server/lib/screenplay/abilities~managealocalserver",
    "class/src/screenplay/abilities/ManageALocalServer.ts~ManageALocalServer.html",
    "<span>ManageALocalServer</span> <span class=\"search-result-import-path\">@serenity-js/local-server/lib/screenplay/abilities</span>",
    "class"
  ],
  [
    "@serenity-js/local-server/lib/screenplay/interactions~startlocalserver",
    "class/src/screenplay/interactions/StartLocalServer.ts~StartLocalServer.html",
    "<span>StartLocalServer</span> <span class=\"search-result-import-path\">@serenity-js/local-server/lib/screenplay/interactions</span>",
    "class"
  ],
  [
    "@serenity-js/local-server/lib/screenplay/interactions~stoplocalserver",
    "class/src/screenplay/interactions/StopLocalServer.ts~StopLocalServer.html",
    "<span>StopLocalServer</span> <span class=\"search-result-import-path\">@serenity-js/local-server/lib/screenplay/interactions</span>",
    "class"
  ],
  [
    "@serenity-js/assertions/lib/expectations~and",
    "/modules/assertions/function/src/expectations/and.ts~and.html",
    "@serenity-js/assertions/lib/expectations~and",
    "external"
  ],
  [
    "@serenity-js/assertions/lib/expectations~contain",
    "/modules/assertions/function/src/expectations/contain.ts~contain.html",
    "@serenity-js/assertions/lib/expectations~contain",
    "external"
  ],
  [
    "@serenity-js/assertions/lib/expectations~containatleastoneitemthat",
    "/modules/assertions/function/src/expectations/containAtLeastOneItemThat.ts~containAtLeastOneItemThat.html",
    "@serenity-js/assertions/lib/expectations~containAtLeastOneItemThat",
    "external"
  ],
  [
    "@serenity-js/assertions/lib/expectations~containitemswhereeachitem",
    "/modules/assertions/function/src/expectations/containItemsWhereEachItem.ts~containItemsWhereEachItem.html",
    "@serenity-js/assertions/lib/expectations~containItemsWhereEachItem",
    "external"
  ],
  [
    "@serenity-js/assertions/lib/expectations~endswith",
    "/modules/assertions/function/src/expectations/endsWith.ts~endsWith.html",
    "@serenity-js/assertions/lib/expectations~endsWith",
    "external"
  ],
  [
    "@serenity-js/assertions/lib/expectations~equals",
    "/modules/assertions/function/src/expectations/equals.ts~equals.html",
    "@serenity-js/assertions/lib/expectations~equals",
    "external"
  ],
  [
    "@serenity-js/assertions/lib/expectations~includes",
    "/modules/assertions/function/src/expectations/includes.ts~includes.html",
    "@serenity-js/assertions/lib/expectations~includes",
    "external"
  ],
  [
    "@serenity-js/assertions/lib/expectations~isafter",
    "/modules/assertions/function/src/expectations/isAfter.ts~isAfter.html",
    "@serenity-js/assertions/lib/expectations~isAfter",
    "external"
  ],
  [
    "@serenity-js/assertions/lib/expectations~isbefore",
    "/modules/assertions/function/src/expectations/isBefore.ts~isBefore.html",
    "@serenity-js/assertions/lib/expectations~isBefore",
    "external"
  ],
  [
    "@serenity-js/assertions/lib/expectations~isfalse",
    "/modules/assertions/function/src/expectations/isFalse.ts~isFalse.html",
    "@serenity-js/assertions/lib/expectations~isFalse",
    "external"
  ],
  [
    "@serenity-js/assertions/lib/expectations~isgreaterthan",
    "/modules/assertions/function/src/expectations/isGreaterThan.ts~isGreaterThan.html",
    "@serenity-js/assertions/lib/expectations~isGreaterThan",
    "external"
  ],
  [
    "@serenity-js/assertions/lib/expectations~islessthan",
    "/modules/assertions/function/src/expectations/isLessThan.ts~isLessThan.html",
    "@serenity-js/assertions/lib/expectations~isLessThan",
    "external"
  ],
  [
    "@serenity-js/assertions/lib/expectations~istrue",
    "/modules/assertions/function/src/expectations/isTrue.ts~isTrue.html",
    "@serenity-js/assertions/lib/expectations~isTrue",
    "external"
  ],
  [
    "@serenity-js/assertions/lib/expectations~matches",
    "/modules/assertions/function/src/expectations/matches.ts~matches.html",
    "@serenity-js/assertions/lib/expectations~matches",
    "external"
  ],
  [
    "@serenity-js/assertions/lib/expectations~not",
    "/modules/assertions/function/src/expectations/not.ts~not.html",
    "@serenity-js/assertions/lib/expectations~not",
    "external"
  ],
  [
    "@serenity-js/assertions/lib/expectations~or",
    "/modules/assertions/function/src/expectations/or.ts~or.html",
    "@serenity-js/assertions/lib/expectations~or",
    "external"
  ],
  [
    "@serenity-js/assertions/lib/expectations~property",
    "/modules/assertions/function/src/expectations/property.ts~property.html",
    "@serenity-js/assertions/lib/expectations~property",
    "external"
  ],
  [
    "@serenity-js/assertions/lib/expectations~startswith",
    "/modules/assertions/function/src/expectations/startsWith.ts~startsWith.html",
    "@serenity-js/assertions/lib/expectations~startsWith",
    "external"
  ],
  [
    "@serenity-js/assertions~check",
    "/modules/assertions/class/src/Check.ts~Check.html",
    "@serenity-js/assertions~Check",
    "external"
  ],
  [
    "@serenity-js/assertions~ensure",
    "/modules/assertions/class/src/Ensure.ts~Ensure.html",
    "@serenity-js/assertions~Ensure",
    "external"
  ],
  [
    "@serenity-js/assertions~expectation",
    "/modules/assertions/class/src/Expectation.ts~Expectation.html",
    "@serenity-js/assertions~Expectation",
    "external"
  ],
  [
    "@serenity-js/assertions~expectationmet",
    "/modules/assertions/class/src/outcomes.ts~ExpectationMet.html",
    "@serenity-js/assertions~ExpectationMet",
    "external"
  ],
  [
    "@serenity-js/assertions~expectationnotmet",
    "/modules/assertions/class/src/outcomes.ts~ExpectationNotMet.html",
    "@serenity-js/assertions~ExpectationNotMet",
    "external"
  ],
  [
    "@serenity-js/assertions~outcome",
    "/modules/assertions/class/src/outcomes.ts~Outcome.html",
    "@serenity-js/assertions~Outcome",
    "external"
  ],
  [
    "@serenity-js/core/lib/errors~assertionerror",
    "/modules/core/class/src/errors/AssertionError.ts~AssertionError.html",
    "@serenity-js/core/lib/errors~AssertionError",
    "external"
  ],
  [
    "@serenity-js/core/lib/errors~configurationerror",
    "/modules/core/class/src/errors/ConfigurationError.ts~ConfigurationError.html",
    "@serenity-js/core/lib/errors~ConfigurationError",
    "external"
  ],
  [
    "@serenity-js/core/lib/errors~implementationpendingerror",
    "/modules/core/class/src/errors/ImplementationPendingError.ts~ImplementationPendingError.html",
    "@serenity-js/core/lib/errors~ImplementationPendingError",
    "external"
  ],
  [
    "@serenity-js/core/lib/errors~logicerror",
    "/modules/core/class/src/errors/LogicError.ts~LogicError.html",
    "@serenity-js/core/lib/errors~LogicError",
    "external"
  ],
  [
    "@serenity-js/core/lib/errors~runtimeerror",
    "/modules/core/class/src/errors/RuntimeError.ts~RuntimeError.html",
    "@serenity-js/core/lib/errors~RuntimeError",
    "external"
  ],
  [
    "@serenity-js/core/lib/errors~testcompromisederror",
    "/modules/core/class/src/errors/TestCompromisedError.ts~TestCompromisedError.html",
    "@serenity-js/core/lib/errors~TestCompromisedError",
    "external"
  ],
  [
    "@serenity-js/core/lib/errors~unknownerror",
    "/modules/core/class/src/errors/UnknownError.ts~UnknownError.html",
    "@serenity-js/core/lib/errors~UnknownError",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~activityfinished",
    "/modules/core/class/src/events/ActivityFinished.ts~ActivityFinished.html",
    "@serenity-js/core/lib/events~ActivityFinished",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~activityrelatedartifactarchived",
    "/modules/core/class/src/events/ActivityRelatedArtifactArchived.ts~ActivityRelatedArtifactArchived.html",
    "@serenity-js/core/lib/events~ActivityRelatedArtifactArchived",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~activityrelatedartifactgenerated",
    "/modules/core/class/src/events/ActivityRelatedArtifactGenerated.ts~ActivityRelatedArtifactGenerated.html",
    "@serenity-js/core/lib/events~ActivityRelatedArtifactGenerated",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~activitystarts",
    "/modules/core/class/src/events/ActivityStarts.ts~ActivityStarts.html",
    "@serenity-js/core/lib/events~ActivityStarts",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~artifactarchived",
    "/modules/core/class/src/events/ArtifactArchived.ts~ArtifactArchived.html",
    "@serenity-js/core/lib/events~ArtifactArchived",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~artifactgenerated",
    "/modules/core/class/src/events/ArtifactGenerated.ts~ArtifactGenerated.html",
    "@serenity-js/core/lib/events~ArtifactGenerated",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~asyncoperationattempted",
    "/modules/core/class/src/events/AsyncOperationAttempted.ts~AsyncOperationAttempted.html",
    "@serenity-js/core/lib/events~AsyncOperationAttempted",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~asyncoperationcompleted",
    "/modules/core/class/src/events/AsyncOperationCompleted.ts~AsyncOperationCompleted.html",
    "@serenity-js/core/lib/events~AsyncOperationCompleted",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~asyncoperationfailed",
    "/modules/core/class/src/events/AsyncOperationFailed.ts~AsyncOperationFailed.html",
    "@serenity-js/core/lib/events~AsyncOperationFailed",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~domainevent",
    "/modules/core/class/src/events/DomainEvent.ts~DomainEvent.html",
    "@serenity-js/core/lib/events~DomainEvent",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~featurenarrativedetected",
    "/modules/core/class/src/events/FeatureNarrativeDetected.ts~FeatureNarrativeDetected.html",
    "@serenity-js/core/lib/events~FeatureNarrativeDetected",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~interactionfinished",
    "/modules/core/class/src/events/InteractionFinished.ts~InteractionFinished.html",
    "@serenity-js/core/lib/events~InteractionFinished",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~interactionstarts",
    "/modules/core/class/src/events/InteractionStarts.ts~InteractionStarts.html",
    "@serenity-js/core/lib/events~InteractionStarts",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~scenebackgrounddetected",
    "/modules/core/class/src/events/SceneBackgroundDetected.ts~SceneBackgroundDetected.html",
    "@serenity-js/core/lib/events~SceneBackgroundDetected",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~scenedescriptiondetected",
    "/modules/core/class/src/events/SceneDescriptionDetected.ts~SceneDescriptionDetected.html",
    "@serenity-js/core/lib/events~SceneDescriptionDetected",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~scenefinished",
    "/modules/core/class/src/events/SceneFinished.ts~SceneFinished.html",
    "@serenity-js/core/lib/events~SceneFinished",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~scenefinishes",
    "/modules/core/class/src/events/SceneFinishes.ts~SceneFinishes.html",
    "@serenity-js/core/lib/events~SceneFinishes",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~sceneparametersdetected",
    "/modules/core/class/src/events/SceneParametersDetected.ts~SceneParametersDetected.html",
    "@serenity-js/core/lib/events~SceneParametersDetected",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~scenesequencedetected",
    "/modules/core/class/src/events/SceneSequenceDetected.ts~SceneSequenceDetected.html",
    "@serenity-js/core/lib/events~SceneSequenceDetected",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~scenestarts",
    "/modules/core/class/src/events/SceneStarts.ts~SceneStarts.html",
    "@serenity-js/core/lib/events~SceneStarts",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~scenetagged",
    "/modules/core/class/src/events/SceneTagged.ts~SceneTagged.html",
    "@serenity-js/core/lib/events~SceneTagged",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~scenetemplatedetected",
    "/modules/core/class/src/events/SceneTemplateDetected.ts~SceneTemplateDetected.html",
    "@serenity-js/core/lib/events~SceneTemplateDetected",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~taskfinished",
    "/modules/core/class/src/events/TaskFinished.ts~TaskFinished.html",
    "@serenity-js/core/lib/events~TaskFinished",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~taskstarts",
    "/modules/core/class/src/events/TaskStarts.ts~TaskStarts.html",
    "@serenity-js/core/lib/events~TaskStarts",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~testrunfinished",
    "/modules/core/class/src/events/TestRunFinished.ts~TestRunFinished.html",
    "@serenity-js/core/lib/events~TestRunFinished",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~testrunfinishes",
    "/modules/core/class/src/events/TestRunFinishes.ts~TestRunFinishes.html",
    "@serenity-js/core/lib/events~TestRunFinishes",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~testrunnerdetected",
    "/modules/core/class/src/events/TestRunnerDetected.ts~TestRunnerDetected.html",
    "@serenity-js/core/lib/events~TestRunnerDetected",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~testsuitefinished",
    "/modules/core/class/src/events/TestSuiteFinished.ts~TestSuiteFinished.html",
    "@serenity-js/core/lib/events~TestSuiteFinished",
    "external"
  ],
  [
    "@serenity-js/core/lib/events~testsuitestarts",
    "/modules/core/class/src/events/TestSuiteStarts.ts~TestSuiteStarts.html",
    "@serenity-js/core/lib/events~TestSuiteStarts",
    "external"
  ],
  [
    "@serenity-js/core/lib/io/collections~mappable",
    "/modules/core/class/src/io/collections/mappable.ts~Mappable.html",
    "@serenity-js/core/lib/io/collections~Mappable",
    "external"
  ],
  [
    "@serenity-js/core/lib/io/collections~reducible",
    "/modules/core/class/src/io/collections/reducible.ts~Reducible.html",
    "@serenity-js/core/lib/io/collections~Reducible",
    "external"
  ],
  [
    "@serenity-js/core/lib/io/collections~ismappable",
    "/modules/core/function/src/io/collections/mappable.ts~isMappable.html",
    "@serenity-js/core/lib/io/collections~isMappable",
    "external"
  ],
  [
    "@serenity-js/core/lib/io~assertionreportdiffer",
    "/modules/core/class/src/io/AssertionReportDiffer.ts~AssertionReportDiffer.html",
    "@serenity-js/core/lib/io~AssertionReportDiffer",
    "external"
  ],
  [
    "@serenity-js/core/lib/io~errorserialiser",
    "/modules/core/class/src/io/ErrorSerialiser.ts~ErrorSerialiser.html",
    "@serenity-js/core/lib/io~ErrorSerialiser",
    "external"
  ],
  [
    "@serenity-js/core/lib/io~filesystem",
    "/modules/core/class/src/io/FileSystem.ts~FileSystem.html",
    "@serenity-js/core/lib/io~FileSystem",
    "external"
  ],
  [
    "@serenity-js/core/lib/io~filesystemlocation",
    "/modules/core/class/src/io/FileSystemLocation.ts~FileSystemLocation.html",
    "@serenity-js/core/lib/io~FileSystemLocation",
    "external"
  ],
  [
    "@serenity-js/core/lib/io~moduleloader",
    "/modules/core/class/src/io/ModuleLoader.ts~ModuleLoader.html",
    "@serenity-js/core/lib/io~ModuleLoader",
    "external"
  ],
  [
    "@serenity-js/core/lib/io~path",
    "/modules/core/class/src/io/Path.ts~Path.html",
    "@serenity-js/core/lib/io~Path",
    "external"
  ],
  [
    "@serenity-js/core/lib/io~serialisederror",
    "/modules/core/class/src/io/ErrorSerialiser.ts~SerialisedError.html",
    "@serenity-js/core/lib/io~SerialisedError",
    "external"
  ],
  [
    "@serenity-js/core/lib/io~version",
    "/modules/core/class/src/io/Version.ts~Version.html",
    "@serenity-js/core/lib/io~Version",
    "external"
  ],
  [
    "@serenity-js/core/lib/io~commaseparated",
    "/modules/core/function/src/io/commaSeparated.ts~commaSeparated.html",
    "@serenity-js/core/lib/io~commaSeparated",
    "external"
  ],
  [
    "@serenity-js/core/lib/io~formatted",
    "/modules/core/function/src/io/formatted.ts~formatted.html",
    "@serenity-js/core/lib/io~formatted",
    "external"
  ],
  [
    "@serenity-js/core/lib/io~inspected",
    "/modules/core/function/src/io/inspected.ts~inspected.html",
    "@serenity-js/core/lib/io~inspected",
    "external"
  ],
  [
    "@serenity-js/core/lib/io~trimmed",
    "/modules/core/function/src/io/trimmed.ts~trimmed.html",
    "@serenity-js/core/lib/io~trimmed",
    "external"
  ],
  [
    "@serenity-js/core/lib/model/artifacts~assertionreport",
    "/modules/core/class/src/model/artifacts/AssertionReport.ts~AssertionReport.html",
    "@serenity-js/core/lib/model/artifacts~AssertionReport",
    "external"
  ],
  [
    "@serenity-js/core/lib/model/artifacts~httprequestresponse",
    "/modules/core/class/src/model/artifacts/HTTPRequestResponse.ts~HTTPRequestResponse.html",
    "@serenity-js/core/lib/model/artifacts~HTTPRequestResponse",
    "external"
  ],
  [
    "@serenity-js/core/lib/model/artifacts~jsondata",
    "/modules/core/class/src/model/artifacts/JSONData.ts~JSONData.html",
    "@serenity-js/core/lib/model/artifacts~JSONData",
    "external"
  ],
  [
    "@serenity-js/core/lib/model/artifacts~logentry",
    "/modules/core/class/src/model/artifacts/LogEntry.ts~LogEntry.html",
    "@serenity-js/core/lib/model/artifacts~LogEntry",
    "external"
  ],
  [
    "@serenity-js/core/lib/model/artifacts~photo",
    "/modules/core/class/src/model/artifacts/Photo.ts~Photo.html",
    "@serenity-js/core/lib/model/artifacts~Photo",
    "external"
  ],
  [
    "@serenity-js/core/lib/model/artifacts~requestandresponse",
    "/modules/core/class/src/model/artifacts/HTTPRequestResponse.ts~RequestAndResponse.html",
    "@serenity-js/core/lib/model/artifacts~RequestAndResponse",
    "external"
  ],
  [
    "@serenity-js/core/lib/model/artifacts~testreport",
    "/modules/core/class/src/model/artifacts/TestReport.ts~TestReport.html",
    "@serenity-js/core/lib/model/artifacts~TestReport",
    "external"
  ],
  [
    "@serenity-js/core/lib/model/artifacts~textdata",
    "/modules/core/class/src/model/artifacts/TextData.ts~TextData.html",
    "@serenity-js/core/lib/model/artifacts~TextData",
    "external"
  ],
  [
    "@serenity-js/core/lib/model/tags~arbitrarytag",
    "/modules/core/class/src/model/tags/ArbitraryTag.ts~ArbitraryTag.html",
    "@serenity-js/core/lib/model/tags~ArbitraryTag",
    "external"
  ],
  [
    "@serenity-js/core/lib/model/tags~browsertag",
    "/modules/core/class/src/model/tags/BrowserTag.ts~BrowserTag.html",
    "@serenity-js/core/lib/model/tags~BrowserTag",
    "external"
  ],
  [
    "@serenity-js/core/lib/model/tags~capabilitytag",
    "/modules/core/class/src/model/tags/CapabilityTag.ts~CapabilityTag.html",
    "@serenity-js/core/lib/model/tags~CapabilityTag",
    "external"
  ],
  [
    "@serenity-js/core/lib/model/tags~contexttag",
    "/modules/core/class/src/model/tags/ContextTag.ts~ContextTag.html",
    "@serenity-js/core/lib/model/tags~ContextTag",
    "external"
  ],
  [
    "@serenity-js/core/lib/model/tags~executionretriedtag",
    "/modules/core/class/src/model/tags/ExecutionRetriedTag.ts~ExecutionRetriedTag.html",
    "@serenity-js/core/lib/model/tags~ExecutionRetriedTag",
    "external"
  ],
  [
    "@serenity-js/core/lib/model/tags~featuretag",
    "/modules/core/class/src/model/tags/FeatureTag.ts~FeatureTag.html",
    "@serenity-js/core/lib/model/tags~FeatureTag",
    "external"
  ],
  [
    "@serenity-js/core/lib/model/tags~issuetag",
    "/modules/core/class/src/model/tags/IssueTag.ts~IssueTag.html",
    "@serenity-js/core/lib/model/tags~IssueTag",
    "external"
  ],
  [
    "@serenity-js/core/lib/model/tags~manualtag",
    "/modules/core/class/src/model/tags/ManualTag.ts~ManualTag.html",
    "@serenity-js/core/lib/model/tags~ManualTag",
    "external"
  ],
  [
    "@serenity-js/core/lib/model/tags~platformtag",
    "/modules/core/class/src/model/tags/PlatformTag.ts~PlatformTag.html",
    "@serenity-js/core/lib/model/tags~PlatformTag",
    "external"
  ],
  [
    "@serenity-js/core/lib/model/tags~tag",
    "/modules/core/class/src/model/tags/Tag.ts~Tag.html",
    "@serenity-js/core/lib/model/tags~Tag",
    "external"
  ],
  [
    "@serenity-js/core/lib/model/tags~themetag",
    "/modules/core/class/src/model/tags/ThemeTag.ts~ThemeTag.html",
    "@serenity-js/core/lib/model/tags~ThemeTag",
    "external"
  ],
  [
    "@serenity-js/core/lib/model~activitydetails",
    "/modules/core/class/src/model/ActivityDetails.ts~ActivityDetails.html",
    "@serenity-js/core/lib/model~ActivityDetails",
    "external"
  ],
  [
    "@serenity-js/core/lib/model~artifact",
    "/modules/core/class/src/model/Artifact.ts~Artifact.html",
    "@serenity-js/core/lib/model~Artifact",
    "external"
  ],
  [
    "@serenity-js/core/lib/model~category",
    "/modules/core/class/src/model/Category.ts~Category.html",
    "@serenity-js/core/lib/model~Category",
    "external"
  ],
  [
    "@serenity-js/core/lib/model~correlationid",
    "/modules/core/class/src/model/CorrelationId.ts~CorrelationId.html",
    "@serenity-js/core/lib/model~CorrelationId",
    "external"
  ],
  [
    "@serenity-js/core/lib/model~description",
    "/modules/core/class/src/model/Description.ts~Description.html",
    "@serenity-js/core/lib/model~Description",
    "external"
  ],
  [
    "@serenity-js/core/lib/model~duration",
    "/modules/core/class/src/model/Duration.ts~Duration.html",
    "@serenity-js/core/lib/model~Duration",
    "external"
  ],
  [
    "@serenity-js/core/lib/model~executioncompromised",
    "/modules/core/class/src/model/outcomes.ts~ExecutionCompromised.html",
    "@serenity-js/core/lib/model~ExecutionCompromised",
    "external"
  ],
  [
    "@serenity-js/core/lib/model~executionfailedwithassertionerror",
    "/modules/core/class/src/model/outcomes.ts~ExecutionFailedWithAssertionError.html",
    "@serenity-js/core/lib/model~ExecutionFailedWithAssertionError",
    "external"
  ],
  [
    "@serenity-js/core/lib/model~executionfailedwitherror",
    "/modules/core/class/src/model/outcomes.ts~ExecutionFailedWithError.html",
    "@serenity-js/core/lib/model~ExecutionFailedWithError",
    "external"
  ],
  [
    "@serenity-js/core/lib/model~executionignored",
    "/modules/core/class/src/model/outcomes.ts~ExecutionIgnored.html",
    "@serenity-js/core/lib/model~ExecutionIgnored",
    "external"
  ],
  [
    "@serenity-js/core/lib/model~executionskipped",
    "/modules/core/class/src/model/outcomes.ts~ExecutionSkipped.html",
    "@serenity-js/core/lib/model~ExecutionSkipped",
    "external"
  ],
  [
    "@serenity-js/core/lib/model~executionsuccessful",
    "/modules/core/class/src/model/outcomes.ts~ExecutionSuccessful.html",
    "@serenity-js/core/lib/model~ExecutionSuccessful",
    "external"
  ],
  [
    "@serenity-js/core/lib/model~implementationpending",
    "/modules/core/class/src/model/outcomes.ts~ImplementationPending.html",
    "@serenity-js/core/lib/model~ImplementationPending",
    "external"
  ],
  [
    "@serenity-js/core/lib/model~name",
    "/modules/core/class/src/model/Name.ts~Name.html",
    "@serenity-js/core/lib/model~Name",
    "external"
  ],
  [
    "@serenity-js/core/lib/model~outcome",
    "/modules/core/class/src/model/outcomes.ts~Outcome.html",
    "@serenity-js/core/lib/model~Outcome",
    "external"
  ],
  [
    "@serenity-js/core/lib/model~problemindication",
    "/modules/core/class/src/model/outcomes.ts~ProblemIndication.html",
    "@serenity-js/core/lib/model~ProblemIndication",
    "external"
  ],
  [
    "@serenity-js/core/lib/model~scenariodetails",
    "/modules/core/class/src/model/ScenarioDetails.ts~ScenarioDetails.html",
    "@serenity-js/core/lib/model~ScenarioDetails",
    "external"
  ],
  [
    "@serenity-js/core/lib/model~scenarioparameters",
    "/modules/core/class/src/model/ScenarioParameters.ts~ScenarioParameters.html",
    "@serenity-js/core/lib/model~ScenarioParameters",
    "external"
  ],
  [
    "@serenity-js/core/lib/model~testsuitedetails",
    "/modules/core/class/src/model/TestSuiteDetails.ts~TestSuiteDetails.html",
    "@serenity-js/core/lib/model~TestSuiteDetails",
    "external"
  ],
  [
    "@serenity-js/core/lib/model~timestamp",
    "/modules/core/class/src/model/Timestamp.ts~Timestamp.html",
    "@serenity-js/core/lib/model~Timestamp",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay/abilities~takenotes",
    "/modules/core/class/src/screenplay/abilities/TakeNotes.ts~TakeNotes.html",
    "@serenity-js/core/lib/screenplay/abilities~TakeNotes",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay/actor~actor",
    "/modules/core/class/src/screenplay/actor/Actor.ts~Actor.html",
    "@serenity-js/core/lib/screenplay/actor~Actor",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay/actor~answersquestions",
    "/modules/core/class/src/screenplay/actor/AnswersQuestions.ts~AnswersQuestions.html",
    "@serenity-js/core/lib/screenplay/actor~AnswersQuestions",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay/actor~canhaveabilities",
    "/modules/core/class/src/screenplay/actor/CanHaveAbilities.ts~CanHaveAbilities.html",
    "@serenity-js/core/lib/screenplay/actor~CanHaveAbilities",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay/actor~collectsartifacts",
    "/modules/core/class/src/screenplay/actor/CollectsArtifacts.ts~CollectsArtifacts.html",
    "@serenity-js/core/lib/screenplay/actor~CollectsArtifacts",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay/actor~listenstodomainevents",
    "/modules/core/class/src/screenplay/actor/ListensToDomainEvents.ts~ListensToDomainEvents.html",
    "@serenity-js/core/lib/screenplay/actor~ListensToDomainEvents",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay/actor~performsactivities",
    "/modules/core/class/src/screenplay/actor/PerformsActivities.ts~PerformsActivities.html",
    "@serenity-js/core/lib/screenplay/actor~PerformsActivities",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay/actor~usesabilities",
    "/modules/core/class/src/screenplay/actor/UsesAbilities.ts~UsesAbilities.html",
    "@serenity-js/core/lib/screenplay/actor~UsesAbilities",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay/interactions~log",
    "/modules/core/class/src/screenplay/interactions/Log.ts~Log.html",
    "@serenity-js/core/lib/screenplay/interactions~Log",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay/interactions~see",
    "/modules/core/class/src/screenplay/interactions/See.ts~See.html",
    "@serenity-js/core/lib/screenplay/interactions~See",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay/interactions~takenote",
    "/modules/core/class/src/screenplay/interactions/TakeNote.ts~TakeNote.html",
    "@serenity-js/core/lib/screenplay/interactions~TakeNote",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay/questions/mappings/string~append",
    "/modules/core/function/src/screenplay/questions/mappings/string/append.ts~append.html",
    "@serenity-js/core/lib/screenplay/questions/mappings/string~append",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay/questions/mappings/string~normalize",
    "/modules/core/function/src/screenplay/questions/mappings/string/normalize.ts~normalize.html",
    "@serenity-js/core/lib/screenplay/questions/mappings/string~normalize",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay/questions/mappings/string~replace",
    "/modules/core/function/src/screenplay/questions/mappings/string/replace.ts~replace.html",
    "@serenity-js/core/lib/screenplay/questions/mappings/string~replace",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay/questions/mappings/string~slice",
    "/modules/core/function/src/screenplay/questions/mappings/string/slice.ts~slice.html",
    "@serenity-js/core/lib/screenplay/questions/mappings/string~slice",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay/questions/mappings/string~split",
    "/modules/core/function/src/screenplay/questions/mappings/string/split.ts~split.html",
    "@serenity-js/core/lib/screenplay/questions/mappings/string~split",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay/questions/mappings/string~tolocalelowercase",
    "/modules/core/function/src/screenplay/questions/mappings/string/toLocaleLowerCase.ts~toLocaleLowerCase.html",
    "@serenity-js/core/lib/screenplay/questions/mappings/string~toLocaleLowerCase",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay/questions/mappings/string~tolocaleuppercase",
    "/modules/core/function/src/screenplay/questions/mappings/string/toLocaleUpperCase.ts~toLocaleUpperCase.html",
    "@serenity-js/core/lib/screenplay/questions/mappings/string~toLocaleUpperCase",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay/questions/mappings/string~tolowercase",
    "/modules/core/function/src/screenplay/questions/mappings/string/toLowerCase.ts~toLowerCase.html",
    "@serenity-js/core/lib/screenplay/questions/mappings/string~toLowerCase",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay/questions/mappings/string~tonumber",
    "/modules/core/function/src/screenplay/questions/mappings/string/toNumber.ts~toNumber.html",
    "@serenity-js/core/lib/screenplay/questions/mappings/string~toNumber",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay/questions/mappings/string~touppercase",
    "/modules/core/function/src/screenplay/questions/mappings/string/toUpperCase.ts~toUpperCase.html",
    "@serenity-js/core/lib/screenplay/questions/mappings/string~toUpperCase",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay/questions/mappings/string~trim",
    "/modules/core/function/src/screenplay/questions/mappings/string/trim.ts~trim.html",
    "@serenity-js/core/lib/screenplay/questions/mappings/string~trim",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay/questions~note",
    "/modules/core/class/src/screenplay/questions/Note.ts~Note.html",
    "@serenity-js/core/lib/screenplay/questions~Note",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay/questions~transform",
    "/modules/core/class/src/screenplay/questions/Transform.ts~Transform.html",
    "@serenity-js/core/lib/screenplay/questions~Transform",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay/tasks~loop",
    "/modules/core/class/src/screenplay/tasks/Loop.ts~Loop.html",
    "@serenity-js/core/lib/screenplay/tasks~Loop",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay~ability",
    "/modules/core/class/src/screenplay/Ability.ts~Ability.html",
    "@serenity-js/core/lib/screenplay~Ability",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay~abilitytype",
    "/modules/core/class/src/screenplay/AbilityType.ts~AbilityType.html",
    "@serenity-js/core/lib/screenplay~AbilityType",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay~activity",
    "/modules/core/class/src/screenplay/Activity.ts~Activity.html",
    "@serenity-js/core/lib/screenplay~Activity",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay~discardable",
    "/modules/core/class/src/screenplay/Discardable.ts~Discardable.html",
    "@serenity-js/core/lib/screenplay~Discardable",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay~interaction",
    "/modules/core/class/src/screenplay/Interaction.ts~Interaction.html",
    "@serenity-js/core/lib/screenplay~Interaction",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay~question",
    "/modules/core/class/src/screenplay/Question.ts~Question.html",
    "@serenity-js/core/lib/screenplay~Question",
    "external"
  ],
  [
    "@serenity-js/core/lib/screenplay~task",
    "/modules/core/class/src/screenplay/Task.ts~Task.html",
    "@serenity-js/core/lib/screenplay~Task",
    "external"
  ],
  [
    "@serenity-js/core/lib/stage/crew/artifact-archiver~artifactarchiver",
    "/modules/core/class/src/stage/crew/artifact-archiver/ArtifactArchiver.ts~ArtifactArchiver.html",
    "@serenity-js/core/lib/stage/crew/artifact-archiver~ArtifactArchiver",
    "external"
  ],
  [
    "@serenity-js/core/lib/stage/crew/stream-reporter~streamreporter",
    "/modules/core/class/src/stage/crew/stream-reporter/StreamReporter.ts~StreamReporter.html",
    "@serenity-js/core/lib/stage/crew/stream-reporter~StreamReporter",
    "external"
  ],
  [
    "@serenity-js/core/lib/stage~cast",
    "/modules/core/class/src/stage/Cast.ts~Cast.html",
    "@serenity-js/core/lib/stage~Cast",
    "external"
  ],
  [
    "@serenity-js/core/lib/stage~clock",
    "/modules/core/class/src/stage/Clock.ts~Clock.html",
    "@serenity-js/core/lib/stage~Clock",
    "external"
  ],
  [
    "@serenity-js/core/lib/stage~dressingroom",
    "/modules/core/class/src/stage/DressingRoom.ts~DressingRoom.html",
    "@serenity-js/core/lib/stage~DressingRoom",
    "external"
  ],
  [
    "@serenity-js/core/lib/stage~stage",
    "/modules/core/class/src/stage/Stage.ts~Stage.html",
    "@serenity-js/core/lib/stage~Stage",
    "external"
  ],
  [
    "@serenity-js/core/lib/stage~stagecrewmember",
    "/modules/core/class/src/stage/StageCrewMember.ts~StageCrewMember.html",
    "@serenity-js/core/lib/stage~StageCrewMember",
    "external"
  ],
  [
    "@serenity-js/core/lib/stage~stagemanager",
    "/modules/core/class/src/stage/StageManager.ts~StageManager.html",
    "@serenity-js/core/lib/stage~StageManager",
    "external"
  ],
  [
    "@serenity-js/core/lib/stage~withstage",
    "/modules/core/class/src/stage/WithStage.ts~WithStage.html",
    "@serenity-js/core/lib/stage~WithStage",
    "external"
  ],
  [
    "@serenity-js/core~serenity",
    "/modules/core/class/src/Serenity.ts~Serenity.html",
    "@serenity-js/core~Serenity",
    "external"
  ],
  [
    "@serenity-js/core~serenityconfig",
    "/modules/core/class/src/SerenityConfig.ts~SerenityConfig.html",
    "@serenity-js/core~SerenityConfig",
    "external"
  ],
  [
    "@serenity-js/core~actorcalled",
    "/modules/core/function/src/instance.ts~actorCalled.html",
    "@serenity-js/core~actorCalled",
    "external"
  ],
  [
    "@serenity-js/core~actorinthespotlight",
    "/modules/core/function/src/instance.ts~actorInTheSpotlight.html",
    "@serenity-js/core~actorInTheSpotlight",
    "external"
  ],
  [
    "@serenity-js/core~configure",
    "/modules/core/function/src/instance.ts~configure.html",
    "@serenity-js/core~configure",
    "external"
  ],
  [
    "@serenity-js/core~engage",
    "/modules/core/function/src/instance.ts~engage.html",
    "@serenity-js/core~engage",
    "external"
  ],
  [
    "@serenity-js/core~serenity",
    "/modules/core/variable/src/instance.ts~serenity.html",
    "@serenity-js/core~serenity",
    "external"
  ],
  [
    "",
    "test-file/spec/reporting.spec.ts.html#lineNumber12",
    "@serenity-js/local-server",
    "test"
  ],
  [
    "",
    "test-file/spec/reporting.spec.ts.html#lineNumber58",
    "@serenity-js/local-server when managing a local server",
    "test"
  ],
  [
    "",
    "test-file/spec/reporting.spec.ts.html#lineNumber87",
    "@serenity-js/local-server when managing a local server",
    "test"
  ],
  [
    "managealocalserver startlocalserver stoplocalserver src/screenplay/abilities/managealocalserver.ts~managealocalserver,managealocalserver src/screenplay/interactions/startlocalserver.ts~startlocalserver,startlocalserver src/screenplay/interactions/stoplocalserver.ts~stoplocalserver,stoplocalserver",
    "test-file/spec/reporting.spec.ts.html#lineNumber65",
    "@serenity-js/local-server when managing a local server ",
    "test"
  ],
  [
    "",
    "test-file/spec/reporting.spec.ts.html#lineNumber98",
    "@serenity-js/local-server when managing a local server ",
    "test"
  ],
  [
    "@serenity-js/rest/lib/model~deleterequest",
    "/modules/rest/class/src/model/DeleteRequest.ts~DeleteRequest.html",
    "@serenity-js/rest/lib/model~DeleteRequest",
    "external"
  ],
  [
    "@serenity-js/rest/lib/model~getrequest",
    "/modules/rest/class/src/model/GetRequest.ts~GetRequest.html",
    "@serenity-js/rest/lib/model~GetRequest",
    "external"
  ],
  [
    "@serenity-js/rest/lib/model~httprequest",
    "/modules/rest/class/src/model/HTTPRequest.ts~HTTPRequest.html",
    "@serenity-js/rest/lib/model~HTTPRequest",
    "external"
  ],
  [
    "@serenity-js/rest/lib/model~headrequest",
    "/modules/rest/class/src/model/HeadRequest.ts~HeadRequest.html",
    "@serenity-js/rest/lib/model~HeadRequest",
    "external"
  ],
  [
    "@serenity-js/rest/lib/model~optionsrequest",
    "/modules/rest/class/src/model/OptionsRequest.ts~OptionsRequest.html",
    "@serenity-js/rest/lib/model~OptionsRequest",
    "external"
  ],
  [
    "@serenity-js/rest/lib/model~patchrequest",
    "/modules/rest/class/src/model/PatchRequest.ts~PatchRequest.html",
    "@serenity-js/rest/lib/model~PatchRequest",
    "external"
  ],
  [
    "@serenity-js/rest/lib/model~postrequest",
    "/modules/rest/class/src/model/PostRequest.ts~PostRequest.html",
    "@serenity-js/rest/lib/model~PostRequest",
    "external"
  ],
  [
    "@serenity-js/rest/lib/model~putrequest",
    "/modules/rest/class/src/model/PutRequest.ts~PutRequest.html",
    "@serenity-js/rest/lib/model~PutRequest",
    "external"
  ],
  [
    "@serenity-js/rest/lib/screenplay/abilities~callanapi",
    "/modules/rest/class/src/screenplay/abilities/CallAnApi.ts~CallAnApi.html",
    "@serenity-js/rest/lib/screenplay/abilities~CallAnApi",
    "external"
  ],
  [
    "@serenity-js/rest/lib/screenplay/interactions~changeapiconfig",
    "/modules/rest/class/src/screenplay/interactions/ChangeApiConfig.ts~ChangeApiConfig.html",
    "@serenity-js/rest/lib/screenplay/interactions~ChangeApiConfig",
    "external"
  ],
  [
    "@serenity-js/rest/lib/screenplay/interactions~changeapiurl",
    "/modules/rest/class/src/screenplay/interactions/ChangeApiUrl.ts~ChangeApiUrl.html",
    "@serenity-js/rest/lib/screenplay/interactions~ChangeApiUrl",
    "external"
  ],
  [
    "@serenity-js/rest/lib/screenplay/interactions~send",
    "/modules/rest/class/src/screenplay/interactions/Send.ts~Send.html",
    "@serenity-js/rest/lib/screenplay/interactions~Send",
    "external"
  ],
  [
    "@serenity-js/rest/lib/screenplay/questions~lastresponse",
    "/modules/rest/class/src/screenplay/questions/LastResponse.ts~LastResponse.html",
    "@serenity-js/rest/lib/screenplay/questions~LastResponse",
    "external"
  ],
  [
    "axioserror",
    "https://github.com/axios/axios/blob/v0.19.2/index.d.ts#L82",
    "AxiosError",
    "external"
  ],
  [
    "axiosinstance",
    "https://github.com/axios/axios/blob/v0.19.2/index.d.ts#L127",
    "AxiosInstance",
    "external"
  ],
  [
    "axiospromise",
    "https://github.com/axios/axios/blob/v0.19.2/index.d.ts#L91",
    "AxiosPromise",
    "external"
  ],
  [
    "axiosrequestconfig",
    "https://github.com/axios/axios/blob/v0.19.2/index.d.ts#L43",
    "AxiosRequestConfig",
    "external"
  ],
  [
    "axiosresponse",
    "https://github.com/axios/axios/blob/v0.19.2/index.d.ts#L73",
    "AxiosResponse",
    "external"
  ],
  [
    "elementarrayfinder",
    "https://www.protractortest.org/#/api?view=ElementArrayFinder",
    "ElementArrayFinder",
    "external"
  ],
  [
    "elementfinder",
    "https://www.protractortest.org/#/api?view=ElementFinder",
    "ElementFinder",
    "external"
  ],
  [
    "",
    "test-file/spec/restarting.spec.ts.html#lineNumber13",
    "ManageALocalServer",
    "test"
  ],
  [
    "",
    "test-file/spec/servers.spec.ts.html#lineNumber15",
    "ManageALocalServer",
    "test"
  ],
  [
    "managealocalserver src/screenplay/abilities/managealocalserver.ts~managealocalserver,managealocalserver",
    "test-file/spec/restarting.spec.ts.html#lineNumber16",
    "ManageALocalServer restarting",
    "test"
  ],
  [
    "managealocalserver src/screenplay/abilities/managealocalserver.ts~managealocalserver,managealocalserver",
    "test-file/spec/servers.spec.ts.html#lineNumber18",
    "ManageALocalServer when working with HTTP",
    "test"
  ],
  [
    "managealocalserver src/screenplay/abilities/managealocalserver.ts~managealocalserver,managealocalserver",
    "test-file/spec/servers.spec.ts.html#lineNumber115",
    "ManageALocalServer when working with HTTPS",
    "test"
  ],
  [
    "",
    "test-file/spec/servers.spec.ts.html#lineNumber183",
    "ManageALocalServer when working with HTTPS allows the Actor to start, stop and access the location of a HTTPS Hapi app",
    "test"
  ],
  [
    "",
    "test-file/spec/servers.spec.ts.html#lineNumber240",
    "ManageALocalServer when working with HTTPS allows the Actor to start, stop and access the location of a Restify app",
    "test"
  ],
  [
    "protractorbrowser",
    "https://www.protractortest.org/#/api?view=ProtractorBrowser",
    "ProtractorBrowser",
    "external"
  ],
  [
    "localserver.port src/screenplay/questions/localserver.ts~localserver.port,localserver.port",
    "test-file/spec/screenplay/interactions/StartLocalServer.spec.ts.html#lineNumber17",
    "StartALocalServer",
    "test"
  ],
  [
    "selenium-webdriver~actions",
    "https://www.selenium.dev/selenium/docs/api/javascript/module/selenium-webdriver/lib/input_exports_Actions.html",
    "selenium-webdriver~Actions",
    "external"
  ],
  [
    "selenium-webdriver~alertpromise",
    "https://www.selenium.dev/selenium/docs/api/javascript/module/selenium-webdriver/lib/webdriver_exports_AlertPromise.html",
    "selenium-webdriver~AlertPromise",
    "external"
  ],
  [
    "selenium-webdriver~by",
    "https://www.selenium.dev/selenium/docs/api/javascript/module/selenium-webdriver/lib/by_exports_By.html",
    "selenium-webdriver~By",
    "external"
  ],
  [
    "selenium-webdriver~capabilities",
    "https://www.selenium.dev/selenium/docs/api/javascript/module/selenium-webdriver/index_exports_Capabilities.html",
    "selenium-webdriver~Capabilities",
    "external"
  ],
  [
    "selenium-webdriver~navigation",
    "https://www.selenium.dev/selenium/docs/api/javascript/module/selenium-webdriver/lib/webdriver_exports_Navigation.html",
    "selenium-webdriver~Navigation",
    "external"
  ],
  [
    "selenium-webdriver~options",
    "https://www.selenium.dev/selenium/docs/api/javascript/module/selenium-webdriver/ie_exports_Options.html",
    "selenium-webdriver~Options",
    "external"
  ],
  [
    "spec/reporting.spec.ts",
    "test-file/spec/reporting.spec.ts.html",
    "spec/reporting.spec.ts",
    "testFile"
  ],
  [
    "spec/restarting.spec.ts",
    "test-file/spec/restarting.spec.ts.html",
    "spec/restarting.spec.ts",
    "testFile"
  ],
  [
    "spec/screenplay/interactions/startlocalserver.spec.ts",
    "test-file/spec/screenplay/interactions/StartLocalServer.spec.ts.html",
    "spec/screenplay/interactions/StartLocalServer.spec.ts",
    "testFile"
  ],
  [
    "spec/servers.spec.ts",
    "test-file/spec/servers.spec.ts.html",
    "spec/servers.spec.ts",
    "testFile"
  ],
  [
    "spec/setup.spec.ts",
    "test-file/spec/setup.spec.ts.html",
    "spec/setup.spec.ts",
    "testFile"
  ],
  [
    "src/index.ts",
    "file/src/index.ts.html",
    "src/index.ts",
    "file"
  ],
  [
    "src/screenplay/abilities/managealocalserver.ts",
    "file/src/screenplay/abilities/ManageALocalServer.ts.html",
    "src/screenplay/abilities/ManageALocalServer.ts",
    "file"
  ],
  [
    "src/screenplay/abilities/managealocalserver.ts~managealocalserver#constructor",
    "class/src/screenplay/abilities/ManageALocalServer.ts~ManageALocalServer.html#instance-constructor-constructor",
    "src/screenplay/abilities/ManageALocalServer.ts~ManageALocalServer#constructor",
    "method"
  ],
  [
    "src/screenplay/abilities/managealocalserver.ts~managealocalserver#listen",
    "class/src/screenplay/abilities/ManageALocalServer.ts~ManageALocalServer.html#instance-method-listen",
    "src/screenplay/abilities/ManageALocalServer.ts~ManageALocalServer#listen",
    "method"
  ],
  [
    "src/screenplay/abilities/managealocalserver.ts~managealocalserver#mapinstance",
    "class/src/screenplay/abilities/ManageALocalServer.ts~ManageALocalServer.html#instance-method-mapInstance",
    "src/screenplay/abilities/ManageALocalServer.ts~ManageALocalServer#mapInstance",
    "method"
  ],
  [
    "src/screenplay/abilities/managealocalserver.ts~managealocalserver.as",
    "class/src/screenplay/abilities/ManageALocalServer.ts~ManageALocalServer.html#static-method-as",
    "src/screenplay/abilities/ManageALocalServer.ts~ManageALocalServer.as",
    "method"
  ],
  [
    "src/screenplay/abilities/managealocalserver.ts~managealocalserver.runningahttplistener",
    "class/src/screenplay/abilities/ManageALocalServer.ts~ManageALocalServer.html#static-method-runningAHttpListener",
    "src/screenplay/abilities/ManageALocalServer.ts~ManageALocalServer.runningAHttpListener",
    "method"
  ],
  [
    "src/screenplay/abilities/managealocalserver.ts~managealocalserver.runningahttpslistener",
    "class/src/screenplay/abilities/ManageALocalServer.ts~ManageALocalServer.html#static-method-runningAHttpsListener",
    "src/screenplay/abilities/ManageALocalServer.ts~ManageALocalServer.runningAHttpsListener",
    "method"
  ],
  [
    "src/screenplay/abilities/managealocalserver.ts~requestlistener",
    "typedef/index.html#static-typedef-RequestListener",
    "src/screenplay/abilities/ManageALocalServer.ts~RequestListener",
    "typedef"
  ],
  [
    "src/screenplay/abilities/managealocalserver.ts~serverwithshutdown",
    "typedef/index.html#static-typedef-ServerWithShutdown",
    "src/screenplay/abilities/ManageALocalServer.ts~ServerWithShutdown",
    "typedef"
  ],
  [
    "src/screenplay/abilities/managealocalserver.ts~supportedprotocols",
    "typedef/index.html#static-typedef-SupportedProtocols",
    "src/screenplay/abilities/ManageALocalServer.ts~SupportedProtocols",
    "typedef"
  ],
  [
    "src/screenplay/abilities/index.ts",
    "file/src/screenplay/abilities/index.ts.html",
    "src/screenplay/abilities/index.ts",
    "file"
  ],
  [
    "src/screenplay/index.ts",
    "file/src/screenplay/index.ts.html",
    "src/screenplay/index.ts",
    "file"
  ],
  [
    "src/screenplay/interactions/startlocalserver.ts",
    "file/src/screenplay/interactions/StartLocalServer.ts.html",
    "src/screenplay/interactions/StartLocalServer.ts",
    "file"
  ],
  [
    "src/screenplay/interactions/startlocalserver.ts~startlocalserver.ononeofthepreferredports",
    "class/src/screenplay/interactions/StartLocalServer.ts~StartLocalServer.html#static-method-onOneOfThePreferredPorts",
    "src/screenplay/interactions/StartLocalServer.ts~StartLocalServer.onOneOfThePreferredPorts",
    "method"
  ],
  [
    "src/screenplay/interactions/startlocalserver.ts~startlocalserver.onport",
    "class/src/screenplay/interactions/StartLocalServer.ts~StartLocalServer.html#static-method-onPort",
    "src/screenplay/interactions/StartLocalServer.ts~StartLocalServer.onPort",
    "method"
  ],
  [
    "src/screenplay/interactions/startlocalserver.ts~startlocalserver.onrandomport",
    "class/src/screenplay/interactions/StartLocalServer.ts~StartLocalServer.html#static-method-onRandomPort",
    "src/screenplay/interactions/StartLocalServer.ts~StartLocalServer.onRandomPort",
    "method"
  ],
  [
    "src/screenplay/interactions/startlocalserver.ts~startlocalserver.onrandomportbetween",
    "class/src/screenplay/interactions/StartLocalServer.ts~StartLocalServer.html#static-method-onRandomPortBetween",
    "src/screenplay/interactions/StartLocalServer.ts~StartLocalServer.onRandomPortBetween",
    "method"
  ],
  [
    "src/screenplay/interactions/stoplocalserver.ts",
    "file/src/screenplay/interactions/StopLocalServer.ts.html",
    "src/screenplay/interactions/StopLocalServer.ts",
    "file"
  ],
  [
    "src/screenplay/interactions/stoplocalserver.ts~stoplocalserver#performas",
    "class/src/screenplay/interactions/StopLocalServer.ts~StopLocalServer.html#instance-method-performAs",
    "src/screenplay/interactions/StopLocalServer.ts~StopLocalServer#performAs",
    "method"
  ],
  [
    "src/screenplay/interactions/stoplocalserver.ts~stoplocalserver#tostring",
    "class/src/screenplay/interactions/StopLocalServer.ts~StopLocalServer.html#instance-method-toString",
    "src/screenplay/interactions/StopLocalServer.ts~StopLocalServer#toString",
    "method"
  ],
  [
    "src/screenplay/interactions/stoplocalserver.ts~stoplocalserver.ifrunning",
    "class/src/screenplay/interactions/StopLocalServer.ts~StopLocalServer.html#static-method-ifRunning",
    "src/screenplay/interactions/StopLocalServer.ts~StopLocalServer.ifRunning",
    "method"
  ],
  [
    "src/screenplay/interactions/index.ts",
    "file/src/screenplay/interactions/index.ts.html",
    "src/screenplay/interactions/index.ts",
    "file"
  ],
  [
    "src/screenplay/questions/localserver.ts",
    "file/src/screenplay/questions/LocalServer.ts.html",
    "src/screenplay/questions/LocalServer.ts",
    "file"
  ],
  [
    "src/screenplay/questions/localserver.ts~localserver.port",
    "class/src/screenplay/questions/LocalServer.ts~LocalServer.html#static-method-port",
    "src/screenplay/questions/LocalServer.ts~LocalServer.port",
    "method"
  ],
  [
    "src/screenplay/questions/localserver.ts~localserver.url",
    "class/src/screenplay/questions/LocalServer.ts~LocalServer.html#static-method-url",
    "src/screenplay/questions/LocalServer.ts~LocalServer.url",
    "method"
  ],
  [
    "src/screenplay/questions/index.ts",
    "file/src/screenplay/questions/index.ts.html",
    "src/screenplay/questions/index.ts",
    "file"
  ]
]