/** @external {@serenity-js/cucumber/lib/cli~CucumberConfig} /modules/cucumber/class/src/cli/CucumberConfig.ts~CucumberConfig.html */
/** @external {@serenity-js/cucumber/lib/errors~AmbiguousStepDefinitionError} /modules/cucumber/class/src/errors/AmbiguousStepDefinitionError.ts~AmbiguousStepDefinitionError.html */
/** @external {@serenity-js/cucumber/lib/gherkin/nodes~ASTNode} /modules/cucumber/class/src/gherkin/nodes/ASTNode.ts~ASTNode.html */
/** @external {@serenity-js/cucumber/lib/gherkin/nodes~Background} /modules/cucumber/class/src/gherkin/nodes/Background.ts~Background.html */
/** @external {@serenity-js/cucumber/lib/gherkin/nodes~Comment} /modules/cucumber/class/src/gherkin/nodes/Comment.ts~Comment.html */
/** @external {@serenity-js/cucumber/lib/gherkin/nodes~DataTable} /modules/cucumber/class/src/gherkin/nodes/DataTable.ts~DataTable.html */
/** @external {@serenity-js/cucumber/lib/gherkin/nodes~DocString} /modules/cucumber/class/src/gherkin/nodes/DocString.ts~DocString.html */
/** @external {@serenity-js/cucumber/lib/gherkin/nodes~Examples} /modules/cucumber/class/src/gherkin/nodes/Examples.ts~Examples.html */
/** @external {@serenity-js/cucumber/lib/gherkin/nodes~Feature} /modules/cucumber/class/src/gherkin/nodes/Feature.ts~Feature.html */
/** @external {@serenity-js/cucumber/lib/gherkin/nodes~GherkinDocument} /modules/cucumber/class/src/gherkin/nodes/GherkinDocument.ts~GherkinDocument.html */
/** @external {@serenity-js/cucumber/lib/gherkin/nodes~Location} /modules/cucumber/class/src/gherkin/nodes/Location.ts~Location.html */
/** @external {@serenity-js/cucumber/lib/gherkin/nodes~Scenario} /modules/cucumber/class/src/gherkin/nodes/Scenario.ts~Scenario.html */
/** @external {@serenity-js/cucumber/lib/gherkin/nodes~ScenarioDefinition} /modules/cucumber/class/src/gherkin/nodes/ScenarioDefinition.ts~ScenarioDefinition.html */
/** @external {@serenity-js/cucumber/lib/gherkin/nodes~ScenarioOutline} /modules/cucumber/class/src/gherkin/nodes/ScenarioOutline.ts~ScenarioOutline.html */
/** @external {@serenity-js/cucumber/lib/gherkin/nodes~Step} /modules/cucumber/class/src/gherkin/nodes/Step.ts~Step.html */
/** @external {@serenity-js/cucumber/lib/gherkin/nodes~StepArgument} /modules/cucumber/class/src/gherkin/nodes/StepArgument.ts~StepArgument.html */
/** @external {@serenity-js/cucumber/lib/gherkin/nodes~TableCell} /modules/cucumber/class/src/gherkin/nodes/TableCell.ts~TableCell.html */
/** @external {@serenity-js/cucumber/lib/gherkin/nodes~TableRow} /modules/cucumber/class/src/gherkin/nodes/TableRow.ts~TableRow.html */
/** @external {@serenity-js/cucumber/lib/gherkin/nodes~Tag} /modules/cucumber/class/src/gherkin/nodes/Tag.ts~Tag.html */
/** @external {@serenity-js/cucumber/lib/listeners~listenerForCucumber} /modules/cucumber/function/src/listeners/index.ts~listenerForCucumber.html */