import htm from 'htm';
import { h } from 'preact';

import type { RouteDefinition } from '../../router/RouteDefinition.js';
import { DATA } from '../../utils/data.js';
import { link } from '../../utils/link.js';
import { SerenityJsLogo, SerenityJsMark } from './brand.js';
import { icons } from './icons.js';

const html = htm.bind(h);

interface NavItemProps {
    item: RouteDefinition;
    isActive: boolean;
    badge?: number;
    onNavigate: (path: string) => void;
    onClose: () => void;
}

function NavItem({ item, isActive, badge, onNavigate, onClose }: NavItemProps): ReturnType<typeof html> {
    return html`
      <button type="button" class="nav-item ${isActive ? 'active' : ''}"
           title=${item.navLabel}
           aria-current=${isActive ? 'page' : undefined}
           onClick=${() => { onNavigate(item.pattern); onClose(); }}>
        ${item.icon ? icons[item.icon as keyof typeof icons] : null}
        <span>${item.navLabel}</span>
        ${badge && badge > 0 ? html`<span class="nav-badge">${badge}</span>` : null}
      </button>
    `;
}

interface ThemeToggleProps {
    theme: string;
    onSetTheme: (theme: string) => void;
}

function ThemeToggle({ theme, onSetTheme }: ThemeToggleProps): ReturnType<typeof html> {
    const options = ['light', 'system', 'dark'] as const;
    const labels: Record<string, string> = { light: 'Light theme', system: 'System theme', dark: 'Dark theme' };
    const iconMap: Record<string, unknown> = { light: icons.sun, system: icons.system, dark: icons.moon };

    const handleKeyDown = (e: KeyboardEvent) => {
        const currentIndex = options.indexOf(theme as typeof options[number]);
        let nextIndex = -1;
        if (e.key === 'ArrowRight' || e.key === 'ArrowDown') {
            nextIndex = (currentIndex + 1) % options.length;
        } else if (e.key === 'ArrowLeft' || e.key === 'ArrowUp') {
            nextIndex = (currentIndex - 1 + options.length) % options.length;
        }
        if (nextIndex >= 0) {
            e.preventDefault();
            onSetTheme(options[nextIndex]);
            const container = (e.currentTarget as HTMLElement);
            const buttons = container.querySelectorAll('[role="radio"]');
            (buttons[nextIndex] as HTMLElement)?.focus();
        }
    };

    return html`
      <div class="theme-switch" role="radiogroup" aria-label="Theme preference" onKeyDown=${handleKeyDown}>
        ${options.map(opt => html`
          <button class="theme-switch-option${theme === opt ? ' active' : ''}"
                  onClick=${() => onSetTheme(opt)}
                  aria-checked=${String(theme === opt)}
                  tabIndex=${theme === opt ? 0 : -1}
                  role="radio" title=${labels[opt]}>
            ${iconMap[opt]}
          </button>
        `)}
      </div>
    `;
}

interface SidebarProps {
    route: string;
    routes: RouteDefinition[];
    sidebarOpen: boolean;
    collapsed: boolean;
    failedBadgeCount: number;
    routeMatched?: boolean;
    onNavigate: (path: string) => void;
    onClose: () => void;
    onToggleCollapse: () => void;
    theme: string;
    onSetTheme: (theme: string) => void;
}

export function Sidebar({ route, routes, sidebarOpen, collapsed, failedBadgeCount, routeMatched, onNavigate, onClose, onToggleCollapse, theme, onSetTheme }: SidebarProps): ReturnType<typeof html> {
    const navItems = routes.filter(r => r.navLabel && r.pattern !== '/about');
    const aboutRoute = routes.find(r => r.pattern === '/about');

    const isActive = (path: string) => {
        if (path === '/') return route === '/' || route === '' || routeMatched === false;
        return route.startsWith(path);
    };

    const getBadge = (r: RouteDefinition): number => {
        if (!r.badge) return 0;
        return r.badge(DATA);
    };

    return html`
    <aside class="sidebar ${sidebarOpen ? 'open' : ''} ${collapsed ? 'collapsed' : ''}" aria-label="Site navigation">
      <div class="sidebar-brand clickable" onClick=${() => { onNavigate(link({ view: 'dashboard' })); onClose(); }}>
        ${SerenityJsLogo}
        ${SerenityJsMark}
      </div>
      <nav class="sidebar-nav">
        ${navItems.map(item => html`
          <${NavItem} item=${item} isActive=${isActive(item.pattern)} badge=${getBadge(item)}
                      onNavigate=${onNavigate} onClose=${onClose} />
        `)}
        ${aboutRoute ? html`
          <${NavItem} item=${aboutRoute} isActive=${isActive('/about')}
                      onNavigate=${onNavigate} onClose=${onClose} />
        ` : null}
        <a href="https://serenity-js.org" target="_blank" class="nav-item" title="This report was generated by Serenity/JS — learn more at serenity-js.org" style="color:var(--text-sidebar);text-decoration:none;margin-top:var(--space-sm);border-top:1px solid rgba(255,255,255,0.08);padding-top:var(--space-md)">
          ${icons.learn}
          <span>Learn Serenity/JS</span>
        </a>
      </nav>
      <div class="sidebar-footer">
        <div class="sidebar-controls">
          <${ThemeToggle} theme=${theme} onSetTheme=${onSetTheme} />
          <button class="sidebar-collapse-btn" onClick=${onToggleCollapse} title=${collapsed ? 'Expand sidebar' : 'Collapse sidebar'} aria-label=${collapsed ? 'Expand sidebar' : 'Collapse sidebar'}>
            ${collapsed ? icons.sidebarExpand : icons.sidebarCollapse}
          </button>
        </div>
        <div class="sidebar-copyright">Serenity/JS © 2016–${new Date().getFullYear()} <a href="https://www.linkedin.com/in/janmolak/" target="_blank">Jan Molak</a><br />Made with 💛 in London, UK</div>
      </div>
    </aside>
  `;
}
