import htm from 'htm';
import { h } from 'preact';

import type { RouteDefinition } from '../../router/RouteDefinition';
import { DATA } from '../../utils';
import { SerenityJsLogo, SerenityJsMark } from './brand';
import { icons } from './icons';

const html = htm.bind(h);

interface SidebarProps {
    route: string;
    routes: RouteDefinition[];
    sidebarOpen: boolean;
    collapsed: boolean;
    failedBadgeCount: number;
    onNavigate: (path: string) => void;
    onClose: () => void;
    onToggleCollapse: () => void;
    theme: string;
    onSetTheme: (theme: string) => void;
}

export function Sidebar({ route, routes, sidebarOpen, collapsed, failedBadgeCount, onNavigate, onClose, onToggleCollapse, theme, onSetTheme }: SidebarProps): ReturnType<typeof html> {
    const navItems = routes.filter(r => r.navLabel && r.pattern !== '/about');
    const aboutRoute = routes.find(r => r.pattern === '/about');

    const isActive = (path: string) => {
        if (path === '/') return route === '/' || route === '';
        return route.startsWith(path);
    };

    const getBadge = (r: RouteDefinition): number => {
        if (!r.badge) return 0;
        return r.badge(DATA);
    };

    return html`
    <aside class="sidebar ${sidebarOpen ? 'open' : ''} ${collapsed ? 'collapsed' : ''}">
      <div class="sidebar-brand clickable" onClick=${() => { onNavigate('/'); onClose(); }}>
        ${SerenityJsLogo}
        ${SerenityJsMark}
      </div>
      <nav class="sidebar-nav">
        ${navItems.map(item => {
            const badge = getBadge(item);
            return html`
          <button type="button" class="nav-item ${isActive(item.pattern) ? 'active' : ''}"
               title=${item.navLabel}
               aria-current=${isActive(item.pattern) ? 'page' : undefined}
               onClick=${() => { onNavigate(item.pattern); onClose(); }}>
            ${item.icon ? icons[item.icon as keyof typeof icons] : null}
            <span>${item.navLabel}</span>
            ${badge > 0 ? html`<span class="nav-badge">${badge}</span>` : null}
          </button>
        `;
        })}
        ${aboutRoute ? html`
          <button type="button" class="nav-item ${isActive('/about') ? 'active' : ''}"
               title=${aboutRoute.navLabel}
               aria-current=${isActive('/about') ? 'page' : undefined}
               onClick=${() => { onNavigate('/about'); onClose(); }}>
            ${aboutRoute.icon ? icons[aboutRoute.icon as keyof typeof icons] : null}
            <span>${aboutRoute.navLabel}</span>
          </button>
        ` : null}
        <a href="https://serenity-js.org" target="_blank" class="nav-item" title="This report was generated by Serenity/JS — learn more at serenity-js.org" style="color:var(--text-sidebar);text-decoration:none;margin-top:var(--space-sm);border-top:1px solid rgba(255,255,255,0.08);padding-top:var(--space-md)">
          ${icons.learn}
          <span>Learn Serenity/JS</span>
        </a>
      </nav>
      <div class="sidebar-footer">
        <div class="sidebar-controls">
          <div class="theme-switch" role="radiogroup" aria-label="Theme preference">
            <button class="theme-switch-option${theme === 'light' ? ' active' : ''}" onClick=${() => onSetTheme('light')} aria-checked=${theme === 'light'} role="radio" title="Light theme">
              ${icons.sun}
            </button>
            <button class="theme-switch-option${theme === 'system' ? ' active' : ''}" onClick=${() => onSetTheme('system')} aria-checked=${theme === 'system'} role="radio" title="System theme">
              ${icons.system}
            </button>
            <button class="theme-switch-option${theme === 'dark' ? ' active' : ''}" onClick=${() => onSetTheme('dark')} aria-checked=${theme === 'dark'} role="radio" title="Dark theme">
              ${icons.moon}
            </button>
          </div>
          <button class="sidebar-collapse-btn" onClick=${onToggleCollapse} title=${collapsed ? 'Expand sidebar' : 'Collapse sidebar'} aria-label=${collapsed ? 'Expand sidebar' : 'Collapse sidebar'}>
            ${collapsed ? icons.sidebarExpand : icons.sidebarCollapse}
          </button>
        </div>
        <div class="sidebar-copyright">Serenity/JS © 2016–${new Date().getFullYear()} <a href="https://www.linkedin.com/in/janmolak/" target="_blank">Jan Molak</a><br />Made with 💛 in London</div>
      </div>
    </aside>
  `;
}
