/** @external {@serenity-js/webdriverio/lib/adapter~WebdriverIOConfig} /modules/webdriverio/class/src/adapter/WebdriverIOConfig.ts~WebdriverIOConfig.html */
/** @external {@serenity-js/webdriverio/lib/expectations~isActive} /modules/webdriverio/function/index.html#static-function-isActive */
/** @external {@serenity-js/webdriverio/lib/expectations~isClickable} /modules/webdriverio/function/index.html#static-function-isClickable */
/** @external {@serenity-js/webdriverio/lib/expectations~isEnabled} /modules/webdriverio/function/index.html#static-function-isEnabled */
/** @external {@serenity-js/webdriverio/lib/expectations~isPresent} /modules/webdriverio/function/index.html#static-function-isPresent */
/** @external {@serenity-js/webdriverio/lib/expectations~isSelected} /modules/webdriverio/function/index.html#static-function-isSelected */
/** @external {@serenity-js/webdriverio/lib/expectations~isVisible} /modules/webdriverio/function/index.html#static-function-isVisible */
/** @external {@serenity-js/webdriverio/lib/input~Key} /modules/webdriverio/class/src/input/Key.ts~Key.html */
/** @external {@serenity-js/webdriverio/lib/screenplay/abilities~BrowseTheWeb} /modules/webdriverio/class/src/screenplay/abilities/BrowseTheWeb.ts~BrowseTheWeb.html */
/** @external {@serenity-js/webdriverio/lib/screenplay/interactions~Clear} /modules/webdriverio/class/src/screenplay/interactions/Clear.ts~Clear.html */
/** @external {@serenity-js/webdriverio/lib/screenplay/interactions~Click} /modules/webdriverio/class/src/screenplay/interactions/Click.ts~Click.html */
/** @external {@serenity-js/webdriverio/lib/screenplay/interactions~DoubleClick} /modules/webdriverio/class/src/screenplay/interactions/DoubleClick.ts~DoubleClick.html */
/** @external {@serenity-js/webdriverio/lib/screenplay/interactions~Enter} /modules/webdriverio/class/src/screenplay/interactions/Enter.ts~Enter.html */
/** @external {@serenity-js/webdriverio/lib/screenplay/interactions~EnterBuilder} /modules/webdriverio/class/src/screenplay/interactions/EnterBuilder.ts~EnterBuilder.html */
/** @external {@serenity-js/webdriverio/lib/screenplay/interactions~ExecuteScript} /modules/webdriverio/class/src/screenplay/interactions/ExecuteScript.ts~ExecuteScript.html */
/** @external {@serenity-js/webdriverio/lib/screenplay/interactions~ExecuteScriptWithArguments} /modules/webdriverio/class/src/screenplay/interactions/ExecuteScript.ts~ExecuteScriptWithArguments.html */
/** @external {@serenity-js/webdriverio/lib/screenplay/interactions~Hover} /modules/webdriverio/class/src/screenplay/interactions/Hover.ts~Hover.html */
/** @external {@serenity-js/webdriverio/lib/screenplay/interactions~Navigate} /modules/webdriverio/class/src/screenplay/interactions/Navigate.ts~Navigate.html */
/** @external {@serenity-js/webdriverio/lib/screenplay/interactions~Press} /modules/webdriverio/class/src/screenplay/interactions/Press.ts~Press.html */
/** @external {@serenity-js/webdriverio/lib/screenplay/interactions~PressBuilder} /modules/webdriverio/class/src/screenplay/interactions/PressBuilder.ts~PressBuilder.html */
/** @external {@serenity-js/webdriverio/lib/screenplay/interactions~RightClick} /modules/webdriverio/class/src/screenplay/interactions/RightClick.ts~RightClick.html */
/** @external {@serenity-js/webdriverio/lib/screenplay/interactions~Wait} /modules/webdriverio/class/src/screenplay/interactions/Wait.ts~Wait.html */
/** @external {@serenity-js/webdriverio/lib/screenplay/interactions~WaitBuilder} /modules/webdriverio/class/src/screenplay/interactions/WaitBuilder.ts~WaitBuilder.html */
/** @external {@serenity-js/webdriverio/lib/screenplay/interactions~WebElementInteraction} /modules/webdriverio/class/src/screenplay/interactions/WebElementInteraction.ts~WebElementInteraction.html */
/** @external {@serenity-js/webdriverio/lib/screenplay/questions~Attribute} /modules/webdriverio/class/src/screenplay/questions/Attribute.ts~Attribute.html */
/** @external {@serenity-js/webdriverio/lib/screenplay/questions~CSSClasses} /modules/webdriverio/class/src/screenplay/questions/CSSClasses.ts~CSSClasses.html */
/** @external {@serenity-js/webdriverio/lib/screenplay/questions~LastScriptExecution} /modules/webdriverio/class/src/screenplay/questions/LastScriptExecution.ts~LastScriptExecution.html */
/** @external {@serenity-js/webdriverio/lib/screenplay/questions~NestedTargetBuilder} /modules/webdriverio/class/src/screenplay/questions/NestedTargetBuilder.ts~NestedTargetBuilder.html */
/** @external {@serenity-js/webdriverio/lib/screenplay/questions~TargetBuilder} /modules/webdriverio/class/src/screenplay/questions/TargetBuilder.ts~TargetBuilder.html */
/** @external {@serenity-js/webdriverio/lib/screenplay/questions~Text} /modules/webdriverio/class/src/screenplay/questions/Text.ts~Text.html */
/** @external {@serenity-js/webdriverio/lib/screenplay/questions~Value} /modules/webdriverio/class/src/screenplay/questions/Value.ts~Value.html */
/** @external {@serenity-js/webdriverio/lib/screenplay/questions~Website} /modules/webdriverio/class/src/screenplay/questions/Website.ts~Website.html */
/** @external {@serenity-js/webdriverio/lib/screenplay/questions~ElementArrayListAdapter} /modules/webdriverio/class/src/screenplay/questions/lists.ts~ElementArrayListAdapter.html */
/** @external {@serenity-js/webdriverio/lib/screenplay/questions~Locator} /modules/webdriverio/class/src/screenplay/questions/locators.ts~Locator.html */
/** @external {@serenity-js/webdriverio/lib/screenplay/questions~Locators} /modules/webdriverio/class/src/screenplay/questions/locators.ts~Locators.html */
/** @external {@serenity-js/webdriverio/lib/screenplay/questions~by} /modules/webdriverio/variable/src/screenplay/questions/locators.ts~by.html */
/** @external {@serenity-js/webdriverio/lib/screenplay/questions~Target} /modules/webdriverio/class/src/screenplay/questions/targets.ts~Target.html */
/** @external {@serenity-js/webdriverio/lib/screenplay/questions~TargetElements} /modules/webdriverio/class/src/screenplay/questions/targets.ts~TargetElements.html */
/** @external {@serenity-js/webdriverio/lib/screenplay/questions~TargetNestedElements} /modules/webdriverio/class/src/screenplay/questions/targets.ts~TargetNestedElements.html */
/** @external {@serenity-js/webdriverio/lib/screenplay/questions~TargetElement} /modules/webdriverio/class/src/screenplay/questions/targets.ts~TargetElement.html */
/** @external {@serenity-js/webdriverio/lib/screenplay/questions~TargetNestedElement} /modules/webdriverio/class/src/screenplay/questions/targets.ts~TargetNestedElement.html */
/** @external {@serenity-js/webdriverio/lib/stage/crew/photographer~Photographer} /modules/webdriverio/class/src/stage/crew/photographer/Photographer.ts~Photographer.html */
/** @external {@serenity-js/webdriverio/lib/stage/crew/photographer/strategies~PhotoTakingStrategy} /modules/webdriverio/class/src/stage/crew/photographer/strategies/PhotoTakingStrategy.ts~PhotoTakingStrategy.html */
/** @external {@serenity-js/webdriverio/lib/stage/crew/photographer/strategies~TakePhotosBeforeAndAfterInteractions} /modules/webdriverio/class/src/stage/crew/photographer/strategies/TakePhotosBeforeAndAfterInteractions.ts~TakePhotosBeforeAndAfterInteractions.html */
/** @external {@serenity-js/webdriverio/lib/stage/crew/photographer/strategies~TakePhotosOfFailures} /modules/webdriverio/class/src/stage/crew/photographer/strategies/TakePhotosOfFailures.ts~TakePhotosOfFailures.html */
/** @external {@serenity-js/webdriverio/lib/stage/crew/photographer/strategies~TakePhotosOfInteractions} /modules/webdriverio/class/src/stage/crew/photographer/strategies/TakePhotosOfInteractions.ts~TakePhotosOfInteractions.html */