/** @external {@serenity-js/protractor/lib/adapter~Config} /modules/protractor/class/src/adapter/Config.ts~Config.html */
/** @external {@serenity-js/protractor/lib/adapter~run} /modules/protractor/function/index.html#static-function-run */
/** @external {@serenity-js/protractor/lib/adapter/runner~CucumberAdapterConfig} /modules/protractor/class/src/adapter/runner/CucumberAdapterConfig.ts~CucumberAdapterConfig.html */
/** @external {@serenity-js/protractor/lib/adapter/runner~TestRunnerDetector} /modules/protractor/class/src/adapter/runner/TestRunnerDetector.ts~TestRunnerDetector.html */
/** @external {@serenity-js/protractor/lib/adapter/runner~TestRunnerLoader} /modules/protractor/class/src/adapter/runner/TestRunnerLoader.ts~TestRunnerLoader.html */
/** @external {@serenity-js/protractor/lib/expectations~isActive} /modules/protractor/function/index.html#static-function-isActive */
/** @external {@serenity-js/protractor/lib/expectations~isClickable} /modules/protractor/function/index.html#static-function-isClickable */
/** @external {@serenity-js/protractor/lib/expectations~isEnabled} /modules/protractor/function/index.html#static-function-isEnabled */
/** @external {@serenity-js/protractor/lib/expectations~isPresent} /modules/protractor/function/index.html#static-function-isPresent */
/** @external {@serenity-js/protractor/lib/expectations~isSelected} /modules/protractor/function/index.html#static-function-isSelected */
/** @external {@serenity-js/protractor/lib/expectations~isVisible} /modules/protractor/function/index.html#static-function-isVisible */
/** @external {@serenity-js/protractor/lib/screenplay/abilities~BrowseTheWeb} /modules/protractor/class/src/screenplay/abilities/BrowseTheWeb.ts~BrowseTheWeb.html */
/** @external {@serenity-js/protractor/lib/screenplay/interactions~Accept} /modules/protractor/class/src/screenplay/interactions/Accept.ts~Accept.html */
/** @external {@serenity-js/protractor/lib/screenplay/interactions~Clear} /modules/protractor/class/src/screenplay/interactions/Clear.ts~Clear.html */
/** @external {@serenity-js/protractor/lib/screenplay/interactions~Click} /modules/protractor/class/src/screenplay/interactions/Click.ts~Click.html */
/** @external {@serenity-js/protractor/lib/screenplay/interactions~Close} /modules/protractor/class/src/screenplay/interactions/Close.ts~Close.html */
/** @external {@serenity-js/protractor/lib/screenplay/interactions~DeleteCookies} /modules/protractor/class/src/screenplay/interactions/DeleteCookies.ts~DeleteCookies.html */
/** @external {@serenity-js/protractor/lib/screenplay/interactions~Dismiss} /modules/protractor/class/src/screenplay/interactions/Dismiss.ts~Dismiss.html */
/** @external {@serenity-js/protractor/lib/screenplay/interactions~DoubleClick} /modules/protractor/class/src/screenplay/interactions/DoubleClick.ts~DoubleClick.html */
/** @external {@serenity-js/protractor/lib/screenplay/interactions~Enter} /modules/protractor/class/src/screenplay/interactions/Enter.ts~Enter.html */
/** @external {@serenity-js/protractor/lib/screenplay/interactions~EnterBuilder} /modules/protractor/class/src/screenplay/interactions/EnterBuilder.ts~EnterBuilder.html */
/** @external {@serenity-js/protractor/lib/screenplay/interactions~ExecuteScript} /modules/protractor/class/src/screenplay/interactions/ExecuteScript.ts~ExecuteScript.html */
/** @external {@serenity-js/protractor/lib/screenplay/interactions~ExecuteScriptWithArguments} /modules/protractor/class/src/screenplay/interactions/ExecuteScript.ts~ExecuteScriptWithArguments.html */
/** @external {@serenity-js/protractor/lib/screenplay/interactions~Hover} /modules/protractor/class/src/screenplay/interactions/Hover.ts~Hover.html */
/** @external {@serenity-js/protractor/lib/screenplay/interactions~Navigate} /modules/protractor/class/src/screenplay/interactions/Navigate.ts~Navigate.html */
/** @external {@serenity-js/protractor/lib/screenplay/interactions~Press} /modules/protractor/class/src/screenplay/interactions/Press.ts~Press.html */
/** @external {@serenity-js/protractor/lib/screenplay/interactions~PressBuilder} /modules/protractor/class/src/screenplay/interactions/PressBuilder.ts~PressBuilder.html */
/** @external {@serenity-js/protractor/lib/screenplay/interactions~ResizeBrowserWindow} /modules/protractor/class/src/screenplay/interactions/ResizeBrowserWindow.ts~ResizeBrowserWindow.html */
/** @external {@serenity-js/protractor/lib/screenplay/interactions~RightClick} /modules/protractor/class/src/screenplay/interactions/RightClick.ts~RightClick.html */
/** @external {@serenity-js/protractor/lib/screenplay/interactions~Scroll} /modules/protractor/class/src/screenplay/interactions/Scroll.ts~Scroll.html */
/** @external {@serenity-js/protractor/lib/screenplay/interactions~Select} /modules/protractor/class/src/screenplay/interactions/Select.ts~Select.html */
/** @external {@serenity-js/protractor/lib/screenplay/interactions~SelectBuilder} /modules/protractor/class/src/screenplay/interactions/SelectBuilder.ts~SelectBuilder.html */
/** @external {@serenity-js/protractor/lib/screenplay/interactions~Switch} /modules/protractor/class/src/screenplay/interactions/Switch.ts~Switch.html */
/** @external {@serenity-js/protractor/lib/screenplay/interactions~TakeScreenshot} /modules/protractor/class/src/screenplay/interactions/TakeScreenshot.ts~TakeScreenshot.html */
/** @external {@serenity-js/protractor/lib/screenplay/interactions~UseAngular} /modules/protractor/class/src/screenplay/interactions/UseAngular.ts~UseAngular.html */
/** @external {@serenity-js/protractor/lib/screenplay/interactions~Wait} /modules/protractor/class/src/screenplay/interactions/Wait.ts~Wait.html */
/** @external {@serenity-js/protractor/lib/screenplay/interactions~WaitBuilder} /modules/protractor/class/src/screenplay/interactions/WaitBuilder.ts~WaitBuilder.html */
/** @external {@serenity-js/protractor/lib/screenplay/questions~Attribute} /modules/protractor/class/src/screenplay/questions/Attribute.ts~Attribute.html */
/** @external {@serenity-js/protractor/lib/screenplay/questions~Browser} /modules/protractor/class/src/screenplay/questions/Browser.ts~Browser.html */
/** @external {@serenity-js/protractor/lib/screenplay/questions~CSSClasses} /modules/protractor/class/src/screenplay/questions/CSSClasses.ts~CSSClasses.html */
/** @external {@serenity-js/protractor/lib/screenplay/questions~Cookie} /modules/protractor/class/src/screenplay/questions/Cookie.ts~Cookie.html */
/** @external {@serenity-js/protractor/lib/screenplay/questions~LastScriptExecution} /modules/protractor/class/src/screenplay/questions/LastScriptExecution.ts~LastScriptExecution.html */
/** @external {@serenity-js/protractor/lib/screenplay/questions~ModalDialog} /modules/protractor/class/src/screenplay/questions/ModalDialog.ts~ModalDialog.html */
/** @external {@serenity-js/protractor/lib/screenplay/questions~Pick} /modules/protractor/class/src/screenplay/questions/Pick.ts~Pick.html */
/** @external {@serenity-js/protractor/lib/screenplay/questions~ProtractorParam} /modules/protractor/class/src/screenplay/questions/ProtractorParam.ts~ProtractorParam.html */
/** @external {@serenity-js/protractor/lib/screenplay/questions~Selected} /modules/protractor/class/src/screenplay/questions/Selected.ts~Selected.html */
/** @external {@serenity-js/protractor/lib/screenplay/questions~Value} /modules/protractor/class/src/screenplay/questions/Value.ts~Value.html */
/** @external {@serenity-js/protractor/lib/screenplay/questions~Website} /modules/protractor/class/src/screenplay/questions/Website.ts~Website.html */
/** @external {@serenity-js/protractor/lib/screenplay/questions~Window} /modules/protractor/class/src/screenplay/questions/Window.ts~Window.html */
/** @external {@serenity-js/protractor/lib/screenplay/questions/lists~ElementArrayFinderListAdapter} /modules/protractor/class/src/screenplay/questions/lists/ElementArrayFinderListAdapter.ts~ElementArrayFinderListAdapter.html */
/** @external {@serenity-js/protractor/lib/screenplay/questions/targets~Target} /modules/protractor/class/src/screenplay/questions/targets/Target.ts~Target.html */
/** @external {@serenity-js/protractor/lib/screenplay/questions/targets~TargetElement} /modules/protractor/class/src/screenplay/questions/targets/TargetElement.ts~TargetElement.html */
/** @external {@serenity-js/protractor/lib/screenplay/questions/targets~TargetElements} /modules/protractor/class/src/screenplay/questions/targets/TargetElements.ts~TargetElements.html */
/** @external {@serenity-js/protractor/lib/screenplay/questions/targets~TargetNestedElement} /modules/protractor/class/src/screenplay/questions/targets/TargetNestedElement.ts~TargetNestedElement.html */
/** @external {@serenity-js/protractor/lib/screenplay/questions/targets~TargetNestedElements} /modules/protractor/class/src/screenplay/questions/targets/TargetNestedElements.ts~TargetNestedElements.html */
/** @external {@serenity-js/protractor/lib/screenplay/questions/text~Text} /modules/protractor/class/src/screenplay/questions/text/Text.ts~Text.html */
/** @external {@serenity-js/protractor/lib/stage/crew/photographer~Photographer} /modules/protractor/class/src/stage/crew/photographer/Photographer.ts~Photographer.html */
/** @external {@serenity-js/protractor/lib/stage/crew/photographer/strategies~PhotoTakingStrategy} /modules/protractor/class/src/stage/crew/photographer/strategies/PhotoTakingStrategy.ts~PhotoTakingStrategy.html */
/** @external {@serenity-js/protractor/lib/stage/crew/photographer/strategies~TakePhotosBeforeAndAfterInteractions} /modules/protractor/class/src/stage/crew/photographer/strategies/TakePhotosBeforeAndAfterInteractions.ts~TakePhotosBeforeAndAfterInteractions.html */
/** @external {@serenity-js/protractor/lib/stage/crew/photographer/strategies~TakePhotosOfFailures} /modules/protractor/class/src/stage/crew/photographer/strategies/TakePhotosOfFailures.ts~TakePhotosOfFailures.html */
/** @external {@serenity-js/protractor/lib/stage/crew/photographer/strategies~TakePhotosOfInteractions} /modules/protractor/class/src/stage/crew/photographer/strategies/TakePhotosOfInteractions.ts~TakePhotosOfInteractions.html */