module.exports = {
    community: [
        { type: 'autogenerated', dirName: '.' },
        {
            type: 'link',
            label: 'Serenity/JS Forum',
            href: 'https://github.com/orgs/serenity-js/discussions',
        },
        {
            type: 'link',
            label: 'Serenity/JS Chat',
            href: 'https://matrix.to/#/#serenity-js:gitter.im',
        }
    ],
};
