/** @external {@serenity-js/core~Serenity} /modules/core/class/src/Serenity.ts~Serenity.html */
/** @external {@serenity-js/core~SerenityConfig} /modules/core/class/src/SerenityConfig.ts~SerenityConfig.html */
/** @external {@serenity-js/core/lib/errors~AssertionError} /modules/core/class/src/errors/AssertionError.ts~AssertionError.html */
/** @external {@serenity-js/core/lib/errors~ConfigurationError} /modules/core/class/src/errors/ConfigurationError.ts~ConfigurationError.html */
/** @external {@serenity-js/core/lib/errors~ImplementationPendingError} /modules/core/class/src/errors/ImplementationPendingError.ts~ImplementationPendingError.html */
/** @external {@serenity-js/core/lib/errors~LogicError} /modules/core/class/src/errors/LogicError.ts~LogicError.html */
/** @external {@serenity-js/core/lib/errors~RuntimeError} /modules/core/class/src/errors/RuntimeError.ts~RuntimeError.html */
/** @external {@serenity-js/core/lib/errors~TestCompromisedError} /modules/core/class/src/errors/TestCompromisedError.ts~TestCompromisedError.html */
/** @external {@serenity-js/core/lib/errors~UnknownError} /modules/core/class/src/errors/UnknownError.ts~UnknownError.html */
/** @external {@serenity-js/core/lib/events~ActivityFinished} /modules/core/class/src/events/ActivityFinished.ts~ActivityFinished.html */
/** @external {@serenity-js/core/lib/events~ActivityRelatedArtifactArchived} /modules/core/class/src/events/ActivityRelatedArtifactArchived.ts~ActivityRelatedArtifactArchived.html */
/** @external {@serenity-js/core/lib/events~ActivityRelatedArtifactGenerated} /modules/core/class/src/events/ActivityRelatedArtifactGenerated.ts~ActivityRelatedArtifactGenerated.html */
/** @external {@serenity-js/core/lib/events~ActivityStarts} /modules/core/class/src/events/ActivityStarts.ts~ActivityStarts.html */
/** @external {@serenity-js/core/lib/events~ArtifactArchived} /modules/core/class/src/events/ArtifactArchived.ts~ArtifactArchived.html */
/** @external {@serenity-js/core/lib/events~ArtifactGenerated} /modules/core/class/src/events/ArtifactGenerated.ts~ArtifactGenerated.html */
/** @external {@serenity-js/core/lib/events~AsyncOperationAttempted} /modules/core/class/src/events/AsyncOperationAttempted.ts~AsyncOperationAttempted.html */
/** @external {@serenity-js/core/lib/events~AsyncOperationCompleted} /modules/core/class/src/events/AsyncOperationCompleted.ts~AsyncOperationCompleted.html */
/** @external {@serenity-js/core/lib/events~AsyncOperationFailed} /modules/core/class/src/events/AsyncOperationFailed.ts~AsyncOperationFailed.html */
/** @external {@serenity-js/core/lib/events~BusinessRuleDetected} /modules/core/class/src/events/BusinessRuleDetected.ts~BusinessRuleDetected.html */
/** @external {@serenity-js/core/lib/events~DomainEvent} /modules/core/class/src/events/DomainEvent.ts~DomainEvent.html */
/** @external {@serenity-js/core/lib/events~FeatureNarrativeDetected} /modules/core/class/src/events/FeatureNarrativeDetected.ts~FeatureNarrativeDetected.html */
/** @external {@serenity-js/core/lib/events~InteractionFinished} /modules/core/class/src/events/InteractionFinished.ts~InteractionFinished.html */
/** @external {@serenity-js/core/lib/events~InteractionStarts} /modules/core/class/src/events/InteractionStarts.ts~InteractionStarts.html */
/** @external {@serenity-js/core/lib/events~SceneBackgroundDetected} /modules/core/class/src/events/SceneBackgroundDetected.ts~SceneBackgroundDetected.html */
/** @external {@serenity-js/core/lib/events~SceneDescriptionDetected} /modules/core/class/src/events/SceneDescriptionDetected.ts~SceneDescriptionDetected.html */
/** @external {@serenity-js/core/lib/events~SceneFinished} /modules/core/class/src/events/SceneFinished.ts~SceneFinished.html */
/** @external {@serenity-js/core/lib/events~SceneFinishes} /modules/core/class/src/events/SceneFinishes.ts~SceneFinishes.html */
/** @external {@serenity-js/core/lib/events~SceneParametersDetected} /modules/core/class/src/events/SceneParametersDetected.ts~SceneParametersDetected.html */
/** @external {@serenity-js/core/lib/events~SceneSequenceDetected} /modules/core/class/src/events/SceneSequenceDetected.ts~SceneSequenceDetected.html */
/** @external {@serenity-js/core/lib/events~SceneStarts} /modules/core/class/src/events/SceneStarts.ts~SceneStarts.html */
/** @external {@serenity-js/core/lib/events~SceneTagged} /modules/core/class/src/events/SceneTagged.ts~SceneTagged.html */
/** @external {@serenity-js/core/lib/events~SceneTemplateDetected} /modules/core/class/src/events/SceneTemplateDetected.ts~SceneTemplateDetected.html */
/** @external {@serenity-js/core/lib/events~TaskFinished} /modules/core/class/src/events/TaskFinished.ts~TaskFinished.html */
/** @external {@serenity-js/core/lib/events~TaskStarts} /modules/core/class/src/events/TaskStarts.ts~TaskStarts.html */
/** @external {@serenity-js/core/lib/events~TestRunFinished} /modules/core/class/src/events/TestRunFinished.ts~TestRunFinished.html */
/** @external {@serenity-js/core/lib/events~TestRunFinishes} /modules/core/class/src/events/TestRunFinishes.ts~TestRunFinishes.html */
/** @external {@serenity-js/core/lib/events~TestRunStarts} /modules/core/class/src/events/TestRunStarts.ts~TestRunStarts.html */
/** @external {@serenity-js/core/lib/events~TestRunnerDetected} /modules/core/class/src/events/TestRunnerDetected.ts~TestRunnerDetected.html */
/** @external {@serenity-js/core/lib/events~TestSuiteFinished} /modules/core/class/src/events/TestSuiteFinished.ts~TestSuiteFinished.html */
/** @external {@serenity-js/core/lib/events~TestSuiteStarts} /modules/core/class/src/events/TestSuiteStarts.ts~TestSuiteStarts.html */
/** @external {@serenity-js/core~serenity} /modules/core/variable/src/instance.ts~serenity.html */
/** @external {@serenity-js/core~configure} /modules/core/function/index.html#static-function-configure */
/** @external {@serenity-js/core~engage} /modules/core/function/index.html#static-function-engage */
/** @external {@serenity-js/core~actorCalled} /modules/core/function/index.html#static-function-actorCalled */
/** @external {@serenity-js/core~actorInTheSpotlight} /modules/core/function/index.html#static-function-actorInTheSpotlight */
/** @external {@serenity-js/core/lib/io~AssertionReportDiffer} /modules/core/class/src/io/AssertionReportDiffer.ts~AssertionReportDiffer.html */
/** @external {@serenity-js/core/lib/io~Config} /modules/core/class/src/io/Config.ts~Config.html */
/** @external {@serenity-js/core/lib/io~SerialisedError} /modules/core/class/src/io/ErrorSerialiser.ts~SerialisedError.html */
/** @external {@serenity-js/core/lib/io~ErrorSerialiser} /modules/core/class/src/io/ErrorSerialiser.ts~ErrorSerialiser.html */
/** @external {@serenity-js/core/lib/io~FileFinder} /modules/core/class/src/io/FileFinder.ts~FileFinder.html */
/** @external {@serenity-js/core/lib/io~FileSystem} /modules/core/class/src/io/FileSystem.ts~FileSystem.html */
/** @external {@serenity-js/core/lib/io~FileSystemLocation} /modules/core/class/src/io/FileSystemLocation.ts~FileSystemLocation.html */
/** @external {@serenity-js/core/lib/io~ModuleLoader} /modules/core/class/src/io/ModuleLoader.ts~ModuleLoader.html */
/** @external {@serenity-js/core/lib/io~Path} /modules/core/class/src/io/Path.ts~Path.html */
/** @external {@serenity-js/core/lib/io~TestRunnerAdapter} /modules/core/class/src/io/TestRunnerAdapter.ts~TestRunnerAdapter.html */
/** @external {@serenity-js/core/lib/io~Version} /modules/core/class/src/io/Version.ts~Version.html */
/** @external {@serenity-js/core/lib/io/collections~Mappable} /modules/core/class/src/io/collections/mappable.ts~Mappable.html */
/** @external {@serenity-js/core/lib/io/collections~isMappable} /modules/core/function/index.html#static-function-isMappable */
/** @external {@serenity-js/core/lib/io/collections~Reducible} /modules/core/class/src/io/collections/reducible.ts~Reducible.html */
/** @external {@serenity-js/core/lib/io~commaSeparated} /modules/core/function/index.html#static-function-commaSeparated */
/** @external {@serenity-js/core/lib/io~formatted} /modules/core/function/index.html#static-function-formatted */
/** @external {@serenity-js/core/lib/io~inspected} /modules/core/function/index.html#static-function-inspected */
/** @external {@serenity-js/core/lib/io/json~stringify} /modules/core/function/index.html#static-function-stringify */
/** @external {@serenity-js/core/lib/io/json~parse} /modules/core/function/index.html#static-function-parse */
/** @external {@serenity-js/core/lib/io~trimmed} /modules/core/function/index.html#static-function-trimmed */
/** @external {@serenity-js/core/lib/model~ActivityDetails} /modules/core/class/src/model/ActivityDetails.ts~ActivityDetails.html */
/** @external {@serenity-js/core/lib/model~Artifact} /modules/core/class/src/model/Artifact.ts~Artifact.html */
/** @external {@serenity-js/core/lib/model~BusinessRule} /modules/core/class/src/model/BusinessRule.ts~BusinessRule.html */
/** @external {@serenity-js/core/lib/model~Category} /modules/core/class/src/model/Category.ts~Category.html */
/** @external {@serenity-js/core/lib/model~CorrelationId} /modules/core/class/src/model/CorrelationId.ts~CorrelationId.html */
/** @external {@serenity-js/core/lib/model~Description} /modules/core/class/src/model/Description.ts~Description.html */
/** @external {@serenity-js/core/lib/model~Duration} /modules/core/class/src/model/Duration.ts~Duration.html */
/** @external {@serenity-js/core/lib/model~Name} /modules/core/class/src/model/Name.ts~Name.html */
/** @external {@serenity-js/core/lib/model~ScenarioDetails} /modules/core/class/src/model/ScenarioDetails.ts~ScenarioDetails.html */
/** @external {@serenity-js/core/lib/model~ScenarioParameters} /modules/core/class/src/model/ScenarioParameters.ts~ScenarioParameters.html */
/** @external {@serenity-js/core/lib/model~TestSuiteDetails} /modules/core/class/src/model/TestSuiteDetails.ts~TestSuiteDetails.html */
/** @external {@serenity-js/core/lib/model~Timestamp} /modules/core/class/src/model/Timestamp.ts~Timestamp.html */
/** @external {@serenity-js/core/lib/model/artifacts~AssertionReport} /modules/core/class/src/model/artifacts/AssertionReport.ts~AssertionReport.html */
/** @external {@serenity-js/core/lib/model/artifacts~RequestAndResponse} /modules/core/class/src/model/artifacts/HTTPRequestResponse.ts~RequestAndResponse.html */
/** @external {@serenity-js/core/lib/model/artifacts~HTTPRequestResponse} /modules/core/class/src/model/artifacts/HTTPRequestResponse.ts~HTTPRequestResponse.html */
/** @external {@serenity-js/core/lib/model/artifacts~JSONData} /modules/core/class/src/model/artifacts/JSONData.ts~JSONData.html */
/** @external {@serenity-js/core/lib/model/artifacts~LogEntry} /modules/core/class/src/model/artifacts/LogEntry.ts~LogEntry.html */
/** @external {@serenity-js/core/lib/model/artifacts~Photo} /modules/core/class/src/model/artifacts/Photo.ts~Photo.html */
/** @external {@serenity-js/core/lib/model/artifacts~TestReport} /modules/core/class/src/model/artifacts/TestReport.ts~TestReport.html */
/** @external {@serenity-js/core/lib/model/artifacts~TextData} /modules/core/class/src/model/artifacts/TextData.ts~TextData.html */
/** @external {@serenity-js/core/lib/model~Outcome} /modules/core/class/src/model/outcomes.ts~Outcome.html */
/** @external {@serenity-js/core/lib/model~ProblemIndication} /modules/core/class/src/model/outcomes.ts~ProblemIndication.html */
/** @external {@serenity-js/core/lib/model~ExecutionCompromised} /modules/core/class/src/model/outcomes.ts~ExecutionCompromised.html */
/** @external {@serenity-js/core/lib/model~ExecutionFailedWithError} /modules/core/class/src/model/outcomes.ts~ExecutionFailedWithError.html */
/** @external {@serenity-js/core/lib/model~ExecutionFailedWithAssertionError} /modules/core/class/src/model/outcomes.ts~ExecutionFailedWithAssertionError.html */
/** @external {@serenity-js/core/lib/model~ImplementationPending} /modules/core/class/src/model/outcomes.ts~ImplementationPending.html */
/** @external {@serenity-js/core/lib/model~ExecutionIgnored} /modules/core/class/src/model/outcomes.ts~ExecutionIgnored.html */
/** @external {@serenity-js/core/lib/model~ExecutionSkipped} /modules/core/class/src/model/outcomes.ts~ExecutionSkipped.html */
/** @external {@serenity-js/core/lib/model~ExecutionSuccessful} /modules/core/class/src/model/outcomes.ts~ExecutionSuccessful.html */
/** @external {@serenity-js/core/lib/model/tags~ArbitraryTag} /modules/core/class/src/model/tags/ArbitraryTag.ts~ArbitraryTag.html */
/** @external {@serenity-js/core/lib/model/tags~BrowserTag} /modules/core/class/src/model/tags/BrowserTag.ts~BrowserTag.html */
/** @external {@serenity-js/core/lib/model/tags~CapabilityTag} /modules/core/class/src/model/tags/CapabilityTag.ts~CapabilityTag.html */
/** @external {@serenity-js/core/lib/model/tags~ContextTag} /modules/core/class/src/model/tags/ContextTag.ts~ContextTag.html */
/** @external {@serenity-js/core/lib/model/tags~ExecutionRetriedTag} /modules/core/class/src/model/tags/ExecutionRetriedTag.ts~ExecutionRetriedTag.html */
/** @external {@serenity-js/core/lib/model/tags~FeatureTag} /modules/core/class/src/model/tags/FeatureTag.ts~FeatureTag.html */
/** @external {@serenity-js/core/lib/model/tags~IssueTag} /modules/core/class/src/model/tags/IssueTag.ts~IssueTag.html */
/** @external {@serenity-js/core/lib/model/tags~ManualTag} /modules/core/class/src/model/tags/ManualTag.ts~ManualTag.html */
/** @external {@serenity-js/core/lib/model/tags~PlatformTag} /modules/core/class/src/model/tags/PlatformTag.ts~PlatformTag.html */
/** @external {@serenity-js/core/lib/model/tags~Tag} /modules/core/class/src/model/tags/Tag.ts~Tag.html */
/** @external {@serenity-js/core/lib/model/tags~ThemeTag} /modules/core/class/src/model/tags/ThemeTag.ts~ThemeTag.html */
/** @external {@serenity-js/core/lib/screenplay~Ability} /modules/core/class/src/screenplay/Ability.ts~Ability.html */
/** @external {@serenity-js/core/lib/screenplay~AbilityType} /modules/core/class/src/screenplay/AbilityType.ts~AbilityType.html */
/** @external {@serenity-js/core/lib/screenplay~Activity} /modules/core/class/src/screenplay/Activity.ts~Activity.html */
/** @external {@serenity-js/core/lib/screenplay~Interaction} /modules/core/class/src/screenplay/Interaction.ts~Interaction.html */
/** @external {@serenity-js/core/lib/screenplay~Question} /modules/core/class/src/screenplay/Question.ts~Question.html */
/** @external {@serenity-js/core/lib/screenplay~Task} /modules/core/class/src/screenplay/Task.ts~Task.html */
/** @external {@serenity-js/core/lib/screenplay/abilities~Discardable} /modules/core/class/src/screenplay/abilities/Discardable.ts~Discardable.html */
/** @external {@serenity-js/core/lib/screenplay/abilities~Initialisable} /modules/core/class/src/screenplay/abilities/Initialisable.ts~Initialisable.html */
/** @external {@serenity-js/core/lib/screenplay/abilities~TakeNotes} /modules/core/class/src/screenplay/abilities/TakeNotes.ts~TakeNotes.html */
/** @external {@serenity-js/core/lib/screenplay/actor~Actor} /modules/core/class/src/screenplay/actor/Actor.ts~Actor.html */
/** @external {@serenity-js/core/lib/screenplay/actor~AnswersQuestions} /modules/core/class/src/screenplay/actor/AnswersQuestions.ts~AnswersQuestions.html */
/** @external {@serenity-js/core/lib/screenplay/actor~CanHaveAbilities} /modules/core/class/src/screenplay/actor/CanHaveAbilities.ts~CanHaveAbilities.html */
/** @external {@serenity-js/core/lib/screenplay/actor~CollectsArtifacts} /modules/core/class/src/screenplay/actor/CollectsArtifacts.ts~CollectsArtifacts.html */
/** @external {@serenity-js/core/lib/screenplay/actor~ListensToDomainEvents} /modules/core/class/src/screenplay/actor/ListensToDomainEvents.ts~ListensToDomainEvents.html */
/** @external {@serenity-js/core/lib/screenplay/actor~PerformsActivities} /modules/core/class/src/screenplay/actor/PerformsActivities.ts~PerformsActivities.html */
/** @external {@serenity-js/core/lib/screenplay/actor~UsesAbilities} /modules/core/class/src/screenplay/actor/UsesAbilities.ts~UsesAbilities.html */
/** @external {@serenity-js/core/lib/screenplay/interactions~Log} /modules/core/class/src/screenplay/interactions/Log.ts~Log.html */
/** @external {@serenity-js/core/lib/screenplay/interactions~See} /modules/core/class/src/screenplay/interactions/See.ts~See.html */
/** @external {@serenity-js/core/lib/screenplay/interactions~TakeNote} /modules/core/class/src/screenplay/interactions/TakeNote.ts~TakeNote.html */
/** @external {@serenity-js/core/lib/screenplay/questions~Note} /modules/core/class/src/screenplay/questions/Note.ts~Note.html */
/** @external {@serenity-js/core/lib/screenplay/questions~Transform} /modules/core/class/src/screenplay/questions/Transform.ts~Transform.html */
/** @external {@serenity-js/core/lib/screenplay/questions/mappings/string~append} /modules/core/function/index.html#static-function-append */
/** @external {@serenity-js/core/lib/screenplay/questions/mappings/string~normalize} /modules/core/function/index.html#static-function-normalize */
/** @external {@serenity-js/core/lib/screenplay/questions/mappings/string~replace} /modules/core/function/index.html#static-function-replace */
/** @external {@serenity-js/core/lib/screenplay/questions/mappings/string~slice} /modules/core/function/index.html#static-function-slice */
/** @external {@serenity-js/core/lib/screenplay/questions/mappings/string~split} /modules/core/function/index.html#static-function-split */
/** @external {@serenity-js/core/lib/screenplay/questions/mappings/string~toLocaleLowerCase} /modules/core/function/index.html#static-function-toLocaleLowerCase */
/** @external {@serenity-js/core/lib/screenplay/questions/mappings/string~toLocaleUpperCase} /modules/core/function/index.html#static-function-toLocaleUpperCase */
/** @external {@serenity-js/core/lib/screenplay/questions/mappings/string~toLowerCase} /modules/core/function/index.html#static-function-toLowerCase */
/** @external {@serenity-js/core/lib/screenplay/questions/mappings/string~toNumber} /modules/core/function/index.html#static-function-toNumber */
/** @external {@serenity-js/core/lib/screenplay/questions/mappings/string~toUpperCase} /modules/core/function/index.html#static-function-toUpperCase */
/** @external {@serenity-js/core/lib/screenplay/questions/mappings/string~trim} /modules/core/function/index.html#static-function-trim */
/** @external {@serenity-js/core/lib/screenplay/questions~q} /modules/core/function/index.html#static-function-q */
/** @external {@serenity-js/core/lib/screenplay/tasks~Loop} /modules/core/class/src/screenplay/tasks/Loop.ts~Loop.html */
/** @external {@serenity-js/core/lib/stage~Cast} /modules/core/class/src/stage/Cast.ts~Cast.html */
/** @external {@serenity-js/core/lib/stage~Clock} /modules/core/class/src/stage/Clock.ts~Clock.html */
/** @external {@serenity-js/core/lib/stage~DressingRoom} /modules/core/class/src/stage/DressingRoom.ts~DressingRoom.html */
/** @external {@serenity-js/core/lib/stage~Stage} /modules/core/class/src/stage/Stage.ts~Stage.html */
/** @external {@serenity-js/core/lib/stage~StageCrewMember} /modules/core/class/src/stage/StageCrewMember.ts~StageCrewMember.html */
/** @external {@serenity-js/core/lib/stage~StageManager} /modules/core/class/src/stage/StageManager.ts~StageManager.html */
/** @external {@serenity-js/core/lib/stage~WithStage} /modules/core/class/src/stage/WithStage.ts~WithStage.html */
/** @external {@serenity-js/core/lib/stage/crew/artifact-archiver~ArtifactArchiver} /modules/core/class/src/stage/crew/artifact-archiver/ArtifactArchiver.ts~ArtifactArchiver.html */
/** @external {@serenity-js/core/lib/stage/crew/stream-reporter~StreamReporter} /modules/core/class/src/stage/crew/stream-reporter/StreamReporter.ts~StreamReporter.html */