name: Test

on:
  workflow_call:
    input:
      name:
        type: string
        required: true
        description: Name of the job
      node-version:
        type: string
        required: true
        description: Node.js version, e.g. 16.x
      install-command:
        type: string
        description: The command to install Node modules
        default: "npm ci"
      test-command:
        type: string
        description: The command to run the tests, e.g. npm test
        required: true
      artifact:
        type: string
        description: The name of the artifact with test results, e.g. test-reports
        required: true


permissions:
  contents: read

jobs:
  test:
    name: ${{ inputs.name }}
    runs-on:  ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ inputs.node-version }}

      - name: Install Node Modules (@serenity-js)
        uses: bahmutov/npm-install@v1
        with:
          install-command: ${{ inputs.install-command }}
        env:
          CHROMEDRIVER_FILEPATH: "/usr/bin/chromedriver"

      - name: Download compiled libs
        uses: actions/download-artifact@v2
        with:
          name: compiled-libs
      - name: Decompress Libs
        run:  7z x -aoa compiled-libs.zip

      - name: Test
        run: ${{ inputs.test-command }}

      - uses: actions/upload-artifact@v2
        with:
          retention-days: 3
          name: ${{ inputs.artifact-name }}
          path: |
            target/**/*
            package.json
