name: Website

on:
  workflow_call:

permissions:
  contents: write

jobs:

  website-build-and-deploy:
    runs-on: ubuntu-latest
    concurrency: ci-${{ github.ref }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install Node Modules (site)
        uses: bahmutov/npm-install@v1
        with:
          install-command: make BOOTSTRAP_SCOPE=site install

      - name: Build serenity-js.org website
        run: make site

      # Debug website
      - name: Compress website
        run: 7z a serenity-js-website.zip "documentation/serenity-js.org/build"
      - uses: actions/upload-artifact@v2
        with:
          retention-days: 3
          name: website
          path: |
            serenity-js-website.zip

  #      - name: Publish website
  #        uses: JamesIves/github-pages-deploy-action@v4.3.0
  #        if: github.ref == 'refs/heads/main'
  #        with:
  #          BRANCH: gh-pages
  #          FOLDER: documentation/serenity-js.org/build
  #          CLEAN: true
