name: Main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize ]

permissions:
  contents: read

jobs:

  lint:
    name: 'Lint'
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - name: Set up Node
        uses: ./.github/actions/setup-node
      - name: Lint
        run: make lint

  compile:
    name: 'Compile'
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - name: Set up Node
        uses: ./.github/actions/setup-node
      - name: Compile
        run: make COMPILE_SCOPE=libs compile
      - name: Upload compiled libs
        uses: ./.github/actions/upload-compressed-artifact
        with:
          artifact-name: 'compiled-libs'
          artifact-path: 'package.json "integration/*/lib/*" "integration/*/esm/*" "packages/*/lib/*" "packages/*/esm/*" "packages/serenity-bdd/cache/*"'

  #
  # Test
  #

  test-linux-node-lts-active:
    name: 'Test: Linux, LTS'
    needs:
      - lint
      - compile
    runs-on: ubuntu-24.04
    permissions:
      checks: write
      contents: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - name: Set up Node
        uses: ./.github/actions/setup-node
      - name: Download compiled libs
        uses: ./.github/actions/download-compressed-artifact
        with:
          artifact-name: 'compiled-libs'
      - name: Test
        run: make test
      - name: Qlty
        uses: qltysh/qlty-action/coverage@fd52dc852530a708d68c3b7342f8d33d1df4cd55 # v2.2.1
        with:
          oidc: true
          command: publish
          files: packages/*/target/coverage/lcov.info
          incomplete: true

  test-linux-node-lts-maintenance:
    name: 'Test: Linux, LTS-1'
    needs:
      - lint
      - compile
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - name: Set up Node
        uses: ./.github/actions/setup-node
        with:
          node-version: 22.x
      - name: Download compiled libs
        uses: ./.github/actions/download-compressed-artifact
        with:
          artifact-name: 'compiled-libs'
      - name: Test
        run: make test-no-coverage

  test-windows-node-lts-active:
    name: 'Test: Windows, LTS'
    needs:
      - lint
      - compile
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - name: Set up Node
        uses: ./.github/actions/setup-node
      - name: Download compiled libs
        uses: ./.github/actions/download-compressed-artifact
        with:
          artifact-name: 'compiled-libs'
      - name: Test
        run: make test-no-coverage

  #
  # Integration
  #

  test-integration-playwright:
    name: 'Integration: Playwright'
    needs:
      - lint
      - compile
    runs-on: ubuntu-24.04
    permissions:
      checks: write
      contents: read
      id-token: write
    strategy:
      matrix:
        module:
          - html-reporter
          - playwright-electron
          - playwright-test
          - playwright-test-ct
          - playwright-web
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - name: Set up Node
        uses: ./.github/actions/setup-node
      - name: Set up Java
        uses: ./.github/actions/setup-java
      - name: Download compiled libs
        uses: ./.github/actions/download-compressed-artifact
        with:
          artifact-name: 'compiled-libs'
      - name: Test
        run: |
          mkdir target && \
          make INTEGRATION_SCOPE=${{ matrix.module }} integration-test
      - name: Upload html-report data
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: 'html-report-data-${{ matrix.module }}'
          path: integration/*/target/html-report/test-runs/
          retention-days: 3
          if-no-files-found: ignore
      - name: Upload test reports
        if: failure()
        uses: ./.github/actions/upload-compressed-artifact
        with:
          artifact-name: 'test-integration-reports-${{ matrix.module }}'
          artifact-path: 'package.json "integration/*/target/site/serenity"'
      - name: Qlty
        uses: qltysh/qlty-action/coverage@fd52dc852530a708d68c3b7342f8d33d1df4cd55 # v2.2.1
        with:
          oidc: true
          command: publish
          files: integration/*/target/coverage/lcov.info
          incomplete: true

  test-integration-protractor:
    name: 'Integration: Protractor'
    needs:
      - lint
      - compile
    runs-on: ubuntu-24.04
    permissions:
      checks: write
      contents: read
      id-token: write
    strategy:
      matrix:
        module:
          - protractor-test-runners
          - protractor-web
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - name: Set up Node
        uses: ./.github/actions/setup-node
      - name: Set up Java
        uses: ./.github/actions/setup-java
      - name: Download compiled libs
        uses: ./.github/actions/download-compressed-artifact
        with:
          artifact-name: 'compiled-libs'
      - name: Test
        run: |
          mkdir target && \
          make INTEGRATION_SCOPE=${{ matrix.module }} integration-test
      - name: Upload html-report data
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: 'html-report-data-${{ matrix.module }}'
          path: integration/*/target/html-report/test-runs/
          retention-days: 3
          if-no-files-found: ignore
      - name: Upload test reports
        if: failure()
        uses: ./.github/actions/upload-compressed-artifact
        with:
          artifact-name: 'test-integration-reports-${{ matrix.module }}'
          artifact-path: 'package.json "integration/*/target/site/serenity"'
      - name: Qlty
        uses: qltysh/qlty-action/coverage@fd52dc852530a708d68c3b7342f8d33d1df4cd55 # v2.2.1
        with:
          oidc: true
          command: publish
          files: integration/*/target/coverage/lcov.info
          incomplete: true

  test-integration-webdriverio:
    name: 'Integration: WebdriverIO'
    needs:
      - lint
      - compile
    runs-on: ubuntu-24.04
    permissions:
      checks: write
      contents: read
      id-token: write
    strategy:
      matrix:
        module:
          - webdriverio-8-test-runners
          - webdriverio-8-web-devtools
          - webdriverio-8-web-webdriver
          - webdriverio-test-runners
          - webdriverio-web
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - name: Set up Node
        uses: ./.github/actions/setup-node
      - name: Set up Java
        uses: ./.github/actions/setup-java
      - name: Download compiled libs
        uses: ./.github/actions/download-compressed-artifact
        with:
          artifact-name: 'compiled-libs'
      - name: Test
        run: |
          mkdir target && \
          make INTEGRATION_SCOPE=${{ matrix.module }} integration-test
      - name: Upload html-report data
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: 'html-report-data-${{ matrix.module }}'
          path: integration/*/target/html-report/test-runs/
          retention-days: 3
          if-no-files-found: ignore
      - name: Upload test reports
        if: failure()
        uses: ./.github/actions/upload-compressed-artifact
        with:
          artifact-name: 'test-integration-reports-${{ matrix.module }}'
          artifact-path: 'package.json "integration/*/target"'
      - name: Qlty
        uses: qltysh/qlty-action/coverage@fd52dc852530a708d68c3b7342f8d33d1df4cd55 # v2.2.1
        with:
          oidc: true
          command: publish
          files: integration/*/target/coverage/lcov.info
          incomplete: true

  test-integration:
    name: 'Integration'
    needs:
      - lint
      - compile
    runs-on: ubuntu-24.04
    permissions:
      checks: write
      contents: read
      id-token: write
    strategy:
      matrix:
        module:
          - cucumber-1
          - cucumber-2
          - cucumber-3
          - cucumber-4
          - cucumber-5
          - cucumber-6
          - cucumber-7
          - cucumber-8
          - cucumber-9
          - cucumber-10
          - cucumber-11
          - cucumber-12
          - cucumber-13
          - jasmine
          - jasmine-5
          - mocha
          - rest
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - name: Set up Node
        uses: ./.github/actions/setup-node
      - name: Download compiled libs
        uses: ./.github/actions/download-compressed-artifact
        with:
          artifact-name: 'compiled-libs'
      - name: Test
        run: |
          mkdir target && \
          make INTEGRATION_SCOPE=${{ matrix.module }} integration-test
      - name: Upload html-report data
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: 'html-report-data-${{ matrix.module }}'
          path: integration/*/target/html-report/test-runs/
          retention-days: 3
          if-no-files-found: ignore
      - name: Qlty
        uses: qltysh/qlty-action/coverage@fd52dc852530a708d68c3b7342f8d33d1df4cd55 # v2.2.1
        with:
          oidc: true
          command: publish
          files: integration/*/target/coverage/lcov.info
          incomplete: true

  #
  # Reporting
  #

  coverage:
    name: 'Coverage'
    needs:
      - test-linux-node-lts-active
      - test-integration
      - test-integration-playwright
      - test-integration-protractor
      - test-integration-webdriverio
    runs-on: ubuntu-24.04
    permissions:
      checks: write
      contents: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Qlty
        uses: qltysh/qlty-action/coverage@fd52dc852530a708d68c3b7342f8d33d1df4cd55 # v2.2.1
        with:
          oidc: true
          command: complete

  #
  # NPM artifact publishing
  #

  html-report:
    name: 'HTML Report: aggregate'
    if: always()
    needs:
      - test-integration
      - test-integration-playwright
      - test-integration-protractor
      - test-integration-webdriverio
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - name: Set up Node
        uses: ./.github/actions/setup-node
      - name: Download compiled libs
        uses: ./.github/actions/download-compressed-artifact
        with:
          artifact-name: 'compiled-libs'
      - name: Download html-report data
        uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e # v4
        with:
          pattern: 'html-report-data-*'
          path: target/html-report-data
          merge-multiple: true
      - name: Generate report
        run: |
          ./packages/html-reporter/bin/html-reporter.mjs \
            --input "target/html-report-data/**/test-runs/*" \
            --output ./target/html-report \
            --title "Serenity/JS Integration Tests" \
            --specRoot integration
      - name: Upload HTML report
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: 'html-report'
          path: target/html-report/
          retention-days: 14

  artifacts-publish:
    name: 'NPM: publish artifacts'
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: write
      id-token: write
    runs-on: ubuntu-24.04
    needs:
      - test-linux-node-lts-active
      - test-linux-node-lts-maintenance
      - test-windows-node-lts-active
      - test-integration
      - test-integration-playwright
      - test-integration-protractor
      - test-integration-webdriverio
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup-lerna
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          git_user_email: ${{ secrets.RELEASE_GH_EMAIL }}
          git_username: ${{ secrets.RELEASE_GH_USERNAME }}

      - name: Download compiled libs
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          name: compiled-libs
      - name: Decompress Libs
        run: 7z x -aoa compiled-libs.zip

      - name: Set up Node
        uses: ./.github/actions/setup-node

      - name: Publish artifacts
        run: pnpm lerna:publish
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Print versions
        run: pnpm version:print >> $GITHUB_STEP_SUMMARY
